### ISSUE TITLE
Egeria, Atlas & IGC proxy fail to initialize in cohort

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1028]
When testing current helm charts with VDC I hit an error whereby the igx proxy failed to join the cohort.

The reported error is:
```
2019-05-14 12:01:22.236 ERROR 1 --- [nio-8080-exec-8] o.o.o.r.m.OMRSCohortManager              : Unable to initialize cohort manager

org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:805) ~[kafka-clients-2.1.1.jar!/:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:652) ~[kafka-clients-2.1.1.jar!/:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:632) ~[kafka-clients-2.1.1.jar!/:na]
	at org.odpi.openmetadata.adapters.eventbus.topic.kafka.KafkaOpenMetadataEventConsumer.<init>(KafkaOpenMetadataEventConsumer.java:74) ~[kafka-open-metadata-topic-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.eventbus.topic.kafka.KafkaOpenMetadataTopicConnector.start(KafkaOpenMetadataTopicConnector.java:219) ~[kafka-open-metadata-topic-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.start(OMRSTopicConnector.java:252) ~[repository-services-apis-1.1-SNAPSHOT.jar!/:na]
```

The full log : 
See https://gist.github.com/766bd716ae925e07288bbc012550e3dd

This is in a configuration where, for egeria, IBM Event streams is being used - ie an external kafka provider with security. The errror looks like it may be JAAS related as part of the error is
```
Caused by: java.lang.IllegalArgumentException: Value not specified for key 'null' in JAAS config
```
I then checked egeria and atlas, and see the same error on these components too

**Comment by planetf1** [comment]
Most likely this is an issue in the helm templating for kafka config. Potentially a lost change...

**Comment by planetf1** [comment]
This has been addressed. This bug was secondary to the main issue (credentials) but showed up due to incorrect quoting of the strings.
