### ISSUE TITLE
Egeria-IGC-connectivity issues - Part I - Connectivity to IGC can't be restored after IGC restart

### ISSUE THREAD

**Issue by jan-frommann** [odpi/egeria#1132]
Hi ODPI Egeria team, 

I deployed Egeria on a dedicated Kubernetes cluster on the IBM Cloud (Yellow zone). Between the cluster and the IGC (Blue Zone) is a firewall, which was configured to allow communication. Everything seemed to work fine until the IGC was restarted. From that point on, it was neither possible to exchange information (Glossary or assets), nor has the connection ever recovered. Purging and reinstalling the helm chart restores the working state, but naturally leads to losing all assets, that have been transferred up to this point. Here is a piece of the IGC pod log:

2019-06-12 15:13:20.623 ERROR 1 --- [       Thread-4] o.o.o.a.r.i.clientlibrary.IGCRestClient  : Request failed -- check IGC environment connectivity and authentication details.

org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Internal Server Error
	at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:79) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:124) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:579) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.makeRequest(IGCRestClient.java:435) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.makeRequest(IGCRestClient.java:467) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.searchJson(IGCRestClient.java:558) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.search(IGCRestClient.java:569) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.model.common.Reference.getAssetWithSubsetOfProperties(Reference.java:134) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.model.common.Reference.getAssetWithSubsetOfProperties(Reference.java:151) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.repositoryconnector.IGCOMRSMetadataCollection.getFullAssetDetails(IGCOMRSMetadataCollection.java:4176) [igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processAsset(IGCOMRSRepositoryEventMapper.java:556) [igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processAssetEventV115(IGCOMRSRepositoryEventMapper.java:354) [igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processEventV115(IGCOMRSRepositoryEventMapper.java:278) [igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processEvent(IGCOMRSRepositoryEventMapper.java:238) [igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper$IGCKafkaConsumerThread.run(IGCOMRSRepositoryEventMapper.java:204) [igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]

2019-06-12 15:13:20.624 ERROR 1 --- [       Thread-4] o.o.o.a.r.i.clientlibrary.IGCRestClient  : Unable to complete request -- check IGC environment connectivity and authentication details.
2019-06-12 15:13:20.624 ERROR 1 --- [       Thread-4] o.o.a.r.i.e.IGCOMRSRepositoryEventMapper : Failed trying to consume IGC events from Kafka.

java.lang.NullPointerException: Unable to complete request -- check IGC environment connectivity and authentication details.
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.makeRequest(IGCRestClient.java:477) ~[igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.searchJson(IGCRestClient.java:558) ~[igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.search(IGCRestClient.java:569) ~[igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.model.common.Reference.getAssetWithSubsetOfProperties(Reference.java:134) ~[igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.model.common.Reference.getAssetWithSubsetOfProperties(Reference.java:151) ~[igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.repositoryconnector.IGCOMRSMetadataCollection.getFullAssetDetails(IGCOMRSMetadataCollection.java:4176) ~[igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processAsset(IGCOMRSRepositoryEventMapper.java:556) ~[igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processAssetEventV115(IGCOMRSRepositoryEventMapper.java:354) ~[igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processEventV115(IGCOMRSRepositoryEventMapper.java:278) ~[igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processEvent(IGCOMRSRepositoryEventMapper.java:238) ~[igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper$IGCKafkaConsumerThread.run(IGCOMRSRepositoryEventMapper.java:204) ~[igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]

2019-06-12 15:13:20.625  WARN 1 --- [       Thread-4] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-1, groupId=IGCOMRSRepositoryEventMapper_consumer] Synchronous auto-commit of offsets {InfosphereEvents-0=OffsetAndMetadata{offset=4398, leaderEpoch=null, metadata=''}} failed: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.
2019-06-12 15:13:20.625  INFO 1 --- [       Thread-4] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-1, groupId=IGCOMRSRepositoryEventMapper_consumer] Revoking previously assigned partitions [InfosphereEvents-0]
2019-06-12 15:13:20.625  INFO 1 --- [       Thread-4] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=IGCOMRSRepositoryEventMapper_consumer] (Re-)joining group
2019-06-12 15:13:20.625  INFO 1 --- [       Thread-4] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=IGCOMRSRepositoryEventMapper_consumer] Group coordinator xxxxxxx.xxx.xxx:59092 (id: 2147483646 rack: null) is unavailable or invalid, will attempt rediscovery
2019-06-12 15:13:21.221  INFO 1 --- [       Thread-4] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=IGCOMRSRepositoryEventMapper_consumer] Discovered group coordinator xxxxxxx.xxx.xxx:59092 (id: 2147483646 rack: null)
2019-06-12 15:13:21.222  INFO 1 --- [       Thread-4] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=IGCOMRSRepositoryEventMapper_consumer] (Re-)joining group
2019-06-12 15:13:21.817  INFO 1 --- [       Thread-4] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=IGCOMRSRepositoryEventMapper_consumer] Successfully joined group with generation 1
2019-06-12 15:13:21.817  INFO 1 --- [       Thread-4] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-1, groupId=IGCOMRSRepositoryEventMapper_consumer] Setting newly assigned partitions [InfosphereEvents-0]
2019-06-12 15:13:26.308  WARN 1 --- [       Thread-4] o.o.o.a.r.i.clientlibrary.IGCRestClient  : Request failed -- session may have expired, retrying...

org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:79) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:579) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.makeRequest(IGCRestClient.java:435) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.makeRequest(IGCRestClient.java:467) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.searchJson(IGCRestClient.java:558) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.search(IGCRestClient.java:569) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.model.common.Reference.getAssetWithSubsetOfProperties(Reference.java:134) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.model.common.Reference.getAssetWithSubsetOfProperties(Reference.java:151) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.repositoryconnector.IGCOMRSMetadataCollection.getFullAssetDetails(IGCOMRSMetadataCollection.java:4176) [igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processAsset(IGCOMRSRepositoryEventMapper.java:556) [igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processAssetEventV115(IGCOMRSRepositoryEventMapper.java:354) [igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processEventV115(IGCOMRSRepositoryEventMapper.java:278) [igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processEvent(IGCOMRSRepositoryEventMapper.java:238) [igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper$IGCKafkaConsumerThread.run(IGCOMRSRepositoryEventMapper.java:204) [igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]

2019-06-12 15:13:47.991  WARN 1 --- [       Thread-4] o.o.o.a.r.i.clientlibrary.IGCRestClient  : Request failed -- session may have expired, retrying...

org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:79) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:579) ~[spring-web-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.makeRequest(IGCRestClient.java:435) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.openNewSessionWithRequest(IGCRestClient.java:215) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.makeRequest(IGCRestClient.java:444) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.makeRequest(IGCRestClient.java:467) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.searchJson(IGCRestClient.java:558) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.search(IGCRestClient.java:569) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.model.common.Reference.getAssetWithSubsetOfProperties(Reference.java:134) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.model.common.Reference.getAssetWithSubsetOfProperties(Reference.java:151) [igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.repositoryconnector.IGCOMRSMetadataCollection.getFullAssetDetails(IGCOMRSMetadataCollection.java:4176) [igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processAsset(IGCOMRSRepositoryEventMapper.java:556) [igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processAssetEventV115(IGCOMRSRepositoryEventMapper.java:354) [igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processEventV115(IGCOMRSRepositoryEventMapper.java:278) [igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processEvent(IGCOMRSRepositoryEventMapper.java:238) [igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper$IGCKafkaConsumerThread.run(IGCOMRSRepositoryEventMapper.java:204) [igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]

2019-06-12 15:13:47.991 ERROR 1 --- [       Thread-4] o.o.o.a.r.i.clientlibrary.IGCRestClient  : Opening a new session already attempted without success -- giving up on POST to https://xxxxxxx.xxx.xxx:444/ibm/iis/igc-rest/v1/search with {"types":["database"],"properties":["name","short_description","long_description","host","labels","stewards","assigned_to_terms","implements_rules","governed_by_rules","database_schemas","alias_(business_name)","location","dbms","dbms_server_instance","dbms_vendor","dbms_version","database_type","imported_from","data_connections","data_connection_mappings","mapped_to_mdm_models","read_by_(static)","written_by_(static)","read_by_(design)","written_by_(design)","read_by_(operational)","written_by_(operational)","read_by_(user_defined)","written_by_(user_defined)","impacted_by","impacts_on","bi_reports","bi_models","suggested_term_assignments","data_policies","blueprint_elements","in_collections","created_by","created_on","modified_by","modified_on"],"pageSize":1000,"where":{"conditions":[{"property":"_id","operator":"=","value":"b1c497ce.6e83759b.9g85t7kh2.9ge978u.81ro06.344cvqapg9q7d4ofhmog8"}],"operator":"and"}}
2019-06-12 15:13:47.991 ERROR 1 --- [       Thread-4] o.o.o.a.r.i.clientlibrary.IGCRestClient  : Unable to complete request -- check IGC environment connectivity and authentication details.
2019-06-12 15:13:47.992 ERROR 1 --- [       Thread-4] o.o.a.r.i.e.IGCOMRSRepositoryEventMapper : Failed trying to consume IGC events from Kafka.

java.lang.NullPointerException: Unable to complete request -- check IGC environment connectivity and authentication details.
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.makeRequest(IGCRestClient.java:477) ~[igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.searchJson(IGCRestClient.java:558) ~[igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.IGCRestClient.search(IGCRestClient.java:569) ~[igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.model.common.Reference.getAssetWithSubsetOfProperties(Reference.java:134) ~[igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.clientlibrary.model.common.Reference.getAssetWithSubsetOfProperties(Reference.java:151) ~[igc-rest-client-library-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.repositoryconnector.IGCOMRSMetadataCollection.getFullAssetDetails(IGCOMRSMetadataCollection.java:4176) ~[igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processAsset(IGCOMRSRepositoryEventMapper.java:556) ~[igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processAssetEventV115(IGCOMRSRepositoryEventMapper.java:354) ~[igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processEventV115(IGCOMRSRepositoryEventMapper.java:278) ~[igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper.processEvent(IGCOMRSRepositoryEventMapper.java:238) ~[igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.adapters.repositoryservices.igc.eventmapper.IGCOMRSRepositoryEventMapper$IGCKafkaConsumerThread.run(IGCOMRSRepositoryEventMapper.java:204) ~[igc-repository-connector-1.1-SNAPSHOT.jar!/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]

**Comment by cmgrote** [comment]
Thanks for raising this -- I'll have a look ASAP (probably a little later this week).  For now, transferring to separate IGC connector repository.
