### ISSUE TITLE
Local graph repo - regression? NPE in deployed k8s 

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1167]
When using the graph repo with the vdc charts the following exception is seen by atlas when starting to process typedefs from the archive:
```
2019-06-25 14:58:40.474 ERROR 1 --- [nio-8080-exec-3] o.o.o.r.l.r.OMRSRepositoryContentManager : TypeDef not added because repository has an unexpected error: EntityDef{name='Referenceable', superType=null, description='An open metadata entity that has a unique identifier.', descriptionGUID='null', origin='bce3b0a0-662a-4f87-b8dc-844078a11a6e', createdBy='ODPi Egeria (OMRS)', updatedBy='null', createTime=Thu Jan 18 22:04:00 GMT 2018, updateTime=null, options=null, externalStandardMappings=null, validInstanceStatusList=[InstanceStatus{ordinal=15, name='Active', description='The instance is approved and in use.'}, InstanceStatus{ordinal=99, name='Deleted', description='The instance has been deleted and is no longer available.'}], initialStatus=InstanceStatus{ordinal=15, name='Active', description='The instance is approved and in use.'}, propertiesDefinition=[TypeDefAttribute{attributeName='qualifiedName', attributeType=PrimitiveDef{name='string', primitiveDefCategory=PrimitiveDefCategory{code=11, name='string', javaClassName='java.lang.String', guid='b34a64b9-554a-42b1-8f8a-7d5c2339f9c4'}, category=AttributeTypeDefCategory{typeCode=1, typeName='Primitive', typeDescription='A primitive type.'}, guid='b34a64b9-554a-42b1-8f8a-7d5c2339f9c4', description='null', descriptionGUID='null'}, cardinality=AttributeCardinality{ordinal=2, name='One Only', description='1 for one instance, no more and no less'}, valuesMinCount=1, valuesMaxCount=1, isIndexable=true, isUnique=true, defaultValue='null', externalStandardMappings=null}, TypeDefAttribute{attributeName='additionalProperties', attributeType=CollectionDef{name='map<string,string>', collectionDefCategory=CollectionDefCategory{code=1, name='map<{$0}, {$1}>', argumentCount=2, javaClassName='org.odpi.openmetadata.repositoryservices.connectors.stores.metadatacollectionstore.properties.instances.MapPropertyValue'}, argumentCount=2, argumentTypes=[PrimitiveDefCategory{code=11, name='string', javaClassName='java.lang.String', guid='b34a64b9-554a-42b1-8f8a-7d5c2339f9c4'}, PrimitiveDefCategory{code=11, name='string', javaClassName='java.lang.String', guid='b34a64b9-554a-42b1-8f8a-7d5c2339f9c4'}], category=AttributeTypeDefCategory{typeCode=2, typeName='Collection', typeDescription='A collection object.'}, guid='005c7c14-ac84-4136-beed-959401b041f8', description='A map from String to String.', descriptionGUID='null'}, cardinality=AttributeCardinality{ordinal=1, name='At Most One', description='0..1 for zero or one instances. 0..1.'}, valuesMinCount=0, valuesMaxCount=1, isIndexable=true, isUnique=false, defaultValue='null', externalStandardMappings=null}], category=TypeDefCategory{typeCode=6, typeName='EntityDef', typeDescription='An object or concept of interest.'}, version=1, versionName='1.0', GUID='a32316b8-dc8c-48c5-b12b-71c1b2a080bf'}
2019-06-25 14:58:40.484 ERROR 1 --- [nio-8080-exec-3] o.o.o.r.l.r.OMRSRepositoryContentManager : Throwable:

java.lang.NullPointerException: null
    at org.odpi.openmetadata.adapters.repositoryservices.graphrepository.repositoryconnector.GraphOMRSMetadataCollection.verifyTypeDef(GraphOMRSMetadataCollection.java:124) ~[graph-repository-connector-1.1-SNAPSHOT.jar!/:na]
    at org.odpi.openmetadata.repositoryservices.localrepository.repositoryconnector.LocalOMRSMetadataCollection.verifyTypeDef(LocalOMRSMetadataCollection.java:729) ~[repository-services-implementation-1.1-SNAPSHOT.jar!/:na]
    at org.odpi.openmetadata.repositoryservices.localrepository.repositorycontentmanager.OMRSRepositoryContentManager.processNewTypeDefEvent(OMRSRepositoryContentManager.java:2226) ~[repository-services-implementation-1.1-SNAPSHOT.jar!/:na]
    at org.odpi.openmetadata.repositoryservices.archivemanager.OMRSArchiveManager.processTypeDefStore(OMRSArchiveManager.java:333) [repository-services-implementation-1.1-SNAPSHOT.jar!/:na]
    at org.odpi.openmetadata.repositoryservices.archivemanager.OMRSArchiveManager.processOpenMetadataArchive(OMRSArchiveManager.java:218) [repository-services-implementation-1.1-SNAPSHOT.jar!/:na]
    at org.odpi.openmetadata.repositoryservices.archivemanager.OMRSArchiveManager.processOpenMetadataTypes(OMRSArchiveManager.java:137) [repository-services-implementation-1.1-SNAPSHOT.jar!/:na]
    at org.odpi.openmetadata.repositoryservices.archivemanager.OMRSArchiveManager.setLocalRepository(OMRSArchiveManager.java:102) [repository-services-implementation-1.1-SNAPSHOT.jar!/:na]
    at org.odpi.openmetadata.repositoryservices.admin.OMRSOperationalServices.initialize(OMRSOperationalServices.java:409) [repository-services-implementation-1.1-SNAPSHOT.jar!/:na]
```
Note that this is only reported via DEBUG log messages, not audit
Possibly caused by #1163

**Comment by mandy-chessell** [comment]
I would not expect the graph repo to be running in the atlas server.  This suggests that there is a problem with the configuration in the Atlas server?  Have a look at the setting of the connector provider in the local repository local connection - this determines which repository connector is being started as the local repository - it should be pointing to the AtlasOMRS repository connector not the local graph repo
