### ISSUE TITLE
Extend zookeeper connection timeout for kafka in docker-compose tutorial image

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1477]
SOmetimes when starting our docker-compose environment for tutorials, a timeout occurs starting kafka. 

You may see this scroll past quickly with an error such as:
```
kafka_1       | [2019-09-03 13:43:19,267] INFO EventThread shut down for session: 0x0 (org.apache.zookeeper.ClientCnxn)
kafka_1       | [2019-09-03 13:43:19,273] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka_1       | kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
kafka_1       | 	at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply$mcV$sp(ZooKeeperClient.scala:258)
kafka_1       | 	at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:254)
kafka_1       | 	at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:254)
kafka_1       | 	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)
kafka_1       | 	at kafka.zookeeper.ZooKeeperClient.kafka$zookeeper$ZooKeeperClient$$waitUntilConnected(ZooKeeperClient.scala:254)
kafka_1       | 	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:112)
kafka_1       | 	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1825)
kafka_1       | 	at kafka.server.KafkaServer.kafka$server$KafkaServer$$createZkClient$1(KafkaServer.scala:363)
kafka_1       | 	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:387)
kafka_1       | 	at kafka.server.KafkaServer.startup(KafkaServer.scala:207)
kafka_1       | 	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
kafka_1       | 	at kafka.Kafka$.main(Kafka.scala:84)
kafka_1       | 	at kafka.Kafka.main(Kafka.scala)
kafka_1       | [2019-09-03 13:43:19,290] INFO shutting down (kafka.server.KafkaServer)
kafka_1       | [2019-09-03 13:43:19,299] INFO shut down completed (kafka.server.KafkaServer)
kafka_1       | [2019-09-03 13:43:19,303] ERROR Exiting Kafka. (kafka.server.KafkaServerStartable)
kafka_1       | [2019-09-03 13:43:19,315] INFO shutting down (kafka.server.KafkaServer)
```

With docker-compose all images are started in dependency order, but there is no check beyond an initial launch. Since hosts will vary in performance, components can come up in different orders, and specifically, the default timeout for the bitnami kafka image is for a fairly short timeout connecting to zookeeper.

The fix to this is to increase the timeout by adding KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS

**Comment by planetf1** [comment]
Tested by setting to 1ms and ensuring failure, then setting to default of 180s (18000ms)

**Comment by planetf1** [comment]
this change has been made
