### ISSUE TITLE
Open types & janus connector: mask debug logs during build

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2089]
When the FVTs are included in a build run, a lot of DEBUG messages are logged of the form
```
    [java] 09:15:34.375 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/LikeToReferenceable/LikeAnchorReference.java
     [java] 09:15:34.381 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/NoteLogAuthorToNoteLog/AuthoredNoteLogsReference.java
     [java] 09:15:34.386 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/NoteLogToNoteLogAuthor/AuthorsReference.java
     [java] 09:15:34.392 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - generating reference file open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/references/DesignPatternToDesignPattern/RelatedDesignPatternReference.java
     [java] 09:15:34.401 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - Generating OMRS Beans Accessor file
     [java] 09:15:35.489 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - Generating OMRS Beans Accessor file
     [java] 09:15:37.276 [main] DEBUG org.odpi.openmetadata.fvt.opentypes.generators.OmrsBeanGenerator - Ending test code generation
```

This adds log clutter and makes real issues harder to spot.

The generator should use a logging default which does not report DEBUG to stdout.

**Comment by planetf1** [comment]
Also noticed lots of

15:24:42.223 [main] INFO org.janusgraph.diskstorage.configuration.builder.ReadConfigurationBuilder - Set default timestamp provider MICRO
15:24:42.240 [main] INFO org.janusgraph.graphdb.idmanagement.UniqueInstanceIdRetriever - Generated unique-instance-id=0a0100046261-fv-az5781
15:24:42.267 [main] INFO org.janusgraph.diskstorage.Backend - Initiated backend operations thread pool of size 4
15:24:42.301 [main] DEBUG org.janusgraph.diskstorage.locking.LocalLockMediators - Local lock mediator instantiated for namespace org.janusgraph.diskstorage.keycolumnvalue.inmemory.InMemoryStoreManager@25e203e6
15:24:42.339 [main] DEBUG org.janusgraph.graphdb.database.idassigner.VertexIDAssigner - Partition IDs? [true], Local Partitions? [false]
15:24:42.349 [main] DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy - Setting partition at index [0] to: 9
15:24:42.350 [main] DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy - Setting partition at index [1] to: 17
15:24:42.351 [main] DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy - Setting partition at index [2] to: 0
15:24:42.351 [main] DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy - Setting partition at index [3] to: 10
15:24:42.352 [main] DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy - Setting partition at index [4] to: 9
15:24:42.354 [main] DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy - Setting partition at index [5] to: 29
15:24:42.355 [main] DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy - Setting partition at index [6] to: 11
15:24:42.356 [main] DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy - Setting partition at index [7] to: 5
15:24:42.357 [main] DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy - Setting partition at index [8] to: 24
15:24:42.358 [main] DEBUG org.janusgraph.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy - Setting partition at index [9] to: 7
15:24:42.451 [main] INFO org.janusgraph.diskstorage.log.kcvs.KCVSLog - Loaded unidentified ReadMarker start time 2019-12-06T15:24:42.451Z into org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller@3e356ed6
15:24:42.514 [main] DEBUG org.janusgraph.diskstorage.log.kcvs.KCVSLog - Creating log read executor: initialDelay=100000000 delay=5000000000 unit=NANOSECONDS
15:24:42.518 [main] DEBUG org.janusgraph.graphdb.database.StandardJanusGraph - Installed shutdown hook Thread[Thread-2,5,main]
java.lang.Throwable: Hook creation trace
	at org.janusgraph.graphdb.database.StandardJanusGraph.<init>(StandardJanusGraph.java:181)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:161)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:132)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:122)

cc: @DimitriosMaimaris 

Will aim to address both & any other remaining DEBUG output in logs (by default)

**Comment by planetf1** [comment]
Picking apart 
```
10:32:50,796 [INFO] Running org.odpi.openmetadata.openconnectors.governancedaemonconnectors.openlineageconnectors.janusconnector.maingraph.MainGraphConnectorTest
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/jonesn/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/jonesn/.m2/repository/org/slf4j/slf4j-simple/1.7.29/slf4j-simple-1.7.29.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
```
We note that there are duplicate logging bindings. slf4j-simple comes as a direct dependency (it's a convenient logger for test cases as it can be easily configured with -D options) but janusgraph hard binds logback in:
```
[INFO] +- org.janusgraph:janusgraph-es:jar:0.4.0:compile
[INFO] |  +- org.elasticsearch.client:elasticsearch-rest-client:jar:6.6.0:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.5:compile
[INFO] |  |  +- org.apache.httpcomponents:httpasyncclient:jar:4.1.2:compile
[INFO] |  |  \- org.apache.httpcomponents:httpcore-nio:jar:4.4.5:compile
[INFO] |  +- org.antlr:antlr-runtime:jar:3.2:compile
[INFO] |  |  \- org.antlr:stringtemplate:jar:3.2:compile
[INFO] |  |     \- antlr:antlr:jar:2.7.7:compile
[INFO] |  \- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |     \- ch.qos.logback:logback-core:jar:1.2.3:compile
```
which isn't idea, since the logging //implementation// should be chosen at run time through the slf4j configuration. Only slf4j-api should be used at compile time ..... but then janusgraph is using logback directly, and not slf4j ....

We could either
 a) configure logback
or
 b) exclude logback (allowing slf4j-simple to be used)

The effect could somewhat viral -fortunately we are only pulling this dependency in one place (the janus connector) so a) is both simpler and safer -- for now. However we need to take care if we depend on this connector in other modules as it could inadvertantly break our logging configurations elsewhere

With a logback-test.xml introduced at level INFO the following entries are seen:
```
14:45:30.555 [main] INFO  o.j.d.c.b.ReadConfigurationBuilder - Set default timestamp provider MICRO
14:45:30.586 [main] INFO  o.j.g.i.UniqueInstanceIdRetriever - Generated unique-instance-id=0a09008e3941-planetf1mac1
14:45:30.609 [main] INFO  org.janusgraph.diskstorage.Backend - Initiated backend operations thread pool of size 16
14:45:30.720 [main] INFO  o.j.diskstorage.log.kcvs.KCVSLog - Loaded unidentified ReadMarker start time 2019-12-09T14:45:30.720024Z into org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller@308fbc6d
14:45:35.041 [main] WARN  o.j.g.t.StandardJanusGraphTx - Query requires iterating over all vertices [(venodeID = c21)]. For better performance, use indexes
14:45:35.079 [main] WARN  o.j.g.t.StandardJanusGraphTx - Query requires iterating over all vertices [(venodeID = c21)]. For better performance, use indexes
14:45:35.092 [main] WARN  o.j.g.t.StandardJanusGraphTx - Query requires iterating over all vertices [(venodeID = c21)]. For better performance, use indexes
14:45:35.142 [main] INFO  o.j.d.c.b.ReadConfigurationBuilder - Set default timestamp provider MICRO
14:45:35.143 [main] INFO  o.j.g.i.UniqueInstanceIdRetriever - Generated unique-instance-id=0a09008e3941-planetf1mac2
14:45:35.146 [main] INFO  org.janusgraph.diskstorage.Backend - Initiated backend operations thread pool of size 16
14:45:35.152 [main] INFO  o.j.diskstorage.log.kcvs.KCVSLog - Loaded unidentified ReadMarker start time 2019-12-09T14:45:35.152309Z into org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller@869f5c3f
14:45:37.493 [main] WARN  o.j.g.t.StandardJanusGraphTx - Query requires iterating over all vertices [(venodeID = c32)]. For better performance, use indexes
14:45:37.500 [main] INFO  o.j.d.c.b.ReadConfigurationBuilder - Set default timestamp provider MICRO
14:45:37.503 [main] INFO  o.j.g.i.UniqueInstanceIdRetriever - Generated unique-instance-id=0a09008e3941-planetf1mac3
14:45:37.506 [main] INFO  org.janusgraph.diskstorage.Backend - Initiated backend operations thread pool of size 16
14:45:37.510 [main] INFO  o.j.diskstorage.log.kcvs.KCVSLog - Loaded unidentified ReadMarker start time 2019-12-09T14:45:37.510062Z into org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller@1656600e
14:45:41.199 [main] WARN  o.j.g.t.StandardJanusGraphTx - Query requires iterating over all vertices [(venodeID = g2)]. For better performance, use indexes
14:45:41.254 [main] WARN  o.j.g.t.StandardJanusGraphTx - Query requires iterating over all vertices [(venodeID = c11)]. For better performance, use indexes
14:45:41.270 [main] WARN  o.j.g.t.StandardJanusGraphTx - Query requires iterating over all vertices [(venodeID = c11)]. For better performance, use indexes
14:45:41.291 [main] WARN  o.j.g.t.StandardJanusGraphTx - Query requires iterating over all vertices [(venodeID = c32)]. For better performance, use indexes
14:45:41.301 [main] WARN  o.j.g.t.StandardJanusGraphTx - Query requires iterating over all vertices [(venodeID = c32)]. For better performance, use indexes
14:45:41.333 [main] WARN  o.j.g.t.StandardJanusGraphTx - Query requires iterating over all vertices [(venodeID = c22)]. For better performance, use indexes
```

We should avoid debug. -or indeed 'expected' warnings in the build log so that we can get output clean. We could filter further, but am inclined to leave as is for now

this was done via the following build fragment - for the test driver
```
           <!-- exclude slf4j-simple from classpath as logback pulled in by janusgraph-es -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <classpathDependencyExcludes>
                        <classpathDependencyExclude>org.slf4j:slf4j-simple</classpathDependencyExclude>
                    </classpathDependencyExcludes>
                </configuration>
            </plugin>
```

**Comment by planetf1** [comment]
Also made change to set default logging level for information view server to INFO (not DEBUG)

**Comment by planetf1** [comment]
The open lineage server itself has the same problem
 * Logging excess entries during build process as DEBUG
 * Multiple slf4j bindings

ie
```
10:42:04,378 [INFO]
10:42:04,378 [INFO] --- maven-surefire-plugin:3.0.0-M3:test (default-test) @ ui-chassis-spring ---
10:42:04,413 [INFO]
10:42:04,413 [INFO] -------------------------------------------------------
10:42:04,414 [INFO]  T E S T S
10:42:04,414 [INFO] -------------------------------------------------------
10:42:05,799 [INFO] Running org.odpi.openmetadata.userinterface.uichassis.springboot.service.OpenLineageServiceTest
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/jonesn/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBin
der.class]
SLF4J: Found binding in [jar:file:/Users/jonesn/.m2/repository/org/slf4j/slf4j-simple/1.7.29/slf4j-simple-1.7.29.jar!/org/slf4j/impl/StaticLoggerBinder.class
]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
10:42:07.905 [main] DEBUG org.springframework.test.util.ReflectionTestUtils - Setting field 'graphName' of type [null] on target object [org.odpi.openmetadata.userinterface.uichassis.springboot.service.OpenLineageService@96a53b4f] or target class [class org.odpi.openmetadata.userinterface.uichassis.springboot.service.OpenLineageService] to value [MAIN]
```
The fix is the same...
