### ISSUE TITLE
Governance Engine Client Unit Tests - ResourceAccessException

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2121]
A recent dependabot proposal of #2018 threw two exceptions
```
[ERROR] Tests run: 14, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 2.59 s <<< FAILURE! - in org.odpi.openmetadata.accessservices.governanceengine.client.GovernanceEngineImplTest
[ERROR] org.odpi.openmetadata.accessservices.governanceengine.client.GovernanceEngineImplTest.testGetGovernedAssetComponentClientAPIException  Time elapsed: 0.013 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <org.odpi.openmetadata.accessservices.governanceengine.api.ffdc.exceptions.MetadataServerException> but was: <org.springframework.web.client.ResourceAccessException>
	at org.odpi.openmetadata.accessservices.governanceengine.client.GovernanceEngineImplTest.testGetGovernedAssetComponentClientAPIException(GovernanceEngineImplTest.java:231)
Caused by: org.springframework.web.client.ResourceAccessException: Test Exception from REST client error
	at org.odpi.openmetadata.accessservices.governanceengine.client.GovernanceEngineImplTest.lambda$testGetGovernedAssetComponentClientAPIException$10(GovernanceEngineImplTest.java:233)
	at org.odpi.openmetadata.accessservices.governanceengine.client.GovernanceEngineImplTest.testGetGovernedAssetComponentClientAPIException(GovernanceEngineImplTest.java:231)

[ERROR] org.odpi.openmetadata.accessservices.governanceengine.client.GovernanceEngineImplTest.testGetGovernedAssetComponentListClientAPIException  Time elapsed: 0.006 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <org.odpi.openmetadata.accessservices.governanceengine.api.ffdc.exceptions.MetadataServerException> but was: <org.springframework.web.client.ResourceAccessException>
	at org.odpi.openmetadata.accessservices.governanceengine.client.GovernanceEngineImplTest.testGetGovernedAssetComponentListClientAPIException(GovernanceEngineImplTest.java:126)
Caused by: org.springframework.web.client.ResourceAccessException: Test Exception from REST client error
	at org.odpi.openmetadata.accessservices.governanceengine.client.GovernanceEngineImplTest.lambda$testGetGovernedAssetComponentListClientAPIException$5(GovernanceEngineImplTest.java:128)
	at org.odpi.openmetadata.accessservices.governanceengine.client.GovernanceEngineImplTest.testGetGovernedAssetComponentListClientAPIException(GovernanceEngineImplTest.java:126)

```
The test case asserts
assertThrows(MetadataServerException.class .......)
ie one of our exceptions

yet...
The code appears to call getGovernedAsset (no catches here), which then (indirectly - no more catches) calls getforObject(String url, Class<t> clazz, Object... params) on restTemplate, which according to https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestClientException.html throwns a RestClientException of which ResourceAccessException is a subclass

I'm unclear why this is only picked up with the surefire change, but it looks like an issue in the testcase - or more likely a deficiency in the client code's exception management

The spring rest client connector does correctly catch this exception, and I note also that other OMASs such as Assetconsumer do make use of the ocf connector, again catching these.

So I surmize that the surefire plugin is correct, and has been fixed, but the client here is incorrect....

**Comment by planetf1** [comment]
Failing run example: https://dev.azure.com/ODPi/Egeria/_build/results?buildId=2499&view=logs&j=8be1a9ea-1eb4-5524-bf1d-a6df7ca2ef0e&t=8d97575e-cba0-5bf4-96d8-a61d91dc9985

**Comment by planetf1** [comment]
We have many areas which need more unit tests. Code coverage analysis shows where. These particular unit tests could be resurrected but that is a code owner decision. As such seems little value in keeping this open for now
