### ISSUE TITLE
NPE in Asset Lineage Topic Listener

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#2311]
The Asset Lineage Topic Listener is throwing an NPE exception if an instance's type does not have a super class.

Here is an example of a stack trace from such an exception ...

```
java.lang.NullPointerException
	at org.odpi.openmetadata.accessservices.assetlineage.util.Validator.collectSuperTypes(Validator.java:47)
	at org.odpi.openmetadata.accessservices.assetlineage.util.Validator.collectSuperTypes(Validator.java:36)
	at org.odpi.openmetadata.accessservices.assetlineage.util.Validator.getSuperTypes(Validator.java:27)
	at org.odpi.openmetadata.accessservices.assetlineage.listeners.AssetLineageOMRSTopicListener.validateEventType(AssetLineageOMRSTopicListener.java:169)
	at org.odpi.openmetadata.accessservices.assetlineage.listeners.AssetLineageOMRSTopicListener.processInstanceEvent(AssetLineageOMRSTopicListener.java:128)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicListenerWrapper.processInstanceEvent(OMRSTopicListenerWrapper.java:143)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.processOMRSEvent(OMRSTopicConnector.java:574)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.lambda$processEvent$0(OMRSTopicConnector.java:497)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
This code is unsafe because it assumes all TypeDefs except Referenceable have a super type ... this is not the case.

```
    private void collectSuperTypes(String userId, TypeDef type, Set<String> superTypes) {
        if (type.getName().equals(REFERENCEABLE)) {
            return;
        }
        superTypes.add(type.getName());
        TypeDef typeDefByName = repositoryHelper.getTypeDefByName(userId, type.getSuperType().getName());
        if (typeDefByName != null) {
            collectSuperTypes(userId, typeDefByName, superTypes);
        }
    }
```

**Comment by mandy-chessell** [comment]
I have stopped seeing this exception so going to close - will reopen if it comes back
