### ISSUE TITLE
starting the OMAG Server, when the port it being used does not give informative message by default 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#2519]
By default it outputs 
 ODPi Egeria
    ____   __  ___ ___    ______   _____                                 ____   _         _     ___
   / __ \ /  |/  //   |  / ____/  / ___/ ___   ____ _   __ ___   ____   / _  \ / / __    / /  / _ /__   ____ _  _
  / / / // /|_/ // /| | / / __    \__ \ / _ \ / __/| | / // _ \ / __/  / /_/ // //   |  / _\ / /_ /  | /  _// || |
 / /_/ // /  / // ___ |/ /_/ /   ___/ //  __// /   | |/ //  __// /    /  __ // // /  \ / /_ /  _// / // /  / / / /
 \____//_/  /_//_/  |_|\____/   /____/ \___//_/    |___/ \___//_/    /_/    /_/ \__/\//___//_/   \__//_/  /_/ /_/

 :: Powered by Spring Boot (v2.2.4.RELEASE) ::

No OMAG servers listed in startup configuration
Thu Jan 30 15:21:42 GMT 2020 OMAG server platform ready for more configuration
Platform shutdown requested. Temporary deactivating any auto-started servers

Process finished with exit code 1

With LOGGING_LEVEL_ROOT=Error specified it gives an informative error.
With LOGGING_LEVEL_ROOT=Info specified it shows a null pointer stack trace in our code as follows:
***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 8080 was already in use.

Action:

Identify and stop the process that's listening on port 8080 or configure this application to listen on another port.

Platform shutdown requested. Temporary deactivating any auto-started servers
2020-01-30 15:51:51.183  WARN 29631 --- [           main] ConfigServletWebServerApplicationContext : Exception thrown from ApplicationListener handling ContextClosedEvent

java.lang.NullPointerException: null
	at org.odpi.openmetadata.serverchassis.springboot.OMAGServerPlatform.temporaryDeactivateServers(OMAGServerPlatform.java:130) [classes!/:na]
	at org.odpi.openmetadata.serverchassis.springboot.OMAGServerPlatform.access$200(OMAGServerPlatform.java:35) [classes!/:na]
	at org.odpi.openmetadata.serverchassis.springboot.OMAGServerPlatform$ApplicationContextListener.onApplicationEvent(OMAGServerPlatform.java:170) ~[classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:305) ~[spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:190) ~[spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:153) ~[spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403) [spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360) [spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1012) [spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:978) [spring-context-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:803) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
	at org.odpi.openmetadata.serverchassis.springboot.OMAGServerPlatform.main(OMAGServerPlatform.java:56) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [server-chassis-spring-1.5-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [server-chassis-spring-1.5-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [server-chassis-spring-1.5-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597) [server-chassis-spring-1.5-SNAPSHOT.jar:na]

**Comment by mandy-chessell** [comment]
Note, whoever fixes this, there is a troubleshooting page coverign this error that laso needs updating ...

https://egeria.odpi.org/open-metadata-publication/website/trouble-shooting/omag-server-errors/err-omag-server-platform-fails-to-start.html

**Comment by planetf1** [comment]
Note that having tried this with the current code, the exception does not occur - whether there are servers autostarted or not

That fix was made in 685e5f55eb2dd4efe2dfe0df0187de8692e0b6d1

**Comment by planetf1** [comment]
It's possible to trap the startup by using a FailureAnalyzer. However at this point we have no infrastructure, so it's unclear what we could do beyond what SpringBoot does by default. Any code here would be spring specific of course.

Changing our default log level to ERROR or FATAL will result in output like
```
egeria git:(issue2519) ✗ cd ~/src/egeria;LOGGING_LEVEL_ROOT=ERROR java -jar ~/src/egeria/open-metadata-implementation/server-chassis/server-chassis-spring/target/server-chassis-spring-1.5-SNAPSHOT.jar
 ODPi Egeria
    ____   __  ___ ___    ______   _____                                 ____   _         _     ___
   / __ \ /  |/  //   |  / ____/  / ___/ ___   ____ _   __ ___   ____   / _  \ / / __    / /  / _ /__   ____ _  _
  / / / // /|_/ // /| | / / __    \__ \ / _ \ / __/| | / // _ \ / __/  / /_/ // //   |  / _\ / /_ /  | /  _// || |
 / /_/ // /  / // ___ |/ /_/ /   ___/ //  __// /   | |/ //  __// /    /  __ // // /  \ / /_ /  _// / // /  / / / /
 \____//_/  /_//_/  |_|\____/   /____/ \___//_/    |___/ \___//_/    /_/    /_/ \__/\//___//_/   \__//_/  /_/ /_/

 :: Powered by Spring Boot (v2.2.4.RELEASE) ::

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (jar:file:/Users/jonesn/IdeaProjects/egeria/open-metadata-implementation/server-chassis/server-chassis-spring/target/server-chassis-spring-1.5-SNAPSHOT.jar!/BOOT-INF/lib/groovy-2.5.7-indy.jar!/) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Tue Feb 25 18:48:16 GMT 2020 No OMAG servers listed in startup configuration
Tue Feb 25 18:48:22 GMT 2020 OMAG server platform ready for more configuration
2020-02-25 18:48:23.008 ERROR 35869 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 8080 was already in use.

Action:

Identify and stop the process that's listening on port 8080 or configure this application to listen on another port.

```
As David mentioned above.

This is well understood and clear.
Generally logging in the app is not helpful beyond debug, but startup is a somewhat special case.

I would propose we revert back to a low level of logging to address -- there may be other critical issues.  Having taken a /quick/ look I don't see any other log entries coming out at ERROR, so that is the level I'd propose.

**Comment by planetf1** [comment]
Verified config/startup of coco cluster -- Nothing additional/new is logged - messages are all AUDIT or Startup, known groovy error (j11 - happens even with OFF) & the ready messages.
