### ISSUE TITLE
Looping audit log messages when starting 2 servers without Kafka being there - when I run the Subject Area FVT.

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#2524]
I started 2 in memory servers - I have not got Kafka setup. I then ran the Subject Area FVT which creates, updates, deletes, gets, restores, glossaries, terms , categories and associated relationships. This causes looping Audit messages in the console as below:

 I have assigned to Dimi as the first error was in Asset Lineage. There is a null pointer in Security Officer as well - so I also assigned Daniela. Please split into 2 issues if you prefer.

I got the following : 
 
Fri Jan 31 14:04:47 GMT 2020 Server2 Information OMRS-AUDIT-0020 The OMRS Topic Connector EnterpriseTopicConnector.Server.Server2 is ready to send and receive events
Fri Jan 31 14:04:47 GMT 2020 Server2 Information OMRS-AUDIT-0015 The listener thread for an OMRS Topic Connector for topic Server2.openmetadata.repositoryservices.enterprise.Server2.OMRSTopic has started
Fri Jan 31 14:05:02 GMT 2020 Server1 Exception OMRS-AUDIT-9017 The topic listener for the Asset Lineage service threw an unexpected exception org.odpi.openmetadata.accessservices.assetlineage.ffdc.exception.AssetLineageException with message REPOSITORY-HANDLER-400-003 An unexpected error was returned by the property server during getRelationshipsByType request for open metadata access service Asset Lineage OMAS on server Server1; message was OMRS-REPOSITORY-404-002 The entity identified with guid bcfed369-1b53-4328-a55b-f5346cf565ac passed on the getEntitySummary call is not known to the open metadata repository Server1; the stack trace was org.odpi.openmetadata.accessservices.assetlineage.ffdc.exception.AssetLineageException: REPOSITORY-HANDLER-400-003 An unexpected error was returned by the property server during getRelationshipsByType request for open metadata access service Asset Lineage OMAS on server Server1; message was OMRS-REPOSITORY-404-002 The entity identified with guid bcfed369-1b53-4328-a55b-f5346cf565ac passed on the getEntitySummary call is not known to the open metadata repository Server1
	at org.odpi.openmetadata.accessservices.assetlineage.handlers.AssetContextHandler.getAssetContext(AssetContextHandler.java:138)
	at org.odpi.openmetadata.accessservices.assetlineage.listeners.AssetLineageOMRSTopicListener.getAssetContext(AssetLineageOMRSTopicListener.java:334)
	at org.odpi.openmetadata.accessservices.assetlineage.listeners.AssetLineageOMRSTopicListener.processNewEntity(AssetLineageOMRSTopicListener.java:192)
	at org.odpi.openmetadata.accessservices.assetlineage.listeners.AssetLineageOMRSTopicListener.validateEventType(AssetLineageOMRSTopicListener.java:164)
	at org.odpi.openmetadata.accessservices.assetlineage.listeners.AssetLineageOMRSTopicListener.processInstanceEvent(AssetLineageOMRSTopicListener.java:121)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicListenerWrapper.processInstanceEvent(OMRSTopicListenerWrapper.java:143)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.processOMRSEvent(OMRSTopicConnector.java:574)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.lambda$processEvent$0(OMRSTopicConnector.java:497)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Fri Jan 31 14:05:02 GMT 2020 Server1 Exception OMRS-AUDIT-9017Supplementary information: log record id 6e65de00-d53d-449a-acdd-1bf9765ec6c9 org.odpi.openmetadata.accessservices.assetlineage.ffdc.exception.AssetLineageException returned message of REPOSITORY-HANDLER-400-003 An unexpected error was returned by the property server during getRelationshipsByType request for open metadata access service Asset Lineage OMAS on server Server1; message was OMRS-REPOSITORY-404-002 The entity identified with guid bcfed369-1b53-4328-a55b-f5346cf565ac passed on the getEntitySummary call is not known to the open metadata repository Server1 and stacktrace of 
org.odpi.openmetadata.accessservices.assetlineage.ffdc.exception.AssetLineageException: REPOSITORY-HANDLER-400-003 An unexpected error was returned by the property server during getRelationshipsByType request for open metadata access service Asset Lineage OMAS on server Server1; message was OMRS-REPOSITORY-404-002 The entity identified with guid bcfed369-1b53-4328-a55b-f5346cf565ac passed on the getEntitySummary call is not known to the open metadata repository Server1
	at org.odpi.openmetadata.accessservices.assetlineage.handlers.AssetContextHandler.getAssetContext(AssetContextHandler.java:138)
	at org.odpi.openmetadata.accessservices.assetlineage.listeners.AssetLineageOMRSTopicListener.getAssetContext(AssetLineageOMRSTopicListener.java:334)
	at org.odpi.openmetadata.accessservices.assetlineage.listeners.AssetLineageOMRSTopicListener.processNewEntity(AssetLineageOMRSTopicListener.java:192)
	at org.odpi.openmetadata.accessservices.assetlineage.listeners.AssetLineageOMRSTopicListener.validateEventType(AssetLineageOMRSTopicListener.java:164)
	at org.odpi.openmetadata.accessservices.assetlineage.listeners.AssetLineageOMRSTopicListener.processInstanceEvent(AssetLineageOMRSTopicListener.java:121)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicListenerWrapper.processInstanceEvent(OMRSTopicListenerWrapper.java:143)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.processOMRSEvent(OMRSTopicConnector.java:574)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.lambda$processEvent$0(OMRSTopicConnector.java:497)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Fri Jan 31 14:05:02 GMT 2020 Server1 Exception OMRS-AUDIT-9017 The topic listener for the Security Officer service threw an unexpected exception java.lang.NullPointerException with message null; the stack trace was java.lang.NullPointerException
	at org.odpi.openmetadata.accessservices.securityofficer.server.admin.publisher.SecurityOfficerPublisher.lambda$containsGovernanceConfidentialityClassification$1(SecurityOfficerPublisher.java:254)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469)
	at org.odpi.openmetadata.accessservices.securityofficer.server.admin.publisher.SecurityOfficerPublisher.containsGovernanceConfidentialityClassification(SecurityOfficerPublisher.java:254)
	at org.odpi.openmetadata.accessservices.securityofficer.server.admin.publisher.SecurityOfficerPublisher.processClassifiedEntityEvent(SecurityOfficerPublisher.java:72)
	at org.odpi.openmetadata.accessservices.securityofficer.server.admin.listener.SecurityOfficerOMRSTopicListener.processInstanceEvent(SecurityOfficerOMRSTopicListener.java:51)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicListenerWrapper.processInstanceEvent(OMRSTopicListenerWrapper.java:143)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.processOMRSEvent(OMRSTopicConnector.java:574)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.lambda$processEvent$0(OMRSTopicConnector.java:497)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Fri Jan 31 14:05:02 GMT 2020 Server1 Exception OMRS-AUDIT-9017Supplementary information: log record id cfd6b181-a2b2-461a-9b4f-8922d79b16b0 java.lang.NullPointerException returned message of null and stacktrace of 
java.lang.NullPointerException
	at org.odpi.openmetadata.accessservices.securityofficer.server.admin.publisher.SecurityOfficerPublisher.lambda$containsGovernanceConfidentialityClassification$1(SecurityOfficerPublisher.java:254)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469)
	at org.odpi.openmetadata.accessservices.securityofficer.server.admin.publisher.SecurityOfficerPublisher.containsGovernanceConfidentialityClassification(SecurityOfficerPublisher.java:254)
	at org.odpi.openmetadata.acces

**Comment by planetf1** [comment]
Can confirm I don't see this in the coco environment with latest master (but - I have kafka setup ok)

**Comment by davidradl** [comment]
@planetf1. I changed the abstract to say this occurs when the Subject Area FVT is run - which it originally did not say; did you try that?

**Comment by planetf1** [comment]
No I have not.

I think the best way to get this running more regularly is to
 * Switch containers to run the full metadata distribution (#2375)
* Ensure this FVT is appropriately packaged within
* Provide instructions to run these tests against the 'standard' environment (this could be a docker/kubectl 'exec' command to launch the test - whilst making the tests as configurable as needed
* Subsequently automate the execution of these (builds on #426)

I see #747 is open, so suggest we followup on the execution of the tests and required changes there, and use this issue for resolving any underlaying issue.

**Comment by planetf1** [comment]
From looking at the logs this looks like a potentially severe issue where those other components are failing due to instances of  types they do not expect? That could fundamentaly break many other aspects in egeria. (not tested myself yet)

**Comment by planetf1** [comment]
Another way to make this easier to test/understand would be to add an example notebook showcasing subject area FVT (presume that is planned for the omas in any case?)

**Comment by davidradl** [comment]
@planetf1  I think the FVT stands separately as a test that do not use meaningful content - it is technically proving that the API works as expected. A notebook would need to be around Coco Pharmaceuticals authoring use case(s), which would be useful; it is not there yet.

**Comment by planetf1** [comment]
Apologies - bad wording. I had meant to saw showcasing subject area (which would introduce terms, glossaries etc.. and thus might expose some of these type issues) . Not FVT, which you quite correctly pointed out :-)

**Comment by mandy-chessell** [comment]
I believe this is fixed via a duplicate defect.
