### ISSUE TITLE
UI - Asset Search - Bad Error Handling - parm in exception handler

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2551]
Running off master, odpi-egeria-vdc helm chart, UI query for 'column'.
```
2020-02-05 14:48:19.593  INFO 1 --- [           main] o.o.o.u.u.springboot.EgeriaUIPlatform    : Started EgeriaUIPlatform in 29.587 seconds (JVM running for 31.395)
2020-02-05 14:53:58.107  INFO 1 --- [nio-8443-exec-5] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-02-05 14:53:58.107  INFO 1 --- [nio-8443-exec-5] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-02-05 14:53:58.120  INFO 1 --- [nio-8443-exec-5] o.s.web.servlet.DispatcherServlet        : Completed initialization in 12 ms
2020-02-05 15:04:13.856 ERROR 1 --- [nio-8443-exec-9] o.o.o.u.u.s.s.AssetCatalogOMASService    : Error searching the assets by criteria COLUMN
2020-02-05 15:04:13.870  WARN 1 --- [nio-8443-exec-9] .m.m.a.ExceptionHandlerExceptionResolver : Failure in @ExceptionHandler org.odpi.openmetadata.userinterface.uichassis.springboot.api.ExceptionHandlerController#handleAssetCatalogException(AssetCatalogException, WebRequest)

java.lang.IllegalStateException: Could not resolve parameter [0] in protected org.springframework.http.ResponseEntity<java.lang.Object> org.odpi.openmetadata.userinterface.uichassis.springboot.api.ExceptionHandlerController.handleAssetCatalogException(org.odpi.openmetadata.accessservices.assetcatalog.exception.AssetCatalogException,org.springframework.web.context.request.WebRequest): No suitable resolver
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:164) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at 
```
I'm not sure of the exact failure, 
Note that another query for 'banana' (a glossary term that exists) succeeds ok and displays on the UI

**Comment by planetf1** [comment]
```
2020-02-05 15:04:13.875 ERROR 1 --- [nio-8443-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is PropertyServerException{reportedHTTPCode=503, reportingClassName='org.odpi.openmetadata.accessservices.assetcatalog.AssetCatalog', reportingActionDescription='searchByType', errorMessage='OMAG-COMMON-503-001 A client-side exception was received from API call searchByType to OMAG Server myserver at http://vdc-odpi-egeria-vdc-egeria-service:8080.  The error message was CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.HttpServerErrorException$InternalServerError was received by method searchByType from API call http://vdc-odpi-egeria-vdc-egeria-service:8080/servers/{0}/open-metadata/access-services/asset-catalog/users/{1}/search?searchCriteria={2} to server myserver on platform http://vdc-odpi-egeria-vdc-egeria-service:8080.  The error message was 500 : [{"timestamp":"2020-02-05T15:04:13.836+0000","status":500,"error":"Internal Server Error","message":"No message available","path":"/servers/myserver/open-metadata/access-services/asset-catalog/users/faithbroker/search"}]', reportedSystemAction='The server has issued a call to the open metadata access service REST API in a remote server and has received an exception from the local client libraries.', reportedUserAction='Look for errors in the local server's console to understand and correct the source of the error.', reportedCaughtException=RESTServerException{reportedHTTPCode=503, reportingClassName='org.odpi.openmetadata.adapters.connectors.restclients.spring.SpringRESTClientConnector', reportingActionDescription='searchByType', errorMessage='CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.HttpServerErrorException$InternalServerError was received by method searchByType from API call http://vdc-odpi-egeria-vdc-egeria-service:8080/servers/{0}/open-metadata/access-services/asset-catalog/users/{1}/search?searchCriteria={2} to server myserver on platform http://vdc-odpi-egeria-vdc-egeria-service:8080.  The error message was 500 : [{"timestamp":"2020-02-05T15:04:13.836+0000","status":500,"error":"Internal Server Error","message":"No message available","path":"/servers/myserver/open-metadata/access-services/asset-catalog/users/faithbroker/search"}]', reportedSystemAction='The client has issued a call to the open metadata access service REST API in a remote server and has received an exception from the local client libraries.', reportedUserAction='Review the error message to determine the cause of the error.  Check that the server is running an the URL is correct. Look for errors in the local server's console to understand and correct the cause of the error. Then rerun the request', reportedCaughtException=org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 : [{"timestamp":"2020-02-05T15:04:13.836+0000","status":500,"error":"Internal Server Error","message":"No message available","path":"/servers/myserver/open-metadata/access-services/asset-catalog/users/faithbroker/search"}]}, relatedProperties=null}] with root cause

```
