### ISSUE TITLE
Unexpected Exception from Governance Engine OMAS

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#2935]
The following errors are occurring while running the Coco Pharmaceuticals labs:

```
Fri Apr 17 10:54:38 BST 2020 cocoMDS1 Security OPEN-METADATA-SECURITY-0006 User Governance Engine is not authorized to issue a request to server cocoMDS1
Fri Apr 17 10:54:38 BST 2020 cocoMDS1 Exception OMAS-GOVERNANCE-ENGINE-0008 The Governance Engine Open Metadata Access Service (OMAS) encounter an exception while processing incoming event {0}
```

Firstly the Governance Engine OMAS is not using the server's userId (serverUserName)
but the `componentName` in multiple places in `GovernanceEngineOMRSTopicListener`.  This userId is not valid and so the UserNotAuthorizedException is thrown.

The second problem is that the `OMAS-GOVERNANCE-ENGINE-0008` message is not being formatted correctly.  It is produced by the `logExceptionToAudit()` method.  Note the call should be `logException()` rather than `logMessage()`.  The `instanceEvent` should be passed to `getMessageDefinition()` and the throwable should be the last parameter on the `logException()` call.

```java
private void logExceptionToAudit(OMRSInstanceEvent instanceEvent, Throwable e) {
        auditLog.logMessage("Governance Engine OMAS is processing an OMRSTopic event.",
                GovernanceEngineAuditCode.EVENT_PROCESSING_ERROR.getMessageDefinition());
    }
```
In addition `logExceptionToAudit()` is called from multiple places and there is no distinguishing property in the message to identify the origin of the error.   A simple fix would be to add methodName to the message.

**Comment by planetf1** [comment]
This is noticeable when running the lab notebooks if/when a user refers to the logs - similarly in a real system.

We should fix this asap 

I'm proposing to add a reference in the release notes for 1.7

**Comment by mandy-chessell** [comment]
There has been a fix go in for this problem and so it is very close to being remedied.  Now we have a proper audit log message and the UserNotAuthorizedException stack trace is logged.

```
Mon May 04 16:38:38 BST 2020 cocoMDS1 Security OPEN-METADATA-SECURITY-0006 User cocoMDS1 is not authorized to issue a request to server cocoMDS1
Mon May 04 16:38:38 BST 2020 cocoMDS1 Exception OMAS-GOVERNANCE-ENGINE-0008 The Governance Engine Open Metadata Access Service (OMAS) encounter an exception while processing event of type ReclassifiedEntityEvent
Mon May 04 16:38:38 BST 2020 cocoMDS1 Exception OMAS-GOVERNANCE-ENGINE-0008 Supplementary information: log record id 9eb4d58b-bbb9-4589-a6b4-cd1bcdf76958 org.odpi.openmetadata.commonservices.ffdc.exceptions.UserNotAuthorizedException returned message of UserNotAuthorizedException{userId='cocoMDS1', reportedHTTPCode=403, reportingClassName='org.odpi.openmetadata.metadatasecurity.samples.CocoPharmaServerSecurityConnector', reportingActionDescription='validateUserForServer', reportedErrorMessageId='OMAG-PLATFORM-SECURITY-403-002 ', reportedErrorMessageParameters=[cocoMDS1, cocoMDS1], reportedSystemAction='The system is unable to process a request from the user because they do not have access to the requested OMAG server.  The request fails with a UserNotAuthorizedException exception.', reportedUserAction='Determine whether the user should have access to the server.  If they should have, take steps to add them to the authorized list of users.  If this user should not have access, investigate where the request came from to determine if the system is under attack, or it was a mistake, or the user's tool is not configured to connect to the correct server.', reportedCaughtException=null, relatedProperties=null} and stacktrace of 
UserNotAuthorizedException{userId='cocoMDS1', reportedHTTPCode=403, reportingClassName='org.odpi.openmetadata.metadatasecurity.samples.CocoPharmaServerSecurityConnector', reportingActionDescription='validateUserForServer', errorMessage='OMAG-PLATFORM-SECURITY-403-002  User cocoMDS1 is not authorized to issue a request to server cocoMDS1', reportedSystemAction='The system is unable to process a request from the user because they do not have access to the requested OMAG server.  The request fails with a UserNotAuthorizedException exception.', reportedUserAction='Determine whether the user should have access to the server.  If they should have, take steps to add them to the authorized list of users.  If this user should not have access, investigate where the request came from to determine if the system is under attack, or it was a mistake, or the user's tool is not configured to connect to the correct server.', reportedCaughtException=null, relatedProperties=null}
	at org.odpi.openmetadata.commonservices.multitenant.OMAGServerPlatformInstanceMap.getInstanceForPlatform(OMAGServerPlatformInstanceMap.java:464)
	at org.odpi.openmetadata.commonservices.multitenant.OMAGServerPlatformInstanceMap.getServiceInstance(OMAGServerPlatformInstanceMap.java:989)
	at org.odpi.openmetadata.commonservices.multitenant.OMAGServerServiceInstanceHandler.getServerServiceInstance(OMAGServerServiceInstanceHandler.java:94)
	at org.odpi.openmetadata.accessservices.governanceengine.server.admin.GovernanceEngineInstanceHandler.getGovernedAssetHandler(GovernanceEngineInstanceHandler.java:43)
	at org.odpi.openmetadata.accessservices.governanceengine.server.listeners.GovernanceEngineOMRSTopicListener.processReclassifiedEntityEvent(GovernanceEngineOMRSTopicListener.java:122)
	at org.odpi.openmetadata.accessservices.governanceengine.server.listeners.GovernanceEngineOMRSTopicListener.processInstanceEvent(GovernanceEngineOMRSTopicListener.java:80)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicListenerWrapper.processInstanceEvent(OMRSTopicListenerWrapper.java:146)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.processOMRSEvent(OMRSTopicConnector.java:508)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.lambda$processEvent$0(OMRSTopicConnector.java:445)
    : 
```
The userId has changed from the component name to the server name - It just needs to be changed to the server's userId.   This is passed to the Governance Engine OMAS as one of the parameters on the call to its admin `initialize()` method.

**Comment by mandy-chessell** [comment]
I have create the fix.

**Comment by planetf1** [comment]
Is this fixed & can be closed now?

**Comment by mandy-chessell** [comment]
I believe so
