### ISSUE TITLE
VDC helm chart - Apache Atlas fails to initialize solr correctly

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3118]
In the VDC chart, apache atlas is currently failing to initialize with:

```
jonesn:charts/ (bogdan-sava-ssl) $ kubectl logs vdc-odpi-egeria-vdc-atlas-cd97d87fd-tgl7c apache-atlas                [18:31:47]
Picked up JAVA_TOOL_OPTIONS: -Xmx1024m
configured for local hbase.
hbase started.
configured for local solr.
solr started.
setting up solr collections...
starting atlas on host localhost
starting atlas on port 21000
..................................
Apache Atlas Server started!!!

==> /opt/apache/atlas/logs/atlas.20200528-173024.out <==
running master, logging to /opt/apache/atlas/hbase/bin/../logs/hbase--master-atlas.out
Picked up JAVA_TOOL_OPTIONS: -Xmx1024m

==> /opt/apache/atlas/logs/atlas.20200528-173025.out <==

Started Solr server on port 9838 (pid=atlas). Happy searching!


==> /opt/apache/atlas/logs/atlas.20200528-173033.out <==
Created collection 'edge_index' with 1 shard(s), 1 replica(s) with config-set 'edge_index'

==> /opt/apache/atlas/logs/atlas.20200528-173042.out <==
Created collection 'fulltext_index' with 1 shard(s), 1 replica(s) with config-set 'fulltext_index'

==> /opt/apache/atlas/logs/atlas.20200528-173049.out <==
	at org.janusgraph.diskstorage.solr.Solr6Index.register(Solr6Index.java:307)
	at org.janusgraph.diskstorage.indexing.IndexTransaction.register(IndexTransaction.java:96)
	at org.janusgraph.graphdb.database.IndexSerializer.register(IndexSerializer.java:105)
	at org.janusgraph.graphdb.database.management.ManagementSystem.addIndexKey(ManagementSystem.java:529)
	at org.apache.atlas.repository.graphdb.janus.AtlasJanusGraphManagement.addMixedIndex(AtlasJanusGraphManagement.java:202)
	at org.apache.atlas.repository.graph.GraphBackedSearchIndexer.createVertexIndex(GraphBackedSearchIndexer.java:518)
	at org.apache.atlas.repository.graph.GraphBackedSearchIndexer.initialize(GraphBackedSearchIndexer.java:269)
	... 75 more
17:31:22,894  INFO AbstractConnector:278 - Started ServerConnector@701d2b59{HTTP/1.1,[http/1.1]}{0.0.0.0:21000}
17:31:22,894  INFO Server:414 - Started @33508ms
```

Note also https://github.com/odpi/egeria/issues/2779 refers to a build issue on this image

originally found working on https://github.com/odpi/egeria/pull/3056 - but this error does not appear related to the change to enable security, rather it is the atlas server itself failing to start

**Comment by planetf1** [comment]
tested this last week and it appears to be working again. Closing for now
