### ISSUE TITLE
Slightly confusing stack traces (jars with dependencies)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3209]
Seen in #3208 - slightly confusing stack traces

 -- We have some of the spring errors coming through the cassandra connector.

This is likely due to the inclusion of all dependencies in the jar, and in this case should stop when all our connectors are not loaded statically

.. needs investigation 

| 	at org.odpi.openmetadata.accessservices.subjectarea.client.SubjectAreaBaseImpl.findRESTCall(SubjectAreaBaseImpl.java:260) ~[subject-area-client-2.0-SNAPSHOT.jar!/:na]
ui_1         | 	at org.odpi.openmetadata.accessservices.subjectarea.client.SubjectAreaGlossaryImpl.findGlossary(SubjectAreaGlossaryImpl.java:132) ~[subject-area-client-2.0-SNAPSHOT.jar!/:na]
ui_1         | 	at org.odpi.openmetadata.userinterface.uichassis.springboot.api.subjectarea.SubjectAreaGlossaryController.findGlossary(SubjectAreaGlossaryController.java:158) ~[classes!/:na]
ui_1         | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
ui_1         | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
ui_1         | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
ui_1         | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
ui_1         | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[cassandra-metadata-extractor-connector-2.0-SNAPSHOT-jar-with-dependencies.jar:5.2.7.RELEASE]
ui_1         | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[cassandra-metadata-extractor-connector-2.0-SNAPSHOT-jar-with-dependencies.jar:5.2.7.RELEASE]
ui_1         | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
ui_1         | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
ui_1         | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]

**Comment by planetf1** [comment]
Dependencies no longer included in the connector jars so this is resolved
