### ISSUE TITLE
[UI][asset-lineage-view] If asset lineage is not configured, the UI chassis reports an exception

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3412]
Brought up the 'lab' notebook environment. Ran through config/start notebooks, and building an asset catalog

Clicked on asset lineage and get a popup 'We are experiencing an unexpected error. Please try again later! ' alongside an exception chain - see https://gist.github.com/planetf1/1714a96d956f6b0bbaa2f18965f6b516

Error begins:
```
2020-07-30 14:01:52.587 -ERROR 1 --- [nio-8443-exec-7] o.o.o.c.ffdc.RESTExceptionHandler        : Detected Invalid Parameter Exception in REST Response

org.odpi.openmetadata.frameworks.connectors.ffdc.InvalidParameterException: OMAG-REPOSITORY-HANDLER-404-007 The none with unique identifier undefined is not found for method getEntityByGUID of access service Asset Catalog OMAS in open metadata server cocoMDS4, error message was: OMRS-REPOSITORY-404-002 The entity identified with guid undefined passed on the getEntityDetail call is not known to the open metadata repository cocoMDS3
	at org.odpi.openmetadata.commonservices.ffdc.RESTExceptionHandler.throwInvalidParameterException(RESTExceptionHandler.java:213) [cassandra-metadata-extractor-connector-2.1-jar-with-dependencies.jar:na]
	at org.odpi.openmetadata.commonservices.ffdc.RESTExceptionHandler.detectAndThrowInvalidParameterException(RESTExceptionHandler.java:130) [cassandra-metadata-extractor-connector-2.1-jar-with-dependencies.jar:na]
	at org.odpi.openmetadata.accessservices.assetcatalog.AssetCatalog.detectExceptions(AssetCatalog.java:321) [asset-catalog-client-2.1.jar!/:na]
```

This isn't a regression and lineage isn't a release function - though having it in the UI without any warning means users may click on it whilst exploring, so we should consider how to handle either the fact it's a function under development, or that it may not be configured.

**Comment by bogdan-sava** [comment]
fixed
