### ISSUE TITLE
Add local graph repo for FVT testing of subject area

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3446]
In PR #3386 we saw test failures with subject area against a graph repo.

This issue will add support for running FVTs for subject area using both inmem and graph.

This is a 'quick' fix which

* duplicates the configuration groovy code to start an additional server
* Uses JUnit5 parameterized tests to run each against 2 servers

Ideally
 * groovy script needs refactoring
 * some groovy content could be moved into before/after

I will ensure we have a seperate issue raised on the fact the tests currently fail - that will need integrating first before the test fix.

**Comment by planetf1** [comment]
A full log from a test run can be found at https://gist.github.com/b3ba00b8d2688030a16902d335c5ff35

An example is:
```
Create a glossary
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.666 s <<< FAILURE! - in org.odpi.openmetadata.accessservices.subjectarea.fvt.junit.Ef
fectiveDatesIT
[ERROR] org.odpi.openmetadata.accessservices.subjectarea.fvt.junit.EffectiveDatesIT.testEffectiveDates(String)[2]  Time elapsed: 0.093 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception thrown: org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException: OMAG-COMMON-503-001 A client-side exception was received from API call find for Glossary to OMAG Server servergraph at https://localhost:10443.  The error message was CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.HttpServerErrorException$InternalServerError was received by method find for Glossary from API call https://localhost:10443/servers/servergraph/open-metadata/access-services/subject-area/users/garygeeke/glossaries?sequencingOrder=ANY&searchCriteria=.*&offset=0&pageSize=0 to server servergraph on platform https://localhost:10443.  The error message was 500 : [{"timestamp":"2020-08-05T09:39:46.865+00:00","status":500,"error":"Internal Server Error","message":"","path":"/servers/servergraph/open-metadata/access-services/subject-area/users/garygeeke/glossaries"}]
        at subject.area.fvt@2.2-SNAPSHOT/org.odpi.openmetadata.accessservices.subjectarea.fvt.junit.EffectiveDatesIT.testEffectiveDates(EffectiveDatesIT.java:17)
Caused by: org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException: OMAG-COMMON-503-001 A client-side exception was received from API call find for Glossary to OMAG Server servergraph at https://localhost:10443.  The error message was CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.HttpServerErrorException$InternalServerError was received by method find for Glossary from API call https://localhost:10443/servers/servergraph/open-metadata/access-services/subject-area/users/garygeeke/glossaries?sequencingOrder=ANY&searchCriteria=.*&offset=0&pageSize=0 to server servergraph on platform https://localhost:10443.  The error message was 500 : [{"timestamp":"2020-08-05T09:39:46.865+00:00","status":500,"error":"Internal Server Error","message":"","path":"/servers/servergraph/open-metadata/access-services/subject-area/users/garygeeke/glossaries"}]
        at subject.area.fvt@2.2-SNAPSHOT/org.odpi.openmetadata.accessservices.subjectarea.fvt.junit.EffectiveDatesIT.lambda$testEffectiveDates$0(EffectiveDatesIT.java:17)
        at subject.area.fvt@2.2-SNAPSHOT/org.odpi.openmetadata.accessservices.subjectarea.fvt.junit.EffectiveDatesIT.testEffectiveDates(EffectiveDatesIT.java:17)
Caused by: org.odpi.openmetadata.adapters.connectors.restclients.ffdc.exceptions.RESTServerException: CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.HttpServerErrorException$InternalServerError was received by method find for Glossary from API call https://localhost:10443/servers/servergraph/open-metadata/access-services/subject-area/users/garygeeke/glossaries?sequencingOrder=ANY&searchCriteria=.*&offset=0&pageSize=0 to server servergraph on platform https://localhost:10443.  The error message was 500 : [{"timestamp":"2020-08-05T09:39:46.865+00:00","status":500,"error":"Internal Ser
ver Error","message":"","path":"/servers/servergraph/open-metadata/access-services/subject-area/users/garygeeke/glossaries"}]
        at subject.area.fvt@2.2-SNAPSHOT/org.odpi.openmetadata.accessservices.subjectarea.fvt.junit.EffectiveDatesIT.lambda$testEffectiveDates$0(EffectiveDates
IT.java:17)
        at subject.area.fvt@2.2-SNAPSHOT/org.odpi.openmetadata.accessservices.subjectarea.fvt.junit.EffectiveDatesIT.testEffectiveDates(EffectiveDatesIT.java:1
7)
Caused by: org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 : [{"timestamp":"2020-08-05T09:39:46.865+00:00","status":500,"error
":"Internal Server Error","message":"","path":"/servers/servergraph/open-metadata/access-services/subject-area/users/garygeeke/glossaries"}]
        at subject.area.fvt@2.2-SNAPSHOT/org.odpi.openmetadata.accessservices.subjectarea.fvt.junit.EffectiveDatesIT.lambda$testEffectiveDates$0(EffectiveDates
IT.java:17)
        at subject.area.fvt@2.2-SNAPSHOT/org.odpi.openmetadata.accessservices.subjectarea.fvt.junit.EffectiveDatesIT.testEffectiveDates(EffectiveDatesIT.java:1
7)
```

need to check if this is a SA failure, or an error with my test update

**Comment by planetf1** [comment]
The full server log during a test run is at 
https://gist.github.com/0252f24c24611fcd4946321260a9fe87

An example server-side exception is:
```
10:49:02.254 [https-jsse-nio-10443-exec-9] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
        at org.odpi.openmetadata.accessservices.subjectarea.utilities.OMRSAPIHelper.getTypeDefGUID(OMRSAPIHelper.java:911)
        at org.odpi.openmetadata.accessservices.subjectarea.utilities.OMRSAPIHelper.findEntitiesByPropertyValue(OMRSAPIHelper.java:813)
        at org.odpi.openmetadata.accessservices.subjectarea.utilities.OMRSAPIHelper.findEntitiesByPropertyValue(OMRSAPIHelper.java:788)
        at org.odpi.openmetadata.accessservices.subjectarea.handlers.SubjectAreaHandler.findEntities(SubjectAreaHandler.java:109)
        at org.odpi.openmetadata.accessservices.subjectarea.handlers.SubjectAreaGlossaryHandler.findGlossary(SubjectAreaGlossaryHandler.java:148)
        at org.odpi.openmetadata.accessservices.subjectarea.server.services.SubjectAreaGlossaryRESTServices.findGlossary(SubjectAreaGlossaryRESTServices.java:145)
        at org.odpi.openmetadata.accessservices.subjectarea.server.spring.SubjectAreaGlossaryRESTResource.findGlossary(SubjectAreaGlossaryRESTResource.java:123)
        at jdk.internal.reflect.GeneratedMethodAccessor309.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

As an aside there are typedef exceptions - I will raise a new issue.
An example is:
```
Wed Aug 05 10:48:24 BST 2020 servergraph Types OMRS-AUDIT-0301 The local server has added a new type called SolutionPortDirection with a unique identifier of 4879c96e-26c7-48af-ba92-8277632be733 and a version number of 1 from ODPi Egeria (1.8)
Wed Aug 05 10:48:24 BST 2020 servergraph Exception OMRS-AUDIT-9019 The type definition event processor for the ODPi Egeria (1.8) service caught an unexpected exception java.lang.NullPointerException with message null
Wed Aug 05 10:48:24 BST 2020 servergraph Exception OMRS-AUDIT-9019 Supplementary information: log record id f195f8a0-9030-4d52-9b8c-4317b6c6de08 java.lang.NullPointerException returned message of null and stacktrace of
java.lang.NullPointerException
        at org.odpi.openmetadata.adapters.repositoryservices.graphrepository.repositoryconnector.GraphOMRSMetadataCollection.verifyTypeDef(GraphOMRSMetadataCollection.java:130)
        at org.odpi.openmetadata.repositoryservices.localrepository.repositoryconnector.LocalOMRSMetadataCollection.verifyTypeDef(LocalOMRSMetadataCollection.java:835)
        at org.odpi.openmetadata.repositoryservices.localrepository.repositorycontentmanager.OMRSRepositoryContentManager.processNewTypeDefEvent(OMRSRepositoryContentManager.java:2443)
        at org.odpi.openmetadata.repositoryservices.archivemanager.OMRSArchiveManager.processTypeDefStore(OMRSArchiveManager.java:300)
        at org.odpi.openmetadata.repositoryservices.archivemanager.OMRSArchiveManager.processOpenMetadataArchive(OMRSArchiveManager.java:211)
        at org.odpi.openmetadata.repositoryservices.archivemanager.OMRSArchiveManager.processOpenMetadataTypes(OMRSArchiveManager.java:139)
        at org.odpi.openmetadata.repositoryservices.archivemanager.OMRSArchiveManager.setLocalRepository(OMRSArchiveManager.java:102)
        at org.odpi.openmetadata.repositoryservices.admin.OMRSOperationalServices.initializeCohortMember(OMRSOperationalServices.java:430)
        at org.odpi.openmetadata.adminservices.OMAGServerOperationalServices.activateWithSuppliedConfig(OMAGServerOperationalServices.java:316)
        at org.odpi.openmetadata.adminservices.OMAGServerOperationalServices.activateWithStoredConfig(OMAGServerOperationalServices.java:152)
        at org.odpi.openmetadata.adminservices.spring.OperationalServicesResource.activateWithStoredConfig(OperationalServicesResource.java:59)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:832)
```
cc: @davidradl

**Comment by planetf1** [comment]
In fact the error seems to stem from:
```
Wed Aug 05 10:48:22 BST 2020 servergraph Startup OMRS-AUDIT-0030 Registering the Local Repository to Enterprise event consumer with the local repository outbou
nd event manager
10:48:23.898 [REST:OMAG Server Operational Services:activateWithSuppliedConfig] INFO  o.j.g.i.UniqueInstanceIdRetriever - Generated unique-instance-id=0a090028
66307-planetf1mac1
10:48:24.023 [REST:OMAG Server Operational Services:activateWithSuppliedConfig] INFO  org.janusgraph.diskstorage.Backend - Configuring index [search]
10:48:24.242 [REST:OMAG Server Operational Services:activateWithSuppliedConfig] INFO  org.janusgraph.diskstorage.Backend - Initiated backend operations thread
pool of size 16
10:48:24.405 [REST:OMAG Server Operational Services:activateWithSuppliedConfig] INFO  o.j.diskstorage.log.kcvs.KCVSLog - Loaded unidentified ReadMarker start t
ime 2020-08-05T09:48:24.405115Z into org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller@4c0419cc
10:48:24.775 [REST:OMAG Server Operational Services:activateWithSuppliedConfig] ERROR o.o.o.a.r.g.r.GraphOMRSGraphFactory - checkAndUpdateControlInformation Th
e graph database for repository servergraph has metadataCollectionId 5fc44583-7124-476f-bb3c-14ab13e25ff1, and cannot be opened using metadataCollectionId 5784
77d2-cb92-4177-b533-e1d56cdf5799
Wed Aug 05 10:48:24 BST 2020 servergraph Exception OMRS-GRAPH-REPOSITORY-0002 The OMRS Graph Database servergraph contains a metadataCollectionId 5fc44583-7124
-476f-bb3c-14ab13e25ff1 that does not match the repositorys metadataCollectionId {2}.
10:48:24.778 [REST:OMAG Server Operational Services:activateWithSuppliedConfig] ERROR o.o.o.a.r.g.r.GraphOMRSGraphFactory - open Check and update of control ve
rtex failed, exception OMRS-GRAPH-REPOSITORY-400-022 It is not possible to open the graph database with metadataCollectionId checkAndUpdateControlInformation,
because the repository connector has metadataCollectionId org.odpi.openmetadata.adapters.repositoryservices.graphrepository.repositoryconnector.GraphOMRSGraphF
actory
10:48:24.778 [REST:OMAG Server Operational Services:activateWithSuppliedConfig] ERROR o.o.o.a.r.g.r.GraphOMRSMetadataStore - GraphOMRSMetadataStore Could not o
pen graph database
10:48:24.778 [REST:OMAG Server Operational Services:activateWithSuppliedConfig] ERROR o.o.o.a.r.g.r.GraphOMRSMetadataCollection - GraphOMRSMetadataCollection c
ould not create graph metadata collection for repository name servergraph
Wed Aug 05 10:48:24 BST 2020 servergraph Information OMRS-AUDIT-0050 The Open Metadata Repository Services (OMRS) is about to process open metadata archive Ope
n Metadata Types
```

**Comment by planetf1** [comment]
ie the graph repo -- in this test configuration -- is not working. Most likely a classpath issue.

I will investigate further and correct.

**Comment by planetf1** [comment]
interestingly enough despite all the errors, the OMRS reports successful startup -- we are failing to pick up a rather broken graph error here 

```
Wed Aug 05 10:48:24 BST 2020 servergraph Startup OMRS-AUDIT-0007 The Open Metadata Repository Services (OMRS) has initialized
```

**Comment by grahamwallis** [comment]
If the graph connectors reports a mismatch of metadataCollectionId it's most likely to be a configuration problem - resulting in an attempt to acquire an existing graph database under a new metadataCollectionId. 

The error message from the graph connector was badly formatted - looks like the parameters to the error message are misaligned.

**Comment by grahamwallis** [comment]
Raised issue #3448 to cover the error message formatting problem.

**Comment by planetf1** [comment]
Thanks @grahamwallis . A silly error on my behalf -- I hadn't added the relevant cleanup of the graph repo for the tests to start clean each time.

Now fixed, just leaving the same issues that @popa-raluca spotted with the inmem vs graph testing, and also consistent with my results in IntelliJ

Any refactoring/improvement aside, this PR should be good to merge once we've fixed the underlying issue -- which I think @davidradl is currently looking it

**Comment by planetf1** [comment]
```
[ERROR] Failures: 
[ERROR]   GraphIT.testGraph:17 Unexpected exception thrown: org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException: OMAG-COMMON-400-016 An unexpected org.odpi.openmetadata.accessservices.subjectarea.handlers.SubjectAreaGlossaryHandler exception was caught by create for Glossary; error message was OMAG-REPOSITORY-HANDLER-400-003 An unexpected error was returned by the metadata server during createGlossary request for open metadata access service Subject Area OMAS on server servergraph; message was OMRS-GRAPH-REPOSITORY-400-003 The attempt to create an entity with GUID 420eb613-c04d-439e-9529-0101dd892e19 failed in createEntityInStore method of class org.odpi.openmetadata.adapters.repositoryservices.graphrepository.repositoryconnector.GraphOMRSMetadataStore to open metadata repository servergraph
[ERROR]   SubjectAreaDefinitionCategoryIT.testSubjectAreaDefinitionCategory:17 Unexpected exception thrown: org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException: OMAG-COMMON-400-016 An unexpected org.odpi.openmetadata.accessservices.subjectarea.handlers.SubjectAreaCategoryHandler exception was caught by create for SubjectAreaDefinition; error message was OMAG-REPOSITORY-HANDLER-400-003 An unexpected error was returned by the metadata server during createCategory request for open metadata access service Subject Area OMAS on server servergraph; message was OMRS-GRAPH-REPOSITORY-400-003 The attempt to create an entity with GUID c2b7eabf-1b42-4e88-9720-2c0470884fd3 failed in createEntityInStore method of class org.odpi.openmetadata.adapters.repositoryservices.graphrepository.repositoryconnector.GraphOMRSMetadataStore to open metadata repository servergraph
[ERROR]   TermIT.testTerm:17 Unexpected exception thrown: org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException: OMAG-COMMON-400-016 An unexpected org.odpi.openmetadata.accessservices.subjectarea.handlers.SubjectAreaTermHandler exception was caught by create for Term; error message was OMAG-REPOSITORY-HANDLER-400-003 An unexpected error was returned by the metadata server during createTerm request for open metadata access service Subject Area OMAS on server servergraph; message was OMRS-GRAPH-REPOSITORY-400-003 The attempt to create an entity with GUID 0ff3df9a-3800-4d23-abb3-5c0d02ceb202 failed in createEntityInStore method of class org.odpi.openmetadata.adapters.repositoryservices.graphrepository.repositoryconnector.GraphOMRSMetadataStore to open metadata repository servergraph
[INFO] 
[ERROR] Tests run: 18, Failures: 3, Errors: 0, Skipped: 0
```

**Comment by planetf1** [comment]
I've also opened up https://github.com/odpi/egeria/issues/3451 to track the issue with the server starting when it shouldn't
