### ISSUE TITLE
Unable to create schemas as part of Asset Owner OMAS

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#3568]
It does not appear to be possible at the moment to create (and attach) schemas to Assets as part of the Asset Owner OMAS.

For example, against an existing Asset, if you attempt to POST the following to `/servers/omas/open-metadata/access-services/asset-owner/users/{{user}}/assets/{{assetGUID}}/schemas/top-level-schema-type`:

```json
{
    "class": "SchemaTypeRequestBody",
    "schemaTypeProperties": {
        "class": "SchemaTypeProperties",
        "typeName": "RelationalDBSchemaType",
        "qualifiedName": "host=my.system.com::database=MYDBNAME::schema_type=MYSCHEMA",
        "displayName": "MYSCHEMA"
    }
}
```

You receive a response of:

```json
{
    "class": "GUIDResponse",
    "relatedHTTPCode": 400,
    "exceptionClassName": "org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException",
    "actionDescription": "addSchemaType",
    "exceptionErrorMessage": "OMAG-REPOSITORY-HANDLER-400-003 An unexpected error was returned by the metadata server during addSchemaType request for open metadata access service Asset Owner OMAS on server omas; message was OMRS-REPOSITORY-400-022 A null unique identifier (guid) for a TypeDef object has been passed as the entityTypeGUID parameter on a addEntity request to open metadata repository omas",
    "exceptionErrorMessageId": "OMAG-REPOSITORY-HANDLER-400-003",
    "exceptionErrorMessageParameters": [
        "OMRS-REPOSITORY-400-022 A null unique identifier (guid) for a TypeDef object has been passed as the entityTypeGUID parameter on a addEntity request to open metadata repository omas",
        "addSchemaType",
        "Asset Owner OMAS",
        "omas"
    ],
    "exceptionSystemAction": "The system is unable to process the request because of an internal error.",
    "exceptionUserAction": "Verify the sanity of the server.  This is probably a logic error.  If you can not work out what happened, ask the ODPi Egeria community for help."
}
```

The exception stack trace on the console of the OMAG platform running the OMAS indicates the following:

```
12:06:46.118 [REST:Asset Owner OMAS:addSchemaTypeToAsset] ERROR o.o.o.c.ffdc.RESTExceptionHandler - Exception from addSchemaTypeToAsset being packaged for return on REST call
org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException: OMAG-REPOSITORY-HANDLER-400-003 An unexpected error was returned by the metadata server during addSchemaType request for open metadata access service Asset Owner OMAS on server omas; message was OMRS-REPOSITORY-400-022 A null unique identifier (guid) for a TypeDef object has been passed as the entityTypeGUID parameter on a addEntity request to open metadata repository omas
	at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryErrorHandler.handleRepositoryError(RepositoryErrorHandler.java:300)
	at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryHandler.createEntity(RepositoryHandler.java:290)
	at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryHandler.createEntity(RepositoryHandler.java:168)
	at org.odpi.openmetadata.commonservices.ocf.metadatamanagement.handlers.SchemaTypeHandler.addSchemaType(SchemaTypeHandler.java:1663)
	at org.odpi.openmetadata.commonservices.ocf.metadatamanagement.handlers.SchemaTypeHandler.saveSchemaType(SchemaTypeHandler.java:1593)
	at org.odpi.openmetadata.commonservices.ocf.metadatamanagement.handlers.SchemaTypeHandler.saveSchemaType(SchemaTypeHandler.java:1557)
	at org.odpi.openmetadata.commonservices.ocf.metadatamanagement.handlers.AssetHandler.saveAssociatedSchemaType(AssetHandler.java:676)
	at org.odpi.openmetadata.commonservices.ocf.metadatamanagement.handlers.AssetHandler.saveAssociatedSchemaType(AssetHandler.java:625)
	at org.odpi.openmetadata.accessservices.assetowner.server.AssetOwnerRESTServices.addSchemaTypeToAsset(AssetOwnerRESTServices.java:305)
	at org.odpi.openmetadata.accessservices.assetowner.server.spring.AssetOwnerResource.addSchemaTypeToAsset(AssetOwnerResource.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

Looking at the details of the stack trace, it appears that:

- By having only the `typeName` provided as part of the `SchemaTypeProperties` in the request body, there is never a resolution of the TypeDef's GUID (ie. in the `cloneProperties()` method of `SchemaTypeProperties` that sets up and returns the `SchemaType` object used by the rest of the stack, only the `setElementTypeName()` is used to setup the TypeDef's name, but nowhere is the TypeDef's ID (GUID) set)
- Hence, when the `addSchemaType()` method of `SchemaTypeHandler` is eventually called, and within it the `createEntity()` is called against the repository handler, the attempt to call `this.getSchemaTypeTypeGUID(schemaType)` actually returns null (as the `ElementType` of the `SchemaType` is not null, but its `getElementTypeId()` is.)

**Comment by cmgrote** [comment]
As discussed, I'll create a temporary quick-fix for now.
