### ISSUE TITLE
I have a problem with 2.3 release during startup server-chassis-spring

### ISSUE THREAD

**Issue by immmus** [odpi/egeria#3757]
Hi @planetf1 @grahamwallis ! after update to 2.3 I got this problem. 
```
15:12:34.476 [main] INFO  o.o.o.s.s.OMAGServerPlatform - Starting OMAGServerPlatform on MacBook-Pro-Ila.local with PID 33035 (/Users/immmus/IdeaProjects/bdp-uad-backend/egeria-servers-starter/server-chassis-spring-2.3.jar started by immmus in /Users/immmus/IdeaProjects/bdp-uad-backend/egeria-servers-starter)
15:12:34.484 [main] INFO  o.o.o.s.s.OMAGServerPlatform - No active profile set, falling back to default profiles: default
15:12:38.279 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 9443 (https)
15:12:38.295 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["https-jsse-nio-9443"]
15:12:38.296 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
15:12:38.296 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.36]
15:12:38.406 [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
15:12:40.020 [main] INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat]
15:12:40.048 [main] ERROR o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dinoViewRESTResource' defined in URL [jar:file:/Users/immmus/IdeaProjects/bdp-uad-backend/egeria-servers-starter/server-chassis-spring-2.3.jar!/BOOT-INF/lib/dino-view-spring-2.3.jar!/org/odpi/openmetadata/viewservices/dino/server/DinoViewRESTResource.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.odpi.openmetadata.viewservices.dino.server.DinoViewRESTResource]: Constructor threw exception; nested exception is java.lang.NoSuchFieldError: org/odpi/openmetadata/adminservices/configuration/registration/ViewServiceDescription.DINO
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1320)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1214)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$293/0000000000000000.getObject(Unknown Source)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:893)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.odpi.openmetadata.serverchassis.springboot.OMAGServerPlatform.main(OMAGServerPlatform.java:94)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:466)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.odpi.openmetadata.viewservices.dino.server.DinoViewRESTResource]: Constructor threw exception; nested exception is java.lang.NoSuchFieldError: org/odpi/openmetadata/adminservices/configuration/registration/ViewServiceDescription.DINO
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:217)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1312)
        ... 27 common frames omitted
Caused by: java.lang.NoSuchFieldError: org/odpi/openmetadata/adminservices/configuration/registration/ViewServiceDescription.DINO
        at org.odpi.openmetadata.viewservices.dino.server.DinoViewInstanceHandler.<init>(DinoViewInstanceHandler.java:28)
        at org.odpi.openmetadata.viewservices.dino.server.DinoViewRESTServices.<clinit>(DinoViewRESTServices.java:44)
        at org.odpi.openmetadata.viewservices.dino.server.DinoViewRESTResource.<init>(DinoViewRESTResource.java:38)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204)
        ... 29 common frames omitted

```

**Comment by grahamwallis** [comment]
@immus Hi Ilya - that looks strange. In both the 2.3 release branch and in master the ViewDescription class has entries for 4 view services, including Dino. Are you sure you have upgraded fully to 2.3?

**Comment by immmus** [comment]
> @immus Hi Ilya - that looks strange. In both the 2.3 release branch and in master the ViewDescription class has entries for 4 view services, including Dino. Are you sure you have upgraded fully to 2.3?

Yes, I use branch egeria-release-2.3

**Comment by grahamwallis** [comment]
@immus - Are you building from source or using a 2.3 assembly? Also, I'm not sure if it will make a difference, but are you running locally or in a container?

**Comment by immmus** [comment]
> @immus - Are you building from source or using a 2.3 assembly? Also, I'm not sure if it will make a difference, but are you running locally or in a container?

Sorry, full clear local maven repo and rebild project after, resoled the problem.

**Comment by immmus** [comment]
> @immus - no problem. Glad you resolved it.

Thank you=)
