### ISSUE TITLE
Unit test failure in data Engine Server with latest surefire plugin

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3991]
In PR #3830 dependabot proposed an update in maven-surefire-plugin from 3.0.0-M4 to 3.0.0-M5

A test in data engine fails after this update - it looks as if perhaps this is a genuine failure.

The failing test ig 'addPortDelegationRelationship_InvalidPortType'

The test result is reported as:
```


Argument(s) are different! Wanted:
dataEngineCommonHandler.throwInvalidParameterException(
    INVALID_PORT_TYPE,
    "addPortDelegationRelationship",
    "delegated",
    "OUTIN_PORT"
);
-> at org.odpi.openmetadata.accessservices.dataengine.server.handlers.PortHandlerTest.addPortDelegationRelationship_InvalidPortType(PortHandlerTest.java:341)
Actual invocations have different arguments:
dataEngineCommonHandler.findEntity(
    "user",
    "delegated",
    "PortAlias"
);
-> at org.odpi.openmetadata.accessservices.dataengine.server.handlers.PortHandler.findPortAliasEntity(PortHandler.java:341)
dataEngineCommonHandler.throwInvalidParameterException(
    INVALID_PORT_TYPE,
    "addPortDelegationRelationship",
    "qualifiedName",
    "delegated",
    "INPUT_PORT"
);
-> at org.odpi.openmetadata.accessservices.dataengine.server.handlers.PortHandler.addPortDelegationRelationship(PortHandler.java:282)

Comparison Failure: 
<Click to see difference>

Argument(s) are different! Wanted:
dataEngineCommonHandler.throwInvalidParameterException(
    INVALID_PORT_TYPE,
    "addPortDelegationRelationship",
    "delegated",
    "OUTIN_PORT"
);
-> at org.odpi.openmetadata.accessservices.dataengine.server.handlers.PortHandlerTest.addPortDelegationRelationship_InvalidPortType(PortHandlerTest.java:341)
Actual invocations have different arguments:
dataEngineCommonHandler.findEntity(
    "user",
    "delegated",
    "PortAlias"
);
-> at org.odpi.openmetadata.accessservices.dataengine.server.handlers.PortHandler.findPortAliasEntity(PortHandler.java:341)
dataEngineCommonHandler.throwInvalidParameterException(
    INVALID_PORT_TYPE,
    "addPortDelegationRelationship",
    "qualifiedName",
    "delegated",
    "INPUT_PORT"
);
-> at org.odpi.openmetadata.accessservices.dataengine.server.handlers.PortHandler.addPortDelegationRelationship(PortHandler.java:282)

	at org.odpi.openmetadata.accessservices.dataengine.server.handlers.PortHandlerTest.addPortDelegationRelationship_InvalidPortType(PortHandlerTest.java:341)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

```
when run in IntelliJ

The test is:
```
   void addPortDelegationRelationship_InvalidPortType() throws UserNotAuthorizedException, PropertyServerException,
                                                                InvalidParameterException {
        mockDelegatedPortEntity(PortType.OUTIN_PORT);

        portHandler.addPortDelegationRelationship(USER, GUID, PortType.INPUT_PORT, DELEGATED_QUALIFIED_NAME, EXTERNAL_SOURCE_DE_QUALIFIED_NAME);

        verify(dataEngineCommonHandler, times(1)).throwInvalidParameterException(DataEngineErrorCode.INVALID_PORT_TYPE,
                "addPortDelegationRelationship", DELEGATED_QUALIFIED_NAME, PortType.OUTIN_PORT.getName());
    }
```
A clearer comparison is shown as:

<img width="1068" alt="Screenshot 2020-10-28 at 08 54 20" src="https://user-images.githubusercontent.com/7292002/97413887-36ca0800-18fb-11eb-8b30-971caa07f0da.png">

This implies that the exception being generated is incorrect -- the wrong porttype (INOUT) and missing qualified name 

What is unclear is why an update to surefire -- which is really just executing the tests -- is causing this failure.It seems as if previously this failure was missed

HOWEVER when run under intellij (CRTL-SHIFT-R on the handlers test directory) the failure occurs every time, regardless of the maven plugin setting (which isn't involved)

This suggests it is a genuine failure that we previously missed

cc: @mandy-chessell

**Comment by planetf1** [comment]
This is a genuine failure
 - The code in PortHandler.java is logging the port type PASSED IN, whilst the exception refers to the porttype as the EXPECTED port type. The unit test is correct, it's mocking an OUTIN but passing INPUT.

**Comment by planetf1** [comment]
Also noticed the test code was failing to recognize the common error handling invocation also passes the parm name
