### ISSUE TITLE
NPE from MapPropertyValue.valueAsObject if any null values in the map

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#4089]
It seems that the `valueAsObject` method on a `MapPropertyValue` object can throw a NullPointerException if any of the values in the map are null (which seems to be a known issue with Collectors.toMap(): https://bugs.openjdk.java.net/browse/JDK-8148463)

Example error:

```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.odpi.openmetadata.repositoryservices.connectors.stores.metadatacollectionstore.properties.instances.InstancePropertyValue.convertValues(InstancePropertyValue.java:153)
	at org.odpi.openmetadata.repositoryservices.connectors.stores.metadatacollectionstore.properties.instances.InstancePropertyValue.mapValuesAsObject(InstancePropertyValue.java:116)
	at org.odpi.openmetadata.repositoryservices.connectors.stores.metadatacollectionstore.properties.instances.MapPropertyValue.valueAsObject(MapPropertyValue.java:83)
```

**Comment by cmgrote** [comment]
@popa-raluca I notice that the `LineageGraphConnector` class is also using `Collectors.toMap()` -- if there is any possibility that the `getValue()` against an entry will return null, this is probably worth being aware of (as it will apparently result in a runtime NPE)...
