### ISSUE TITLE
Spring UI unit tests fail

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4288]
#4264 corrects a bug where unit tests were not correctly running for all components

With this fixed, the ui chassis spring UTs fail with errors as show at https://gist.github.com/planetf1/0b84b83d6d7b4fd0e988b6237bf99862

If references to junit / runner are removed (since the tests are JUnit5) the actual tests then fail as per:
https://gist.github.com/planetf1/8694db0f363183f71be1bfd8d9efedd8

for example we see:

```
[ERROR] testUltimateDestination  Time elapsed: 0.078 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "org.odpi.openmetadata.userinterface.uichassis.springboot.service.LineageGraphDisplayRulesService.applyRules(org.odpi.openmetadata.userinterface.uichassis.springboot.beans.Graph)" because "this.lineageGraphDisplayRulesService" is null
	at org.odpi.openmetadata.userinterface.uichassis.springboot.service.OpenLineageServiceTest.testUltimateDestination(OpenLineageServiceTest.java:107)

[ERROR] testUltimateSource  Time elapsed: 0.033 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "org.odpi.openmetadata.userinterface.uichassis.springboot.service.LineageGraphDisplayRulesService.applyRules(org.odpi.openmetadata.userinterface.uichassis.springboot.beans.Graph)" because "this.lineageGraphDisplayRulesService" is null
	at org.odpi.openmetadata.userinterface.uichassis.springboot.service.OpenLineageServiceTest.testUltimateSource(OpenLineageServiceTest.java:80)
```

Given these failures, and they are not running currently, in #4264 these tests will be disabled and the component owner will need to fix

**Comment by sarbull** [comment]
@alexandra-bucur can you check this?

**Comment by planetf1** [comment]
Tests still fail here.

```
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ ui-chassis-spring ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.131 s
[INFO] Finished at: 2020-12-11T14:22:22Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project ui-chassis-spring: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test failed: org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-vintage' failed to discover tests: Failed to parse version of junit:junit: 4.13.1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

if this change is made to activate them in the build (they were intentionally disabled in a prior PR as they were failing).
```
diff --git a/open-metadata-implementation/user-interfaces/ui-chassis/ui-chassis-spring/pom.xml b/open-metadata-implementation/user-interfaces/ui-chassis/ui-chassis-spring/pom.xml
index 5df267cecf..0dc6021382 100644
--- a/open-metadata-implementation/user-interfaces/ui-chassis/ui-chassis-spring/pom.xml
+++ b/open-metadata-implementation/user-interfaces/ui-chassis/ui-chassis-spring/pom.xml
@@ -384,7 +384,7 @@
                         <classpathDependencyExclude>org.slf4j:slf4j-simple</classpathDependencyExclude>
                     </classpathDependencyExcludes>
                     <!-- TODO: tests disabled due to issue 4288 -->
-                    <skip>true</skip>
+                    <skip>false</skip>
                 </configuration>
             </plugin>
             <plugin>
```

**Comment by planetf1** [comment]
This line needs to be removed so tests run by default as a minimum. The current error may just be a pom/config issue if the underlying java code is now fixed

**Comment by planetf1** [comment]
I have fixed this now. assigning. Will enter a PR
