### ISSUE TITLE
Atlas -503 error

### ISSUE THREAD

**Issue by vijay-kattula** [odpi/egeria#4319]
Hi Team,'

I have deployed odpi/apache-atlas image in my docker environment and logs showing it is running on port 21000 but when i hit the url in browser or when i curl the url in container i am getting below error.
HTTP ERROR: 503
Problem accessing /. Reason:

    Service Unavailable
Powered by Jetty:// 9.3.14.v20161028

Please help

**Comment by vijay-kattula** [comment]
when i cat atlas.20201215.out i got below error

**Comment by vijay-kattula** [comment]
Caused by: org.janusgraph.core.JanusGraphException: Could not register new index field with index backend
        at org.janusgraph.graphdb.database.management.ManagementSystem.addIndexKey(ManagementSystem.java:531)
        at org.apache.atlas.repository.graphdb.janus.AtlasJanusGraphManagement.addMixedIndex(AtlasJanusGraphManagement.java:202)
        at org.apache.atlas.repository.graph.GraphBackedSearchIndexer.createVertexIndex(GraphBackedSearchIndexer.java:518)
        at org.apache.atlas.repository.graph.GraphBackedSearchIndexer.initialize(GraphBackedSearchIndexer.java:269)
        ... 87 more
Caused by: org.janusgraph.diskstorage.PermanentBackendException: Permanent failure in storage backend
        at org.janusgraph.diskstorage.solr.Solr6Index.register(Solr6Index.java:309)
        at org.janusgraph.diskstorage.indexing.IndexTransaction.register(IndexTransaction.java:96)
        at org.janusgraph.graphdb.database.IndexSerializer.register(IndexSerializer.java:105)
        at org.janusgraph.graphdb.database.management.ManagementSystem.addIndexKey(ManagementSystem.java:529)
        ... 90 more
Caused by: org.apache.solr.client.solrj.SolrServerException: 172.17.0.4:9838_solr=org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException:Error from server at http://172.17.0.4:9838/solr: Error CREATEing SolrCore 'vertex_index_shard1_replica_n1': Unable to create core [vertex_index_shard1_replica_n1] Caused by: no segments* file found in LockValidatingDirectoryWrapper(NRTCachingDirectory(MMapDirectory@/opt/apache/atlas/solr/server/solr/vertex_index_shard1_replica_n1/data/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@7541d801; maxCacheMB=48.0 maxMergeSizeMB=4.0)): files: [write.lock]
        at org.janusgraph.diskstorage.solr.Solr6Index.createCollectionIfNotExists(Solr6Index.java:1090)
        at org.janusgraph.diskstorage.solr.Solr6Index.register(Solr6Index.java:307)
        ... 93 more
08:28:30,633  INFO AbstractConnector:278 - Started ServerConnector@38bc5ac0{HTTP/1.1,[http/1.1]}{0.0.0.0:21000}
08:28:30,634  INFO Server:414 - Started @49602ms
08:28:52,983  INFO ZooKeeper:684 - Session: 0x1766582dc910009 closed
08:28:52,983  INFO ClientCnxn:512 - EventThread shut down

**Comment by planetf1** [comment]
Hi,
 We originally create the Apache Atlas image to use in our 'vdc' helm chart which was to demo a virtual data connector
environment with Egeria. An egeria connector was built. However As priorities evolved we didn't persue that further. There is an intent to revisit Hadoop integration very soon, likely making use of some new APIs available for integration. As part of this we plan to move the atlas and ranger related code/images out of the core repo & into the egeria-hadoop-ecosystem repository

As such the docker image for atlas has not been checked closely. 

Can you expand on your interest in the image? Is it to run standalone? Are you trying out the existing atlas egeria connector? Are you looking for atlas integration with egeria? Or integration with other hadoop components? Are you trying to run our VDC demo? Knowing this may help me point you in the most fruitful direction :-)

Back to the actual problem you mention. I did see this in #3118 but in cursory usage it appeared to have gone away. 

If it was necessary to get this working, I'd be inclined to 
 a) check both the docker builds are current (we have a base image then a customized image - only the latter is being built automatically)
 b) Look at the version of solr being used - can we update
 c) Consider updating the level of atlas being built
 d) If required, look to test the existing connector works

**Comment by planetf1** [comment]
Closing for now. please re-open if you have further information
