### ISSUE TITLE
Asset analysis api tests fail when run from surefire

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4332]
In PR #4330 I have (hopefully, again!) fixed the maven build to ensure all tests are run.

With that in place, the asset analysis api tests fail.

I have disabled the tests (see the pom in that module & search for skip) and recording the issue here for later investigation 
```
12:31:58,239 [INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ asset-analysis-api ---
12:31:58,247 [INFO]
12:31:58,247 [INFO] -------------------------------------------------------
12:31:58,248 [INFO]  T E S T S
12:31:58,248 [INFO] -------------------------------------------------------
12:31:59,068 [INFO] Running org.odpi.openmetadata.engineservices.assetanalysis.ffdc.ErrorCodeTest
12:31:59,149 [INFO] Running org.odpi.openmetadata.engineservices.assetanalysis.ffdc.AuditCodeTest
12:32:00,016 [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.945 s <<< FAILURE! - in org.odpi.openmetadata.engines
ervices.assetanalysis.ffdc.ErrorCodeTest
12:32:00,018 [ERROR] org.odpi.openmetadata.engineservices.assetanalysis.ffdc.ErrorCodeTest.testAllErrorCodeValues  Time elapsed: 0.022 s  <<
< FAILURE!
java.lang.AssertionError: Message definition ASSET-ANALYSIS-OMES-400-007  does not start with the correct message prefix: OMES-ASSET-ANALYSI
S expected [true] but found [false]
        at org.odpi.openmetadata.engineservices.assetanalysis.ffdc.ErrorCodeTest.testAllErrorCodeValues(ErrorCodeTest.java:26)

12:32:00,269 [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.118 s <<< FAILURE! - in org.odpi.openmetadata.engines
ervices.assetanalysis.ffdc.AuditCodeTest
12:32:00,270 [ERROR] org.odpi.openmetadata.engineservices.assetanalysis.ffdc.AuditCodeTest.testAllErrorCodeValues  Time elapsed: 0.036 s  <<
< FAILURE!
java.lang.AssertionError: Message definition ASSET-ANALYSIS-OMES-0001 does not start with the correct message prefix: OMES-ASSET-ANALYSIS ex
pected [true] but found [false]
        at org.odpi.openmetadata.engineservices.assetanalysis.ffdc.AuditCodeTest.testAllErrorCodeValues(AuditCodeTest.java:25)

12:32:00,293 [INFO]
12:32:00,293 [INFO] Results:
12:32:00,293 [INFO]
12:32:00,293 [ERROR] Failures:
12:32:00,293 [ERROR]   AuditCodeTest.testAllErrorCodeValues:25->AuditLogMessageSetTest.testSingleAuditCodeValue:30->MessageSetTest.testSingl
eMessageDefinitionValues:134 Message definition ASSET-ANALYSIS-OMES-0001 does not start with the correct message prefix: OMES-ASSET-ANALYSIS
 expected [true] but found [false]
12:32:00,295 [ERROR]   ErrorCodeTest.testAllErrorCodeValues:26->ExceptionMessageSetTest.testSingleErrorCodeValue:30->MessageSetTest.testSing
leMessageDefinitionValues:134 Message definition ASSET-ANALYSIS-OMES-400-007  does not start with the correct message prefix: OMES-ASSET-ANA
LYSIS expected [true] but found [false]
12:32:00,296 [INFO]
12:32:00,296 [ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0
12:32:00,296 [INFO]
12:32:00,298 [INFO] ------------------------------------------------------------------------
```

**Comment by mandy-chessell** [comment]
No kidding !!!
```
public class ErrorCodeTest extends ExceptionMessageSetTest
{
    final static String  messageIdPrefix = "OMES-ASSET-ANALYSIS";

    /**
     * Validated the values of the enum.
     */
    @Test public void testAllErrorCodeValues()
    {
        for (AssetAnalysisErrorCode errorCode : AssetAnalysisErrorCode.values())
        {
            super.testSingleErrorCodeValue(errorCode, messageIdPrefix);
        }
    }
}
```
