### ISSUE TITLE
Release 2.6 Egeria UI (polymer) fails to start in coco lab environment

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4490]
When the coco pharma notebook environment is run in k8s, the UI pod fails to initialize with:
```
 ODPi Egeria

       ______                        _                  __  __   ____
      / ____/ ____ _  ___    _____  (_) ____ _         / / / /  /  _/
     / __/   / __ `/ / _ \  / ___/ / / / __ `/        / / / /   / /
    / /___  / /_/ / /  __/ / /    / / / /_/ /        / /_/ /  _/ /
   /_____/  \__, /  \___/ /_/    /_/  \__,_/         \____/  /___/
           /____/


 :: Powered by Spring Boot (v2.3.3.RELEASE) ::

2021-01-18 13:08:29.760 - INFO 1 --- [           main] o.o.o.u.u.springboot.EgeriaUIPlatform    : No active profile set, falling back to default profiles: default
2021-01-18 13:08:33.580 - INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8443 (https)
Exception in thread "task-2" java.lang.IllegalStateException: EntityManagerFactory is closed
	at org.hibernate.internal.SessionFactoryImpl.validateNotClosed(SessionFactoryImpl.java:509)
	at org.hibernate.internal.SessionFactoryImpl.getProperties(SessionFactoryImpl.java:503)
	at org.springframework.boot.autoconfigure.orm.jpa.DataSourceInitializedPublisher.findDataSource(DataSourceInitializedPublisher.java:105)
	at org.springframework.boot.autoconfigure.orm.jpa.DataSourceInitializedPublisher.publishEventIfRequired(DataSourceInitializedPublisher.java:97)
	at org.springframework.boot.autoconfigure.orm.jpa.DataSourceInitializedPublisher.access$100(DataSourceInitializedPublisher.java:50)
	at org.springframework.boot.autoconfigure.orm.jpa.DataSourceInitializedPublisher$DataSourceSchemaCreatedPublisher.lambda$postProcessEntityManagerFactory$0(DataSourceInitializedPublisher.java:200)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-18 13:08:36.968 -ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'securityConfig': Unsatisfied dependency expressed through field 'tokenRedisClient'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'logoutController': Unsatisfied dependency expressed through field 'tokenRedisClient'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'tokenRedisClient': Requested bean is currently in creation: Is there an unresolvable circular reference?
```

**Comment by planetf1** [comment]
@bogdan-sava I assume this is down to some recent configuration changes to support optional redis configuration.

I suggest one of two actions.

Either
 a) We need to fix and maintain the UI working in this environment (probably a minor configuration detail). We also need
to extend the configuration to support more of the UI's features. For example, There is a lab UI notebook which points at the UI, though there aren't any exercises written . Additionally whilst the UI exposes function like OLS, this is not configured in the notebook environment and causes confusion with new users looking at the tutorials
 or
 b) We remove the polymer UI from this environment and focus lab tutorials around presentation server

**Comment by planetf1** [comment]
Having retested, the UI is now working.

WIll close for now, and reopen if the issue resurfaces. It's possible there is some kind of timing issue

**Comment by planetf1** [comment]
The spring UI is failing to start in our release 2.6 testing in the coco pharma environment

This has happened again - a slight variation:

```
 ODPi Egeria

       ______                        _                  __  __   ____
      / ____/ ____ _  ___    _____  (_) ____ _         / / / /  /  _/
     / __/   / __ `/ / _ \  / ___/ / / / __ `/        / / / /   / /
    / /___  / /_/ / /  __/ / /    / / / /_/ /        / /_/ /  _/ /
   /_____/  \__, /  \___/ /_/    /_/  \__,_/         \____/  /___/
           /____/


 :: Powered by Spring Boot (v2.3.3.RELEASE) ::

2021-01-28 13:37:33.010 - INFO 1 --- [           main] o.o.o.u.u.springboot.EgeriaUIPlatform    : No active profile set, falling back to default profiles: default
2021-01-28 13:37:54.515 - INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8443 (https)
Exception in thread "task-2" org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'delegatingApplicationListener': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:220)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
	at org.springframework.context.event.AbstractApplicationEventMulticaster.retrieveApplicationListeners(AbstractApplicationEventMulticaster.java:247)
```

The full log is at https://gist.github.com/929d40078baf31a57edfd57e3a542a15

**Comment by planetf1** [comment]
Retested on 2.6 after fixes for other test issues. - the problem is still occuring

A full log is posted to https://gist.github.com/d5832c604a3ba24e4c2ae063018e7f2d

It looks as if there is a dependency on redis. I do not have any customized application properties other than the omas.server parameters for search

We have three options
 - Fix the UI to work for the 2.6 release - best? - urgent
 - Remove the UI, if it's not intended to maintain it in the coco pharma environment 
 - Leave it in but broken -- I don't like this as users will see k8s warnings, failures

**Comment by planetf1** [comment]
I tried running the jar directly (built on mac) - not assembly - and got a somewhat different error - this time I additionally had a netflix zuul error:

See https://gist.github.com/b49b6f342ef4108eeedc5a772aad2e92

I then tried running from the assembly after building locally & had the same error as above -- ie both from zuul and redis.

**Comment by planetf1** [comment]
The environment of the running container can be seen from the kube output at https://gist.github.com/2070505e3c51cb3860ce1a5cc38623f9

**Comment by bogdan-sava** [comment]
the PR is https://github.com/odpi/egeria/pull/4651

**Comment by planetf1** [comment]
After this fix (tested on 2.6) the ui chassis correctly starts in the Coco environment, and I am able to retrieve file assets created by the data catalog notebook. Details are correctly shown including classifications etc.

Thanks, closing...

**Comment by sarbull** [comment]
we should extract and rename `ui-chassis-spring` to `egeria-api`

**Comment by planetf1** [comment]
> we should extract and rename `ui-chassis-spring` to `egeria-api`

Maybe persue in #4649? Sounds reasonable.
