### ISSUE TITLE
Data Engine OMAS is adding the same classification twice to an entity

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#4846]
I added an extra check to the enterprise repository connector to validate that OMASs are not over-writing an existing classification for an entity and the Data Engine OMAS FVT failed ...

```
[INFO] Wed Mar 03 09:43:19 GMT 2021 platform-3 Exception OMAG-REPOSITORY-HANDLER-0003 An unexpected error org.odpi.openmetadata.repositoryservices.ffdc.exception.ClassificationErrorException was returned to classifyEntity by the metadata server during createSchemaAttribute request for open metadata access service Data Engine OMAS on server platform-3; message was OMRS-REPOSITORY-400-081 A classifyEntity (Detailed) request has been made to repository platform-3 to add a classification TypeEmbeddedAttribute to entity d13d2717-164c-4439-b151-b3467af9d0bd when this entity is already classified
[INFO] Wed Mar 03 09:43:19 GMT 2021 platform-3 Exception OMAG-REPOSITORY-HANDLER-0003 Supplementary information: log record id 1b7bf786-3e1f-4b79-bf4a-a8b98663c244 org.odpi.openmetadata.repositoryservices.ffdc.exception.ClassificationErrorException returned message of OMRS-REPOSITORY-400-081 A classifyEntity (Detailed) request has been made to repository platform-3 to add a classification TypeEmbeddedAttribute to entity d13d2717-164c-4439-b151-b3467af9d0bd when this entity is already classified and stacktrace of 
[INFO] OCFCheckedExceptionBase{reportedHTTPCode=400, reportingClassName='org.odpi.openmetadata.repositoryservices.localrepository.repositorycontentmanager.OMRSRepositoryContentHelper', reportingActionDescription='classifyEntity (Detailed)', reportedErrorMessage='OMRS-REPOSITORY-400-081 A classifyEntity (Detailed) request has been made to repository platform-3 to add a classification TypeEmbeddedAttribute to entity d13d2717-164c-4439-b151-b3467af9d0bd when this entity is already classified', reportedErrorMessageId='OMRS-REPOSITORY-400-081', reportedErrorMessageParameters=[classifyEntity (Detailed), platform-3, TypeEmbeddedAttribute, d13d2717-164c-4439-b151-b3467af9d0bd], reportedSystemAction='The system is unable to perform the request as only one classification of a specific type is permitted.', reportedUserAction='Use the updateClassificationProperties to make changed to an existing classification.', reportedCaughtException=null, reportedCaughtExceptionClassName='null', relatedProperties=null}
[INFO] 	at org.odpi.openmetadata.repositoryservices.localrepository.repositorycontentmanager.OMRSRepositoryContentHelper.checkEntityNotClassifiedEntity(OMRSRepositoryContentHelper.java:1229)
[INFO] 	at org.odpi.openmetadata.repositoryservices.enterprise.repositoryconnector.EnterpriseOMRSMetadataCollection.classifyEntity(EnterpriseOMRSMetadataCollection.java:3176)
[INFO] 	at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryHandler.classifyEntity(RepositoryHandler.java:1674)
[INFO] 	at org.odpi.openmetadata.accessservices.dataengine.server.h
[INFO] andlers.DataEngineSchemaTypeHandler.createSchemaAttribute(DataEngineSchemaTypeHandler.java:337)
[INFO] 	at org.odpi.openmetadata.accessservices.dataengine.server.handlers.DataEngineSchemaTypeHandler.upsertSchemaAttributes(DataEngineSchemaTypeHandler.java:276)
[INFO] 	at org.odpi.openmetadata.accessservices.dataengine.server.handlers.DataEngineSchemaTypeHandler.upsertSchemaType(DataEngineSchemaTypeHandler.java:124)
[INFO] 	at org.odpi.openmetadata.accessservices.dataengine.server.service.DataEngineRESTServices.upsertSchemaType(DataEngineRESTServices.java:723)
[INFO] 	at org.odpi.openmetadata.accessservices.dataengine.server.service.DataEngineRESTServices.upsertSchemaType(DataEngineRESTServices.java:152)
[INFO] 	at org.odpi.openmetadata.accessservices.dataengine.server.spring.DataEngineResource.createOrUpdateSchemaType(DataEngineResource.java:80)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
[INFO] 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
[INFO] 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
[INFO] 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893)
[INFO] 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:807)
[INFO] 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
[INFO] 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1061)
[INFO] 	at org.springframework.web.servlet.DispatcherServlet.doService(Dis
[INFO] patcherServlet.java:961)
[INFO] 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
[INFO] 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
[INFO] 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
[INFO] 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
[INFO] 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
[INFO] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
[INFO] 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
[INFO] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
[INFO] 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
[INFO] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
[INFO] 	at org.apache.catalina.core.ApplicationFilterCha
[INFO] in.doFilter(ApplicationFilterChain.java:166)
[INFO] 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
[INFO] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
[INFO] 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
[INFO] 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
[INFO] 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
[INFO] 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
[INFO] 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
[INFO] 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
[INFO] 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
[INFO] 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
[INFO] 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
[INFO] 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:880)
[INFO] 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1601)
[INFO] 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[INFO] 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[INFO] 	at java.lang.Thread.run(Thread.java:748)
[INFO] 
[INFO] Wed Mar 03 09:43:22 GMT 2021 servergraph Exception OMAG-REPOSITORY-HANDLER-0003 An unexpected error org.odpi.openmetadata.repositoryservices.ffdc.exception.ClassificationErrorException was returned to classifyEntity by the metadata server during createSchemaAttribute request for open metadata access service Data Engine OMAS on server servergraph; message was OMRS-REPOSITORY-400-081 A classifyEntity (Detailed) request has been made to repository servergraph to add a classification TypeEmbeddedAttribute to entity f7c1d61b-189e-4bc7-bba4-02303612c15f when this entity is already classified
[INFO] Wed Mar 03 09:43:22 GMT 2021 servergraph Exception OMAG-REPOSITORY-HANDLER-0003 Supplementary information: log record id cdc1a6e2-032b-4605-941d-08df5a41686a org.odpi.openmetadata.repositoryservices.ffdc.exception.ClassificationErrorException returned message of OMRS-REPOSITORY-400-081 A classifyEntity (Detailed) request has been made to repository servergraph to add a classification TypeEmbeddedAttribute to entity f7c1d61b-189e-4bc7-bba4-02303612c15f when this entity is already classified and stacktrace of 
[INFO] OCFCheckedExceptionBase{reportedHTTPCode=400, reportingClassName='org.odpi.openmetadata.repositoryservices.localrepository.repositorycontentmanager.OMRSRepositoryContentHelper', reportingActionDescription='classifyEntity (Detailed)', reportedErrorMessage='OMRS-REPOSITORY-400-081 A classifyEntity (Detailed) request has been made to repository servergraph to add a classification TypeEmbeddedAttribute to entity f7c1d61b-189e-4bc7-bba4-02303612c15f when this entity is already classified', reportedErrorMessageId='OMRS-REPOSITORY-400-081', reportedErrorMessageParameters=[classifyEntity (Detailed), servergraph, TypeEmbeddedAttribute, f7c1d61b-189e-4bc7-bba4-02303612c15f], reportedSystemAction='The system is unable to perform the request as only one classification of a specific type is permitted.', reportedUserAction='Use the updateClassificationProperties to make changed to an existing classification.', reportedCaughtException=null, r
[INFO] eportedCaughtExceptionClassName='null', relatedProperties=null}
[INFO] 	at org.odpi.openmetadata.repositoryservices.localrepository.repositorycontentmanager.OMRSRepositoryContentHelper.checkEntityNotClassifiedEntity(OMRSRepositoryContentHelper.java:1229)
[INFO] 	at org.odpi.openmetadata.repositoryservices.enterprise.repositoryconnector.EnterpriseOMRSMetadataCollection.classifyEntity(EnterpriseOMRSMetadataCollection.java:3176)
[INFO] 	at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryHandler.classifyEntity(RepositoryHandler.java:1674)
[INFO] 	at org.odpi.openmetadata.accessservices.dataengine.server.handlers.DataEngineSchemaTypeHandler.createSchemaAttribute(DataEngineSchemaTypeHandler.java:337)
[INFO] 	at org.odpi.openmetadata.accessservices.dataengine.server.handlers.DataEngineSchemaTypeHandler.upsertSchemaAttributes(DataEngineSchemaTypeHandler.java:276)
[INFO] 	at org.odpi.openmetadata.accessservices.dataengine.server.handlers.DataEngineSchemaTypeHandler.upsertSchemaType(DataEngineSchemaTypeHandler.java:124)
[INFO] 	at org.odpi.openmetadata.accessservices.dataengine.server.service.DataEngineRESTServices.upsertSchemaType(DataEngineRESTServices.java:723)
[INFO] 	at org.odpi.openmetadata.accessservices.dataengine.server.service.DataEngineRESTServices.upsertSchemaType(DataEngineRESTServices.java:152)
[INFO] 	at org.odpi.openmetadata.accessservices.dataengine.server.spring.DataEngineResource.createOrUpdateSchemaType(DataEngineResource.java:80)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
[INFO] 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
[INFO] 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvoc
[INFO] ableHandlerMethod.java:106)
[INFO] 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893)
[INFO] 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:807)
[INFO] 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
[INFO] 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1061)
[INFO] 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:961)
[INFO] 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
[INFO] 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
[INFO] 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
[INFO] 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
[INFO] 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
[INFO] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
[INFO] 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
[INFO] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(
[INFO] OncePerRequestFilter.java:119)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
[INFO] 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
[INFO] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
[INFO] 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
[INFO] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
[INFO] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
[INFO] 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
[INFO] 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
[INFO] 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
[INFO] 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
[INFO] 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
[INFO] 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
[INFO] 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
[INFO] 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
[INFO] 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
[INFO] 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:880)
[INFO] 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1601)
[INFO] 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProce
[INFO] ssorBase.java:49)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[INFO] 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[INFO] 	at java.lang.Thread.run(Thread.java:748)
[INFO] 
[ERROR] Tests run: 4, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 7.558 s <<< FAILURE! - in org.odpi.openmetadata.accessservices.dataengine.fvt.DataEngineFVT
[ERROR] org.odpi.openmetadata.accessservices.dataengine.fvt.DataEngineFVT.verifyLineageMappingsForAJobProcess(String, DataEngineClient, RepositoryService)[1]  Time elapsed: 0.134 s  <<< ERROR!
org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException: OMAG-REPOSITORY-HANDLER-500-001 An unexpected error org.odpi.openmetadata.repositoryservices.ffdc.exception.ClassificationErrorException was returned to classifyEntity by the metadata server during createSchemaAttribute request for open metadata access service Data Engine OMAS on server platform-3; message was OMRS-REPOSITORY-400-081 A classifyEntity (Detailed) request has been made to repository platform-3 to add a classification TypeEmbeddedAttribute to entity d13d2717-164c-4439-b151-b3467af9d0bd when this entity is already classified
	at org.odpi.openmetadata.accessservices.dataengine.fvt.DataEngineFVT.verifyLineageMappingsForAJobProcess(DataEngineFVT.java:90)

[ERROR] org.odpi.openmetadata.accessservices.dataengine.fvt.DataEngineFVT.verifyLineageMappingsForAJobProcess(String, DataEngineClient, RepositoryService)[2]  Time elapsed: 3.017 s  <<< ERROR!
org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException: OMAG-REPOSITORY-HANDLER-500-001 An unexpected error org.odpi.openmetadata.repositoryservices.ffdc.exception.ClassificationErrorException was returned to classifyEntity by the metadata server during createSchemaAttribute request for open metadata access service Data Engine OMAS on server servergraph; message was OMRS-REPOSITORY-400-081 A classifyEntity (Detailed) request has been made to repository servergraph to add a classification TypeEmbeddedAttribute to entity f7c1d61b-189e-4bc7-bba4-02303612c15f when this entity is already classified
	at org.odpi.openmetadata.accessservices.dataengine.fvt.DataEngineFVT.verifyLineageMappingsForAJobProcess(DataEngineFVT.java:90)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   DataEngineFVT.verifyLineageMappingsForAJobProcess:90 » PropertyServer OMAG-REP...
[ERROR]   DataEngineFVT.verifyLineageMappingsForAJobProcess:90 » PropertyServer OMAG-REP...
[INFO] 
[ERROR] Tests run: 4, Failures: 0, Errors: 2, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- process-exec-maven-plugin:0.9:stop-all (stop-all) @ data-engine-fvt ---
[INFO] Stopping all processes ...
[INFO] Stopping process: chassis-start
[INFO] Stopped process: chassis-start
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.6:report (report) @ data-engine-fvt ---
[INFO] Skipping JaCoCo execution due to missing classes directory.
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (verify) @ data-engine-fvt ---

```

The problem looks like it is occuring in the `createSchemaAttribute` method in `DataEngineSchemaTypeHandler` where it is calling the generic handler `schemaAttributeHandler.createNestedSchemaAttribute()` to create a nested schema type.  This method classifies the schema attribute as a `TypeEmbeddedAttribute`, setting up the properties to define the schema type.

When this method returns, the `createSchemaAttribute` then calls `classifyEntity` for the `TypeEmbeddedAttribute` with just the data type property.  Before adding the validation, this action overrode the properties in the classification set up by `schemaAttributeHandler.createNestedSchemaAttribute()`.  Now a `ClassificationErrorException` is returned.

I think the `createSchemaAttribute` method needs to change from:

```
private void createSchemaAttribute(String userId, SchemaType schemaType, String schemaTypeGUID, Attribute attribute,
                                       String dataType, String externalSourceName) throws InvalidParameterException,
            UserNotAuthorizedException,
            PropertyServerException {
        final String methodName = "createSchemaAttribute";
        SchemaAttributeBuilder schemaAttributeBuilder = getSchemaAttributeBuilder(attribute);
        SchemaTypeBuilder schemaTypeBuilder = getSchemaTypeBuilder(schemaType);
        schemaAttributeBuilder.setSchemaType(userId, schemaTypeBuilder, methodName);
        final String schemaTypeGUIDParameterName = "schemaTypeGUID";
        final String qualifiedNameParameterName = "schemaAttribute.getQualifiedName()";

        String externalSourceGUID = dataEngineRegistrationHandler.getExternalDataEngineByQualifiedName(userId, externalSourceName);

        String schemaAttributeGUID = schemaAttributeHandler.createNestedSchemaAttribute(userId, externalSourceGUID,
                externalSourceName, schemaTypeGUID, schemaTypeGUIDParameterName,
                OpenMetadataAPIMapper.TABULAR_SCHEMA_TYPE_TYPE_NAME,
                OpenMetadataAPIMapper.TYPE_TO_ATTRIBUTE_RELATIONSHIP_TYPE_GUID,
                OpenMetadataAPIMapper.TYPE_TO_ATTRIBUTE_RELATIONSHIP_TYPE_NAME,
                attribute.getQualifiedName(), qualifiedNameParameterName, schemaAttributeBuilder, methodName);

        TypeDef classificationTypeDef = repositoryHelper.getTypeDefByName(userId, SchemaTypePropertiesMapper.TYPE_EMBEDDED_ATTRIBUTE_NAME);
        InstanceProperties properties = repositoryHelper.addStringPropertyToInstance(serviceName, null,
                SchemaTypePropertiesMapper.DATA_TYPE, dataType, methodName);

        repositoryHandler.classifyEntity(userId, externalSourceGUID,
                externalSourceName, schemaAttributeGUID, classificationTypeDef.getGUID(), classificationTypeDef.getName(),
                null, null, properties, methodName);

    }
```
to
```
private void createSchemaAttribute(String userId, SchemaType schemaType, String schemaTypeGUID, Attribute attribute,
                                       String dataType, String externalSourceName) throws InvalidParameterException,
            UserNotAuthorizedException,
            PropertyServerException {
        final String methodName = "createSchemaAttribute";
        SchemaAttributeBuilder schemaAttributeBuilder = getSchemaAttributeBuilder(attribute);
        SchemaTypeBuilder schemaTypeBuilder = getSchemaTypeBuilder(schemaType);
        schemaTypeBuilder.setDataType(dataType);
        schemaAttributeBuilder.setSchemaType(userId, schemaTypeBuilder, methodName);
        final String schemaTypeGUIDParameterName = "schemaTypeGUID";
        final String qualifiedNameParameterName = "schemaAttribute.getQualifiedName()";

        String externalSourceGUID = dataEngineRegistrationHandler.getExternalDataEngineByQualifiedName(userId, externalSourceName);

        schemaAttributeHandler.createNestedSchemaAttribute(userId, externalSourceGUID,
                externalSourceName, schemaTypeGUID, schemaTypeGUIDParameterName,
                OpenMetadataAPIMapper.TABULAR_SCHEMA_TYPE_TYPE_NAME,
                OpenMetadataAPIMapper.TYPE_TO_ATTRIBUTE_RELATIONSHIP_TYPE_GUID,
                OpenMetadataAPIMapper.TYPE_TO_ATTRIBUTE_RELATIONSHIP_TYPE_NAME,
                attribute.getQualifiedName(), qualifiedNameParameterName, schemaAttributeBuilder, methodName);
    }
```

**Comment by mandy-chessell** [comment]
It was also necessary to remove this code from the unit test case `updateSchemaTypeWithSchemaAttribute`

```

        TypeDef classificationTypeDef = repositoryHelper.getTypeDefByName(USER, SchemaTypePropertiesMapper.TYPE_EMBEDDED_ATTRIBUTE_NAME);
        InstanceProperties properties = repositoryHelper.addStringPropertyToInstance("sourceName", null,
                SchemaTypePropertiesMapper.DATA_TYPE, attribute.getDataType(), methodName);

        verify(repositoryHandler, times(1)).classifyEntity(USER, EXTERNAL_SOURCE_DE_GUID,
                EXTERNAL_SOURCE_DE_QUALIFIED_NAME, ATTRIBUTE_GUID, classificationTypeDef.getGUID(), classificationTypeDef.getName(),
                null, null, properties, "createSchemaAttribute");

```
