### ISSUE TITLE
Gradle: Subject Area FVT fails

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4903]
In #4098 the gradle build is being extended to run FVTs. Other FVTs in the test suite are running, but I see an odd area with Subject Area FVT that requires further investigation.

I suspect it is a classpath issue - need to review code and debug, so opening up this issue to investigate later & to allow the other tests to be checked in (currently gradle does not run FVTs)

**Once fixed this test should be reenabled in gradle**

The failure is seen when using the groovy script to initialize subject area OMAS:
```
=== Checking platform at https://localhost:10448 is available (12 attempts remaining) ===
200
Egeria OMAG Server Platform (version 2.8-SNAPSHOT)

=== Configuring server: serverinmem ===
200
{"class":"VoidResponse","relatedHTTPCode":200}
=== Enabling Subject Area OMAS: serverinmem ===
200
{"class":"VoidResponse","relatedHTTPCode":200}
=== Starting server: serverinmem ===
200
{"class":"SuccessMessageResponse","relatedHTTPCode":500,"exceptionClassName":"org.odpi.openmetadata.adminservices.ffdc.exception.OMAGConfigurationErrorException","exceptionCausedBy":"java.lang.IllegalStateException","actionDescription":"initialize","exceptionErrorMessage":"OMAG-ADMIN-500-004 The Subject Area OMAS service detected an unexpected java.lang.IllegalStateException exception with message zip file closed during initialization","exceptionErrorMessageId":"OMAG-ADMIN-500-004","exceptionErrorMessageParameters":["Subject Area OMAS","java.lang.IllegalStateException","zip file closed"],"exceptionSystemAction":"The system is unable to start the service in the OMAG server.","exceptionUserAction":"This is likely to be either an operational or logic error. Look for other errors in the audit log.  Validate the request.  If you are stuck, raise an issue."}
```
```
Fri Mar 12 09:36:50 GMT 2021 servergraph Startup OMAS-SUBJECT_AREA-0001 The Subject Area Open Metadata Access Service (OMAS) is initializing a new server instance
Fri Mar 12 09:36:50 GMT 2021 servergraph Exception OMAS-SUBJECT_AREA-0005 The Subject Area Open Metadata Access Service (OMAS) is unable to initialize a new instance in server java.lang.IllegalStateException; the zip file closed exception occurred with error message: {2}
Fri Mar 12 09:36:50 GMT 2021 servergraph Exception OMAS-SUBJECT_AREA-0005 Supplementary information: log record id 15c59bba-0c49-426f-9cd1-be8ef287afda java.lang.IllegalStateException returned message of zip file closed and stacktrace of
java.lang.IllegalStateException: zip file closed
	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:823)
	at java.base/java.util.zip.ZipFile.jarStream(ZipFile.java:618)
	at java.base/java.util.zip.ZipFile$1.stream(ZipFile.java:1088)
	at java.base/java.util.jar.JarFile.stream(JarFile.java:535)
	at org.reflections.vfs.ZipDir.lambda$getFiles$2(ZipDir.java:21)
	at org.reflections.Reflections.scan(Reflections.java:260)
	at org.reflections.Reflections.scan(Reflections.java:216)
	at org.reflections.Reflections.<init>(Reflections.java:137)
	at org.reflections.Reflections.<init>(Reflections.java:182)
	at org.odpi.openmetadata.accessservices.subjectarea.server.mappers.MappersFactory.<init>(MappersFactory.java:27)
	at org.odpi.openmetadata.accessservices.subjectarea.server.mappers.MappersFactory.<init>(MappersFactory.java:54)
	at org.odpi.openmetadata.accessservices.subjectarea.handlers.SubjectAreaHandler.<init>(SubjectAreaHandler.java:72)
```

**Comment by planetf1** [comment]
Having checked the current build.gradle & output from build, the Subject Area FVT is running ok, and is enabled by default....

Closing
