### ISSUE TITLE
EntityProxyOnlyException in Governance Engine OMAS's Topic Listener

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#5081]
When you run the open metadata labs, you may notice an occasional exception from cocoMDSx relating to entity proxies.
For example, this one occurs when you run the "Building a Data Catalog" lab.

```
Mon Apr 26 09:26:53 BST 2021 cocoMDSx Event OMRS-AUDIT-8006 Processing incoming event of type RefreshRelationshipRequestEvent for instance 194200ed-3acf-417b-8eff-3c0b4a1ddb1c from: OMRSEventOriginator{metadataCollectionId='5817f177-a593-4a74-b3c7-a5275ce64442', serverName='cocoMDS2', serverType='Metadata Server', organizationName='Coco Pharmaceuticals'}
Mon Apr 26 09:26:53 BST 2021 cocoMDSx Information OMRS-AUDIT-8008 Retrying retrieve of an entity 259f0db9-b42c-42e1-a686-0e25651b8d72 for user cocoMDSxnpa because only a proxy is available - attempt 1
Mon Apr 26 09:26:53 BST 2021 cocoMDSx Information OMRS-AUDIT-8008 Retrying retrieve of an entity 259f0db9-b42c-42e1-a686-0e25651b8d72 for user cocoMDSxnpa because only a proxy is available - attempt 2
Mon Apr 26 09:26:53 BST 2021 cocoMDSx Information OMRS-AUDIT-8008 Retrying retrieve of an entity 259f0db9-b42c-42e1-a686-0e25651b8d72 for user cocoMDSxnpa because only a proxy is available - attempt 3
Mon Apr 26 09:26:53 BST 2021 cocoMDSx Information OMRS-AUDIT-8008 Retrying retrieve of an entity 259f0db9-b42c-42e1-a686-0e25651b8d72 for user cocoMDSxnpa because only a proxy is available - attempt 4
Mon Apr 26 09:26:53 BST 2021 cocoMDSx Exception OMAS-GOVERNANCE-ENGINE-0007 The Governance Engine Open Metadata Access Service (OMAS) encounter an exception while processing event from Governance Engine OMAS of type processNewEntityEvent for instance ce383809-6b90-48e8-83a0-1f48e463ba3a
Mon Apr 26 09:26:53 BST 2021 cocoMDSx Exception OMAS-GOVERNANCE-ENGINE-0007 Supplementary information: log record id 0e93c046-8258-4634-8feb-946549c2b49c org.odpi.openmetadata.frameworks.connectors.ffdc.InvalidParameterException returned message of OMAG-REPOSITORY-HANDLER-404-005 Only an entity proxy for requested Referenceable object with unique identifier (guid) 259f0db9-b42c-42e1-a686-0e25651b8d72 is found in the open metadata server cocoMDSx, error message was: OMRS-REPOSITORY-400-051 A request for entity 259f0db9-b42c-42e1-a686-0e25651b8d72 has been passed to repository cocoMDSx as the guid parameter of the getEntityDetail operation but only an entity proxy has been found and stacktrace of 
InvalidParameterException{parameterName='anchorGUID', reportedHTTPCode=404, reportingClassName='org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryErrorHandler', reportingActionDescription='processNewEntityEvent', reportedErrorMessage='OMAG-REPOSITORY-HANDLER-404-005 Only an entity proxy for requested Referenceable object with unique identifier (guid) 259f0db9-b42c-42e1-a686-0e25651b8d72 is found in the open metadata server cocoMDSx, error message was: OMRS-REPOSITORY-400-051 A request for entity 259f0db9-b42c-42e1-a686-0e25651b8d72 has been passed to repository cocoMDSx as the guid parameter of the getEntityDetail operation but only an entity proxy has been found', reportedErrorMessageId='OMAG-REPOSITORY-HANDLER-404-005', reportedErrorMessageParameters=[Referenceable, 259f0db9-b42c-42e1-a686-0e25651b8d72, cocoMDSx, OMRS-REPOSITORY-400-051 A request for entity 259f0db9-b42c-42e1-a686-0e25651b8d72 has been passed to repository cocoMDSx as the guid parameter of the getEntityDetail operation but only an entity proxy has been found], reportedSystemAction='The system is unable to populate the requested connection object.', reportedUserAction='Check that the connection name and the OMAS Server URL are correct.  Retry the request when the connection is available in the OMAS Service', reportedCaughtException=OCFCheckedExceptionBase{reportedHTTPCode=400, reportingClassName='org.odpi.openmetadata.adapters.repositoryservices.inmemory.repositoryconnector.InMemoryOMRSMetadataCollection', reportingActionDescription='getEntityDetail', reportedErrorMessage='OMRS-REPOSITORY-400-051 A request for entity 259f0db9-b42c-42e1-a686-0e25651b8d72 has been passed to repository cocoMDSx as the guid parameter of the getEntityDetail operation but only an entity proxy has been found', reportedErrorMessageId='OMRS-REPOSITORY-400-051', reportedErrorMessageParameters=[259f0db9-b42c-42e1-a686-0e25651b8d72, cocoMDSx, guid, getEntityDetail], reportedSystemAction='The system is unable to return all of the details of the entity.  It can only supply an entity summary.', reportedUserAction='The fact that the system has a proxy means that the entity exists in one of the members of the connected cohorts.  The repository where it is located may be unavailable, or the entity has been deleted but the delete request has not propagated through to this repository.', reportedCaughtException=null, reportedCaughtExceptionClassName='null', relatedProperties=null}, reportedCaughtExceptionClassName='org.odpi.openmetadata.repositoryservices.ffdc.exception.EntityProxyOnlyException', relatedProperties=null}
	at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryErrorHandler.handleEntityProxy(RepositoryErrorHandler.java:636)
	at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryHandler.getEntityByGUID(RepositoryHandler.java:3189)
	at org.odpi.openmetadata.commonservices.generichandlers.OpenMetadataAPIGenericHandler.validateAnchorEntity(OpenMetadataAPIGenericHandler.java:2972)
	at org.odpi.openmetadata.commonservices.generichandlers.OpenMetadataAPIGenericHandler.getEntityFromRepository(OpenMetadataAPIGenericHandler.java:7242)
	at org.odpi.openmetadata.commonservices.generichandlers.OpenMetadataAPIGenericHandler.getEntityFromRepository(OpenMetadataAPIGenericHandler.java:7189)
	at org.odpi.openmetadata.commonservices.generichandlers.OpenMetadataAPIGenericHandler.getBeanFromRepository(OpenMetadataAPIGenericHandler.java:7357)
	at org.odpi.openmetadata.commonservices.generichandlers.OpenMetadataAPIGenericHandler.getBeanFromRepository(OpenMetadataAPIGenericHandler.java:7321)
	at org.odpi.openmetadata.accessservices.governanceengine.handlers.MetadataElementHandler.getMetadataElementByGUID(MetadataElementHandler.java:119)
	at org.odpi.openmetadata.accessservices.governanceengine.outtopic.GovernanceEngineOMRSTopicListener.processWatchdogEvent(GovernanceEngineOMRSTopicListener.java:611)
	at org.odpi.openmetadata.accessservices.governanceengine.outtopic.GovernanceEngineOMRSTopicListener.processNewEntityEvent(GovernanceEngineOMRSTopicListener.java:742)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicListenerBase.processInstanceEvent(OMRSTopicListenerBase.java:484)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicListenerWrapper.processInstanceEvent(OMRSTopicListenerWrapper.java:146)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.processOMRSEvent(OMRSTopicConnector.java:518)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.lambda$processEvent$0(OMRSTopicConnector.java:455)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: OCFCheckedExceptionBase{reportedHTTPCode=400, reportingClassName='org.odpi.openmetadata.adapters.repositoryservices.inmemory.repositoryconnector.InMemoryOMRSMetadataCollection', reportingActionDescription='getEntityDetail', reportedErrorMessage='OMRS-REPOSITORY-400-051 A request for entity 259f0db9-b42c-42e1-a686-0e25651b8d72 has been passed to repository cocoMDSx as the guid parameter of the getEntityDetail operation but only an entity proxy has been found', reportedErrorMessageId='OMRS-REPOSITORY-400-051', reportedErrorMessageParameters=[259f0db9-b42c-42e1-a686-0e25651b8d72, cocoMDSx, guid, getEntityDetail], reportedSystemAction='The system is unable to return all of the details of the entity.  It can only supply an entity summary.', reportedUserAction='The fact that the system has a proxy means that the entity exists in one of the members of the connected cohorts.  The repository where it is located may be unavailable, or the entity has been deleted but the delete request has not propagated through to this repository.', reportedCaughtException=null, reportedCaughtExceptionClassName='null', relatedProperties=null}
	at org.odpi.openmetadata.repositoryservices.connectors.stores.metadatacollectionstore.OMRSMetadataCollectionBase.reportEntityProxyOnly(OMRSMetadataCollectionBase.java:6956)
	at org.odpi.openmetadata.adapters.repositoryservices.inmemory.repositoryconnector.InMemoryOMRSMetadataCollection.getEntityDetail(InMemoryOMRSMetadataCollection.java:173)
	at org.odpi.openmetadata.repositoryservices.localrepository.repositoryconnector.LocalOMRSMetadataCollection.getEntityDetail(LocalOMRSMetadataCollection.java:1827)
	at org.odpi.openmetadata.repositoryservices.enterprise.repositoryconnector.executors.GetEntityExecutor.issueRequestToRepository(GetEntityExecutor.java:104)
	at org.odpi.openmetadata.repositoryservices.enterprise.repositoryconnector.control.SequentialFederationControl.executeCommand(SequentialFederationControl.java:53)
	at org.odpi.openmetadata.repositoryservices.enterprise.repositoryconnector.EnterpriseOMRSMetadataCollection.getEntityDetail(EnterpriseOMRSMetadataCollection.java:1024)
	at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryHandler.getEntityByGUID(RepositoryHandler.java:3177)
	... 21 more
```

The software is behaving correctly but the resulting error messages are alarming.  This is what is happening:

* The cocoMDSx service is receiving notification about a relationship that has been created in cocoMDS2.
* The Governance Action OMAS has an OMRS Topic listener registered and is told about the event.
* The topic listener tries to process it by building an event to send to any listening Engine Hosts, but it can not retrieve one of the entities that the relationship is linked to.  This is because this entity is mastered in cocoMDS1 and so not visible to cocoMDSx because they are in different cohorts.

The topic listener is currently logging all exceptions.  This issue suggests a change to detect this case and log a message specific to this case rather than the generic exception logging.

**Comment by mandy-chessell** [comment]
This one is fixed...
