### ISSUE TITLE
Error in Security Officer OMAS topic listener

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#5191]
The follow exceptions are occuring in the Security Officer OMAS - whilst processing events relating to newly created relational databases

```
Thu May 13 16:10:04 BST 2021 postgresTargetServer Exception OMAG-REPOSITORY-HANDLER-0003 An unexpected error org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException was returned to getEntityForRelationshipType by the metadata server during getRelationalTable request for open metadata access service Security Officer OMAS on server postgresTargetServer; message was OMAG-REPOSITORY-HANDLER-404-006 Multiple NestedSchemaAttribute relationships are connected to the RelationalColumn entity with unique identifier b400c642-8ccb-47e8-92ce-855e49dad9d3: the relationship identifiers are [94d4866d-62db-4633-82b0-cf143efafa14, 90c4c38e-2936-45bd-9f33-9fb8c0d2ae79, e67a5bbb-8715-414a-babf-e14359fc7708, 9584d727-c9e4-4980-b590-fc86d9bf66cd, 18e09e7e-2722-4411-9a1c-d93055a1a088, e9cc718f-d779-452b-a826-6d7f043a807f, 640c9646-7d8d-4738-b914-6db7efa2d21a, 1fc15f0f-f52b-4b0d-ae9b-692776647019, 6888e128-03d4-4f1a-ae64-270774089ba6]; the calling method is getRelationalTable and the server is postgresTargetServer
Thu May 13 16:10:04 BST 2021 postgresTargetServer Exception OMAG-REPOSITORY-HANDLER-0003 Supplementary information: log record id 82c54423-0486-47ab-bacd-1680f8d50b2e org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException returned message of OMAG-REPOSITORY-HANDLER-404-006 Multiple NestedSchemaAttribute relationships are connected to the RelationalColumn entity with unique identifier b400c642-8ccb-47e8-92ce-855e49dad9d3: the relationship identifiers are [94d4866d-62db-4633-82b0-cf143efafa14, 90c4c38e-2936-45bd-9f33-9fb8c0d2ae79, e67a5bbb-8715-414a-babf-e14359fc7708, 9584d727-c9e4-4980-b590-fc86d9bf66cd, 18e09e7e-2722-4411-9a1c-d93055a1a088, e9cc718f-d779-452b-a826-6d7f043a807f, 640c9646-7d8d-4738-b914-6db7efa2d21a, 1fc15f0f-f52b-4b0d-ae9b-692776647019, 6888e128-03d4-4f1a-ae64-270774089ba6]; the calling method is getRelationalTable and the server is postgresTargetServer and stacktrace of 
PropertyServerException{reportedHTTPCode=404, reportingClassName='org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryErrorHandler', reportingActionDescription='getRelationalTable', reportedErrorMessage='OMAG-REPOSITORY-HANDLER-404-006 Multiple NestedSchemaAttribute relationships are connected to the RelationalColumn entity with unique identifier b400c642-8ccb-47e8-92ce-855e49dad9d3: the relationship identifiers are [94d4866d-62db-4633-82b0-cf143efafa14, 90c4c38e-2936-45bd-9f33-9fb8c0d2ae79, e67a5bbb-8715-414a-babf-e14359fc7708, 9584d727-c9e4-4980-b590-fc86d9bf66cd, 18e09e7e-2722-4411-9a1c-d93055a1a088, e9cc718f-d779-452b-a826-6d7f043a807f, 640c9646-7d8d-4738-b914-6db7efa2d21a, 1fc15f0f-f52b-4b0d-ae9b-692776647019, 6888e128-03d4-4f1a-ae64-270774089ba6]; the calling method is getRelationalTable and the server is postgresTargetServer', reportedErrorMessageId='OMAG-REPOSITORY-HANDLER-404-006', reportedErrorMessageParameters=[NestedSchemaAttribute, RelationalColumn, b400c642-8ccb-47e8-92ce-855e49dad9d3, [94d4866d-62db-4633-82b0-cf143efafa14, 90c4c38e-2936-45bd-9f33-9fb8c0d2ae79, e67a5bbb-8715-414a-babf-e14359fc7708, 9584d727-c9e4-4980-b590-fc86d9bf66cd, 18e09e7e-2722-4411-9a1c-d93055a1a088, e9cc718f-d779-452b-a826-6d7f043a807f, 640c9646-7d8d-4738-b914-6db7efa2d21a, 1fc15f0f-f52b-4b0d-ae9b-692776647019, 6888e128-03d4-4f1a-ae64-270774089ba6], getRelationalTable, postgresTargetServer], reportedSystemAction='The system is unable to process a request because multiple relationships have been discovered and it is unsure which relationship to follow.', reportedUserAction='Investigate why multiple relationships exist.  Then retry the request once the issue is resolved.', reportedCaughtException=null, reportedCaughtExceptionClassName='null', relatedProperties=null}
	at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryErrorHandler.handleAmbiguousRelationships(RepositoryErrorHandler.java:679)
	at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryHandler.getEntityForRelationshipType(RepositoryHandler.java:3128)
	at org.odpi.openmetadata.accessservices.securityofficer.server.processors.GovernedAssetContextBuilder.getRelationalTable(GovernedAssetContextBuilder.java:71)
	at org.odpi.openmetadata.accessservices.securityofficer.server.processors.GovernedAssetContextBuilder.getTableName(GovernedAssetContextBuilder.java:60)
	at org.odpi.openmetadata.accessservices.securityofficer.server.processors.GovernedAssetContextBuilder.buildContextForTable(GovernedAssetContextBuilder.java:39)
	at org.odpi.openmetadata.accessservices.securityofficer.server.handler.GovernedAssetHandler.buildContext(GovernedAssetHandler.java:243)
	at org.odpi.openmetadata.accessservices.securityofficer.server.handler.GovernedAssetHandler.convertGovernedAsset(GovernedAssetHandler.java:180)
	at org.odpi.openmetadata.accessservices.securityofficer.server.listener.SecurityOfficerOMRSTopicListener.getGovernanceEngineEvent(SecurityOfficerOMRSTopicListener.java:196)
	at org.odpi.openmetadata.accessservices.securityofficer.server.listener.SecurityOfficerOMRSTopicListener.processReclassifiedEntityEvent(SecurityOfficerOMRSTopicListener.java:131)
	at org.odpi.openmetadata.accessservices.securityofficer.server.listener.SecurityOfficerOMRSTopicListener.processInstanceEvent(SecurityOfficerOMRSTopicListener.java:83)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicListenerWrapper.processInstanceEvent(OMRSTopicListenerWrapper.java:146)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.processOMRSEvent(OMRSTopicConnector.java:518)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.lambda$processEvent$0(OMRSTopicConnector.java:455)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

Thu May 13 16:10:04 BST 2021 postgresTargetServer Exception OMAS-SECURITY-OFFICER-0010 The Security Officer Open Metadata Access Service (OMAS) encounter an exception while processing event of type ReclassifiedEntityEvent
Thu May 13 16:10:04 BST 2021 postgresTargetServer Exception OMAS-SECURITY-OFFICER-0010 Supplementary information: log record id b0770977-a00a-4adf-88cd-2807072138d2 org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException returned message of OMAG-REPOSITORY-HANDLER-500-001 An unexpected error org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException was returned to getEntityForRelationshipType by the metadata server during getRelationalTable request for open metadata access service Security Officer OMAS on server postgresTargetServer; message was OMAG-REPOSITORY-HANDLER-404-006 Multiple NestedSchemaAttribute relationships are connected to the RelationalColumn entity with unique identifier b400c642-8ccb-47e8-92ce-855e49dad9d3: the relationship identifiers are [94d4866d-62db-4633-82b0-cf143efafa14, 90c4c38e-2936-45bd-9f33-9fb8c0d2ae79, e67a5bbb-8715-414a-babf-e14359fc7708, 9584d727-c9e4-4980-b590-fc86d9bf66cd, 18e09e7e-2722-4411-9a1c-d93055a1a088, e9cc718f-d779-452b-a826-6d7f043a807f, 640c9646-7d8d-4738-b914-6db7efa2d21a, 1fc15f0f-f52b-4b0d-ae9b-692776647019, 6888e128-03d4-4f1a-ae64-270774089ba6]; the calling method is getRelationalTable and the server is postgresTargetServer and stacktrace of 
PropertyServerException{reportedHTTPCode=500, reportingClassName='org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryErrorHandler', reportingActionDescription='getRelationalTable', reportedErrorMessage='OMAG-REPOSITORY-HANDLER-500-001 An unexpected error org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException was returned to getEntityForRelationshipType by the metadata server during getRelationalTable request for open metadata access service Security Officer OMAS on server postgresTargetServer; message was OMAG-REPOSITORY-HANDLER-404-006 Multiple NestedSchemaAttribute relationships are connected to the RelationalColumn entity with unique identifier b400c642-8ccb-47e8-92ce-855e49dad9d3: the relationship identifiers are [94d4866d-62db-4633-82b0-cf143efafa14, 90c4c38e-2936-45bd-9f33-9fb8c0d2ae79, e67a5bbb-8715-414a-babf-e14359fc7708, 9584d727-c9e4-4980-b590-fc86d9bf66cd, 18e09e7e-2722-4411-9a1c-d93055a1a088, e9cc718f-d779-452b-a826-6d7f043a807f, 640c9646-7d8d-4738-b914-6db7efa2d21a, 1fc15f0f-f52b-4b0d-ae9b-692776647019, 6888e128-03d4-4f1a-ae64-270774089ba6]; the calling method is getRelationalTable and the server is postgresTargetServer', reportedErrorMessageId='OMAG-REPOSITORY-HANDLER-500-001', reportedErrorMessageParameters=[OMAG-REPOSITORY-HANDLER-404-006 Multiple NestedSchemaAttribute relationships are connected to the RelationalColumn entity with unique identifier b400c642-8ccb-47e8-92ce-855e49dad9d3: the relationship identifiers are [94d4866d-62db-4633-82b0-cf143efafa14, 90c4c38e-2936-45bd-9f33-9fb8c0d2ae79, e67a5bbb-8715-414a-babf-e14359fc7708, 9584d727-c9e4-4980-b590-fc86d9bf66cd, 18e09e7e-2722-4411-9a1c-d93055a1a088, e9cc718f-d779-452b-a826-6d7f043a807f, 640c9646-7d8d-4738-b914-6db7efa2d21a, 1fc15f0f-f52b-4b0d-ae9b-692776647019, 6888e128-03d4-4f1a-ae64-270774089ba6]; the calling method is getRelationalTable and the server is postgresTargetServer, getRelationalTable, Security Officer OMAS, postgresTargetServer, org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException, getEntityForRelationshipType], reportedSystemAction='The system is unable to process the request because of an internal error.', reportedUserAction='Verify the sanity of the server.  This is probably a logic error.  If you can not work out what happened, ask the Egeria community for help.', reportedCaughtException=null, reportedCaughtExceptionClassName='null', relatedProperties=null}
	at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryErrorHandler.handleRepositoryError(RepositoryErrorHandler.java:537)
	at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryHandler.getEntityForRelationshipType(RepositoryHandler.java:3142)
	at org.odpi.openmetadata.accessservices.securityofficer.server.processors.GovernedAssetContextBuilder.getRelationalTable(GovernedAssetContextBuilder.java:71)
	at org.odpi.openmetadata.accessservices.securityofficer.server.processors.GovernedAssetContextBuilder.getTableName(GovernedAssetContextBuilder.java:60)
	at org.odpi.openmetadata.accessservices.securityofficer.server.processors.GovernedAssetContextBuilder.buildContextForTable(GovernedAssetContextBuilder.java:39)
	at org.odpi.openmetadata.accessservices.securityofficer.server.handler.GovernedAssetHandler.buildContext(GovernedAssetHandler.java:243)
	at org.odpi.openmetadata.accessservices.securityofficer.server.handler.GovernedAssetHandler.convertGovernedAsset(GovernedAssetHandler.java:180)
	at org.odpi.openmetadata.accessservices.securityofficer.server.listener.SecurityOfficerOMRSTopicListener.getGovernanceEngineEvent(SecurityOfficerOMRSTopicListener.java:196)
	at org.odpi.openmetadata.accessservices.securityofficer.server.listener.SecurityOfficerOMRSTopicListener.processReclassifiedEntityEvent(SecurityOfficerOMRSTopicListener.java:131)
	at org.odpi.openmetadata.accessservices.securityofficer.server.listener.SecurityOfficerOMRSTopicListener.processInstanceEvent(SecurityOfficerOMRSTopicListener.java:83)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicListenerWrapper.processInstanceEvent(OMRSTopicListenerWrapper.java:146)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.processOMRSEvent(OMRSTopicConnector.java:518)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.lambda$processEvent$0(OMRSTopicConnector.java:455)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


```
The error suggests that the database metadata (created by Data Manager OMAS) has the relational column either with multiple nested elements - or connected to multiple tables.   Looks fishy

**Comment by mandy-chessell** [comment]
I am leaving this open so I can check the status of the code
