### ISSUE TITLE
CohortTopicConnector is not able to gracefully shut down when the Kafka connection initially failed

### ISSUE THREAD

**Issue by christinesjx** [odpi/egeria#5229]
`CohortTopicConnector` should be able to gracefully shut down when the Kafka connection initially failed. Right now, it is giving a `NullPointerException`

### Initialize cohortTopicConnector
In Egeria2.4:
The logic of OMRSCohortManager.initialize() is:
```java
        try {
            ....
            cohortTopicConnector.registerListener(cohortEventListener, cohortName);
            cohortTopicConnector.start();
            this.cohortTopicConnector = cohortTopicConnector;
            this.cohortEventListener = cohortEventListener;
        catch (Throwable  error){}
```
If kafka connection fails to initialize, cohortTopicConnector.start() would go straight to catch block without calling this.cohortTopicConnector = cohortTopicConnector; In this case, we have a null cohortTopicConnector.

In Egeria 2.8:
The logic of OMRSCohortManager.initialize() changes to:
```java
        try {
            ....
            this.cohortTopicConnector = cohortTopicConnector;
            this.cohortEventListener = cohortEventListener;
        catch (Throwable  error){}
```
The first two lines move to `OMRSCohortManager.setSecurityVerifier()` method, and this method will only be executed in `OMRSMetadataHighwayManager.setSecurityVerifier()` when cohortManager != null, after OMRSCohortManager is already initialized.
```java
    public void setSecurityVerifier(OpenMetadataEventsSecurity securityVerifier){
        if (cohortTopicConnector != null)
                cohortTopicConnector.registerListener(cohortEventListener, cohortName);
                cohortTopicConnector.start();
   }
```
Even though Kafka connection fails to initialize, we still get a not null cohortTopicConnector here.

### When shutting down cohortTopicConnector
```java
            if (cohortTopicConnector != null) {
                cohortTopicConnector.disconnect();  
            }
```
In Egeria 2.4, since we have a `cohortTopicConnector=null`; `cohortTopicConnector.disconnect()` won't be excuted.
However, In Egeria 2.8, even though Kafka connection fails to initialize, we still have a not null cohortTopicConnector. cohortTopicConnector.disconnect() will be executed and `consumer.safeCloseConsumer()` will throw an NPE. 

Wrapping consumer.disconnect() and producer.disconnection() with a try catch block in `KafkaOpenMetadataTopicConnector.disconnect()` can fix it.

**Comment by jnhagelberg** [comment]
Here's the stack trace from our test that reproduced the issue:
```
java.lang.NullPointerException
	at com.ibm.catalog.openmetadata.adapters.eventmapper.WKCOMRSRepositoryEventMapper.start(WKCOMRSRepositoryEventMapper.java:311)
	at org.odpi.openmetadata.repositoryservices.localrepository.repositoryconnector.LocalOMRSRepositoryConnector.start(LocalOMRSRepositoryConnector.java:160)
	at org.odpi.openmetadata.repositoryservices.admin.OMRSOperationalServices.initializeCohortMember(OMRSOperationalServices.java:409)
	at org.odpi.openmetadata.adminservices.OMAGServerOperationalServices.activateWithSuppliedConfig(OMAGServerOperationalServices.java:314)
	at org.odpi.openmetadata.adminservices.OMAGServerOperationalServices.activateWithStoredConfig(OMAGServerOperationalServices.java:148)
	at com.ibm.catalog.unified.controllers.OMRSAdminController.activateOMAGServer(OMRSAdminController.java:1067)
	at com.ibm.catalog.unified.controllers.OMRSAdminControllerTest.testDeleteLastCohort(OMRSAdminControllerTest.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:768)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
java.lang.NullPointerException
	at com.ibm.catalog.openmetadata.adapters.eventmapper.WKCOMRSRepositoryEventMapper.start(WKCOMRSRepositoryEventMapper.java:311)
	at org.odpi.openmetadata.repositoryservices.localrepository.repositoryconnector.LocalOMRSRepositoryConnector.start(LocalOMRSRepositoryConnector.java:160)
	at org.odpi.openmetadata.repositoryservices.admin.OMRSOperationalServices.initializeCohortMember(OMRSOperationalServices.java:409)
	at org.odpi.openmetadata.adminservices.OMAGServerOperationalServices.activateWithSuppliedConfig(OMAGServerOperationalServices.java:314)
	at org.odpi.openmetadata.adminservices.OMAGServerOperationalServices.activateWithStoredConfig(OMAGServerOperationalServices.java:148)
	at com.ibm.catalog.unified.controllers.OMRSAdminController.activateOMAGServer(OMRSAdminController.java:1067)
	at com.ibm.catalog.unified.controllers.OMRSAdminControllerTest.testDeleteLastCohort(OMRSAdminControllerTest.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:768)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
	```

**Comment by jnhagelberg** [comment]
Here is the stack trace we saw in our test that reproduces the issue:
```
java.lang.NullPointerException
	at org.odpi.openmetadata.adapters.eventbus.topic.kafka.KafkaOpenMetadataTopicConnector.disconnect(KafkaOpenMetadataTopicConnector.java:338)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.disconnect(OMRSTopicConnector.java:565)
	at org.odpi.openmetadata.repositoryservices.metadatahighway.OMRSCohortManager.disconnect(OMRSCohortManager.java:403)
	at org.odpi.openmetadata.repositoryservices.metadatahighway.OMRSMetadataHighwayManager.disconnect(OMRSMetadataHighwayManager.java:438)
	at org.odpi.openmetadata.repositoryservices.admin.OMRSOperationalServices.disconnect(OMRSOperationalServices.java:889)
	at org.odpi.openmetadata.adminservices.OMAGServerOperationalServices.deactivateRunningServiceInstances(OMAGServerOperationalServices.java:1246)
	at org.odpi.openmetadata.adminservices.OMAGServerOperationalServices.deactivatePermanently(OMAGServerOperationalServices.java:1380)
	at com.ibm.catalog.unified.controllers.OMRSAdminController.deleteOMRS(OMRSAdminController.java:1161)
	at com.ibm.catalog.unified.controllers.OMRSAdminController.deleteOMRS(OMRSAdminController.java:1144)
	at com.ibm.catalog.unified.controllers.OMRSAdminController.deleteCohort(OMRSAdminController.java:1101)
	at com.ibm.catalog.unified.controllers.OMRSAdminControllerTest.testDeleteLastCohort(OMRSAdminControllerTest.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:768)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

The issue is that in `org.odpi.openmetadata.adapters.eventbus.topic.kafka.KafkaOpenMetadataTopicConnector.disconnect.disconnect(...)`, `consumer` is null if the kafka connection fails.

**Comment by planetf1** [comment]
@christinesjx thanks for identifying/fixing -- @mandy-chessell @wbittles This looks like a valuable fix to get in

**Comment by wbittles** [comment]
If whether the variable cohortTopicConnector being null is going to be used as flag to indicate initialisation status  , then it important  that it's not left in an undefined state, so I'd advise only changing  what that variable contains only when we know that it's valid to do so. i.e we should move the initialisation of this variable to as it was in Egeria 2.4

**Comment by planetf1** [comment]
The code is complex and has been subject to change (both in terms of consumers and implementation) & indeed still is. 

Recently changes have been made to improve the resiliance of the connector if the thread dies, and also change the cohort topic from one to three. The design in the Cohort Manager is the same as 2.8 -- we may have a cohortSingleTopicConnector, but that doesn't mean the kafka connection has started. The intend of the code subsequently calling disconnect() in my view is providing an intent that we want things cleaned up (it's really a disconnect on the connector object -- not kafka), but the caller doesn't have that knowledge of whether kafka connection is started or not, nor need it.  Therefore it makes sense to me that the code in the connector should either check state before doing the cleanup, or handle the effect of not being connected.

In addition, Whilst I'd like to thoroughly go through every possible interaction I think taking a defensive coding approach in the way suggested makes sense. There is always a risk of obfustacting a design issue by masking any NPEs but I think here we are right down doing cleanup and that's an acceptable risk.

As such I propose this change.

**Comment by planetf1** [comment]
See https://github.com/odpi/egeria/pull/5680

**Comment by planetf1** [comment]
I went to test the above fix, and it seems as if currently there is an exception in start() even before we get to shutdown:

```
Fri Sep 10 13:56:52 BST 2021 cocoMDS2 Startup OCF-KAFKA-TOPIC-CONNECTOR-0015 The local server is attempting to connect to Kafka, attempt 10
Fri Sep 10 13:57:52 BST 2021 cocoMDS2 Error OCF-KAFKA-TOPIC-CONNECTOR-0014  Connecting to bootstrap Apache Kafka Broker egeria.omag.openmetadata.repositoryservices.cohort.cocoCohort.OMRSTopic.registration
Fri Sep 10 13:57:52 BST 2021 cocoMDS2 Exception OMRS-AUDIT-0006 Configuration error detected while connecting to cohort cocoCohort, exception org.odpi.openmetadata.frameworks.connectors.ffdc.ConnectorCheckedException was caught with error message: OCF-KAFKA-TOPIC-CONNECTOR-400-002  Egeria was unable to initialize a connection to a Kafka cluster.  The message in the exception was: java.util.concurrent.ExecutionException
Fri Sep 10 13:57:52 BST 2021 cocoMDS2 Exception OMRS-AUDIT-0006 Supplementary information: log record id a51b6ba4-c934-48c9-a76c-a5842dd238cc org.odpi.openmetadata.frameworks.connectors.ffdc.ConnectorCheckedException returned message of OCF-KAFKA-TOPIC-CONNECTOR-400-002  Egeria was unable to initialize a connection to a Kafka cluster.  The message in the exception was: java.util.concurrent.ExecutionException and stacktrace of
OCFCheckedExceptionBase{reportedHTTPCode=400, reportingClassName='org.odpi.openmetadata.adapters.eventbus.topic.kafka.KafkaOpenMetadataTopicConnector', reportingActionDescription='KafkaMonitor.waitForThisBroker', reportedErrorMessage='OCF-KAFKA-TOPIC-CONNECTOR-400-002  Egeria was unable to initialize a connection to a Kafka cluster.  The message in the exception was: java.util.concurrent.ExecutionException', reportedErrorMessageId='OCF-KAFKA-TOPIC-CONNECTOR-400-002 ', reportedErrorMessageParameters=[java.util.concurrent.ExecutionException, egeria.omag.openmetadata.repositoryservices.cohort.cocoCohort.OMRSTopic.registration, org.apache.kafka.common.errors.TimeoutException: Call(callName=listNodes, deadlineMs=1631278672209, tries=1, nextAllowedTryMs=1631278672311) timed out at 1631278672211 after 1 attempt(s)], reportedSystemAction='The system is unable initialize.', reportedUserAction='Ensure that Kafka is available', reportedCaughtException=java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Call(callName=listNodes, deadlineMs=1631278672209, tries=1, nextAllowedTryMs=1631278672311) timed out at 1631278672211 after 1 attempt(s), reportedCaughtExceptionClassName='java.util.concurrent.ExecutionException', relatedProperties=null}
	at org.odpi.openmetadata.adapters.eventbus.topic.kafka.KafkaOpenMetadataTopicConnector.start(KafkaOpenMetadataTopicConnector.java:285)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.start(OMRSTopicConnector.java:258)
	at org.odpi.openmetadata.repositoryservices.metadatahighway.OMRSCohortManager.setSecurityVerifier(OMRSCohortManager.java:347)
	at org.odpi.openmetadata.repositoryservices.metadatahighway.OMRSMetadataHighwayManager.setSecurityVerifier(OMRSMetadataHighwayManager.java:128)
	at org.odpi.openmetadata.repositoryservices.admin.OMRSOperationalServices.setSecurityVerifier(OMRSOperationalServices.java:850)
	at org.odpi.openmetadata.adminservices.OMAGServerOperationalServices.activateWithSuppliedConfig(OMAGServerOperationalServices.java:332)
	at org.odpi.openmetadata.adminservices.OMAGServerOperationalServices.activateWithStoredConfig(OMAGServerOperationalServices.java:148)
	at org.odpi.openmetadata.adminservices.spring.OperationalServicesResource.activateWithStoredConfig(OperationalServicesResource.java:59)
```
