### ISSUE TITLE
Random-ish exception during OMAG startup

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#524]
Using the latest build, I seem to get an error and stack trace as follows on approximately 40-50% of my "mvn clean install" startups -- strangely not consistently, and just re-running will typically then work fine (but running again later won't).

Very possible that it's just me doing something wrong in the startup (though not sure what given it works as much as doesn't with exactly the same startup) -- an ideas?

```
2019-01-04 11:11:45.653 DEBUG 53157 --- [           main] .c.l.ClasspathLoggingApplicationListener : Application failed to start with classpath: [file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/charsets.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/deploy.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/cldrdata.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/dnsns.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/jaccess.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/jfxrt.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/localedata.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/nashorn.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunec.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/zipfs.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/javaws.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jce.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jfr.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jfxswt.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jsse.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/management-agent.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/plugin.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/resources.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/rt.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/ant-javafx.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/dt.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/javafx-mx.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/jconsole.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/packager.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/sa-jdi.jar, file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/tools.jar, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/governance-servers/server-chassis/server-chassis-spring/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/governance-servers/admin-services/admin-services-spring/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/governance-servers/admin-services/admin-services-api/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/governance-servers/admin-services/admin-services-server/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/adapters/open-connectors/connector-configuration-factory/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/open-metadata-archive-connectors/open-metadata-archive-file-connector/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/audit-log-connectors/audit-log-file-connector/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/cohort-registry-store-connectors/cohort-registry-file-store-connector/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/open-metadata-collection-store-connectors/graph-repository-connector/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/open-metadata-collection-store-connectors/omrs-rest-repository-connector/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/inmemory-open-metadata-topic-connector/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/adapters/open-connectors/configuration-store-connectors/configuration-file-store-connector/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/open-metadata-collection-store-connectors/ibm-igc-repository-connector/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/open-metadata-collection-store-connectors/igc-rest-client-library/target/classes/, file:/Users/cgrote/.m2/repository/com/flipkart/zjsonpatch/zjsonpatch/0.4.6/zjsonpatch-0.4.6.jar, file:/Users/cgrote/.m2/repository/org/apache/commons/commons-collections4/4.2/commons-collections4-4.2.jar, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/frameworks/open-connector-framework/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/repository-services/repository-services-spring/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/repository-services/repository-services-apis/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/repository-services/repository-services-implementation/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/connected-asset/connected-asset-spring/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/connected-asset/connected-asset-server/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/connected-asset/connected-asset-api/target/classes/, file:/Users/cgrote/.m2/repository/org/springframework/spring-web/5.1.3.RELEASE/spring-web-5.1.3.RELEASE.jar, file:/Users/cgrote/.m2/repository/org/springframework/spring-beans/5.1.3.RELEASE/spring-beans-5.1.3.RELEASE.jar, file:/Users/cgrote/.m2/repository/org/springframework/spring-core/5.1.3.RELEASE/spring-core-5.1.3.RELEASE.jar, file:/Users/cgrote/.m2/repository/org/springframework/spring-jcl/5.1.3.RELEASE/spring-jcl-5.1.3.RELEASE.jar, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/asset-consumer/asset-consumer-spring/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/asset-consumer/asset-consumer-server/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/asset-consumer/asset-consumer-api/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/connected-asset/connected-asset-client/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/governance-engine/governance-engine-spring/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/governance-engine/governance-engine-server/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/governance-engine/governance-engine-api/target/classes/, file:/Users/cgrote/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.2.0/junit-jupiter-engine-5.2.0.jar, file:/Users/cgrote/.m2/repository/org/apiguardian/apiguardian-api/1.0.0/apiguardian-api-1.0.0.jar, file:/Users/cgrote/.m2/repository/org/junit/platform/junit-platform-engine/1.2.0/junit-platform-engine-1.2.0.jar, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/governance-program/governance-program-spring/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/governance-program/governance-program-server/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/governance-program/governance-program-api/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/asset-catalog/asset-catalog-spring/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/asset-catalog/asset-catalog-server/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/asset-catalog/asset-catalog-api/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/information-view/information-view-spring/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/information-view/information-view-server/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/information-view/information-view-api/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/adapters/open-connectors/repository-services-connectors/open-metadata-collection-store-connectors/inmemory-repository-connector/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/subject-area/subject-area-spring/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/subject-area/subject-area-api/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/subject-area/subject-area-tools/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/adapters/authentication-plugins/http-helper/target/classes/, file:/Users/cgrote/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar, file:/Users/cgrote/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar, file:/Users/cgrote/.m2/repository/com/googlecode/maven-download-plugin/download-maven-plugin/1.4.1/download-maven-plugin-1.4.1.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/maven-core/2.0/maven-core-2.0.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/maven-settings/2.0/maven-settings-2.0.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/wagon/wagon-file/1.0-alpha-5/wagon-file-1.0-alpha-5.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/maven-plugin-parameter-documenter/2.0/maven-plugin-parameter-documenter-2.0.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/wagon/wagon-http-lightweight/1.0-alpha-5/wagon-http-lightweight-1.0-alpha-5.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/reporting/maven-reporting-api/2.0/maven-reporting-api-2.0.jar, file:/Users/cgrote/.m2/repository/doxia/doxia-sink-api/1.0-alpha-4/doxia-sink-api-1.0-alpha-4.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/maven-profile/2.0/maven-profile-2.0.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/maven-model/2.0/maven-model-2.0.jar, file:/Users/cgrote/.m2/repository/org/codehaus/plexus/plexus-container-default/1.0-alpha-8/plexus-container-default-1.0-alpha-8.jar, file:/Users/cgrote/.m2/repository/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/maven-repository-metadata/2.0/maven-repository-metadata-2.0.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/maven-error-diagnostics/2.0/maven-error-diagnostics-2.0.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/maven-plugin-registry/2.0/maven-plugin-registry-2.0.jar, file:/Users/cgrote/.m2/repository/commons-cli/commons-cli/1.0/commons-cli-1.0.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/maven-plugin-descriptor/2.0/maven-plugin-descriptor-2.0.jar, file:/Users/cgrote/.m2/repository/org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/maven-artifact-manager/2.0/maven-artifact-manager-2.0.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/maven-monitor/2.0/maven-monitor-2.0.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/wagon/wagon-ssh/1.0-alpha-5/wagon-ssh-1.0-alpha-5.jar, file:/Users/cgrote/.m2/repository/com/jcraft/jsch/0.1.23/jsch-0.1.23.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/maven-plugin-api/2.0/maven-plugin-api-2.0.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/maven-artifact/2.0/maven-artifact-2.0.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/maven-project/2.0/maven-project-2.0.jar, file:/Users/cgrote/.m2/repository/org/apache/httpcomponents/httpclient/4.0-beta2/httpclient-4.0-beta2.jar, file:/Users/cgrote/.m2/repository/org/apache/httpcomponents/httpcore/4.0-beta3/httpcore-4.0-beta3.jar, file:/Users/cgrote/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar, file:/Users/cgrote/.m2/repository/commons-codec/commons-codec/1.3/commons-codec-1.3.jar, file:/Users/cgrote/.m2/repository/org/codehaus/plexus/plexus-archiver/3.0.1/plexus-archiver-3.0.1.jar, file:/Users/cgrote/.m2/repository/org/codehaus/plexus/plexus-io/2.6/plexus-io-2.6.jar, file:/Users/cgrote/.m2/repository/org/iq80/snappy/snappy/0.3/snappy-0.3.jar, file:/Users/cgrote/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.4/plexus-utils-1.5.4.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/wagon/wagon-provider-api/2.5/wagon-provider-api-2.5.jar, file:/Users/cgrote/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar, file:/Users/cgrote/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar, file:/Users/cgrote/.m2/repository/org/apache/maven/plugins/maven-antrun-plugin/1.8/maven-antrun-plugin-1.8.jar, file:/Users/cgrote/.m2/repository/org/apache/ant/ant/1.9.4/ant-1.9.4.jar, file:/Users/cgrote/.m2/repository/org/apache/ant/ant-launcher/1.9.4/ant-launcher-1.9.4.jar, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/data-engine/data-engine-spring/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/data-engine/data-engine-server/target/classes/, file:/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/access-services/data-engine/data-engine-api/target/classes/, file:/Users/cgrote/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.2.0/junit-jupiter-api-5.2.0.jar, file:/Users/cgrote/.m2/repository/org/opentest4j/opentest4j/1.1.0/opentest4j-1.1.0.jar, file:/Users/cgrote/.m2/repository/org/junit/platform/junit-platform-commons/1.2.0/junit-platform-commons-1.2.0.jar, file:/Users/cgrote/.m2/repository/org/mockito/mockito-junit-jupiter/2.17.0/mockito-junit-jupiter-2.17.0.jar, file:/Users/cgrote/.m2/repository/junit/junit/4.12/junit-4.12.jar, file:/Users/cgrote/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar, file:/Users/cgrote/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.1.1.RELEASE/spring-boot-starter-web-2.1.1.RELEASE.jar, file:/Users/cgrote/.m2/repository/org/springframework/boot/spring-boot-starter/2.1.1.RELEASE/spring-boot-starter-2.1.1.RELEASE.jar, file:/Users/cgrote/.m2/repository/org/springframework/boot/spring-boot/2.1.1.RELEASE/spring-boot-2.1.1.RELEASE.jar, file:/Users/cgrote/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.1.1.RELEASE/spring-boot-autoconfigure-2.1.1.RELEASE.jar, file:/Users/cgrote/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.1.1.RELEASE/spring-boot-starter-logging-2.1.1.RELEASE.jar, file:/Users/cgrote/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar, file:/Users/cgrote/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar, file:/Users/cgrote/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.11.1/log4j-to-slf4j-2.11.1.jar, file:/Users/cgrote/.m2/repository/org/apache/logging/log4j/log4j-api/2.11.1/log4j-api-2.11.1.jar, file:/Users/cgrote/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar, file:/Users/cgrote/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar, file:/Users/cgrote/.m2/repository/org/yaml/snakeyaml/1.23/snakeyaml-1.23.jar, file:/Users/cgrote/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.1.1.RELEASE/spring-boot-starter-json-2.1.1.RELEASE.jar, file:/Users/cgrote/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.7/jackson-datatype-jdk8-2.9.7.jar, file:/Users/cgrote/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.9.7/jackson-datatype-jsr310-2.9.7.jar, file:/Users/cgrote/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.9.7/jackson-module-parameter-names-2.9.7.jar, file:/Users/cgrote/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.1.1.RELEASE/spring-boot-starter-tomcat-2.1.1.RELEASE.jar, file:/Users/cgrote/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.13/tomcat-embed-core-9.0.13.jar, file:/Users/cgrote/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/9.0.13/tomcat-embed-el-9.0.13.jar, file:/Users/cgrote/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.13/tomcat-embed-websocket-9.0.13.jar, file:/Users/cgrote/.m2/repository/org/hibernate/validator/hibernate-validator/6.0.13.Final/hibernate-validator-6.0.13.Final.jar, file:/Users/cgrote/.m2/repository/javax/validation/validation-api/2.0.1.Final/validation-api-2.0.1.Final.jar, file:/Users/cgrote/.m2/repository/org/jboss/logging/jboss-logging/3.3.2.Final/jboss-logging-3.3.2.Final.jar, file:/Users/cgrote/.m2/repository/org/springframework/spring-webmvc/5.1.3.RELEASE/spring-webmvc-5.1.3.RELEASE.jar, file:/Users/cgrote/.m2/repository/org/springframework/spring-aop/5.1.3.RELEASE/spring-aop-5.1.3.RELEASE.jar, file:/Users/cgrote/.m2/repository/org/springframework/spring-context/5.1.3.RELEASE/spring-context-5.1.3.RELEASE.jar, file:/Users/cgrote/.m2/repository/org/springframework/spring-expression/5.1.3.RELEASE/spring-expression-5.1.3.RELEASE.jar, file:/Users/cgrote/.m2/repository/io/springfox/springfox-swagger2/2.9.2/springfox-swagger2-2.9.2.jar, file:/Users/cgrote/.m2/repository/io/swagger/swagger-annotations/1.5.20/swagger-annotations-1.5.20.jar, file:/Users/cgrote/.m2/repository/io/swagger/swagger-models/1.5.20/swagger-models-1.5.20.jar, file:/Users/cgrote/.m2/repository/io/springfox/springfox-spi/2.9.2/springfox-spi-2.9.2.jar, file:/Users/cgrote/.m2/repository/io/springfox/springfox-core/2.9.2/springfox-core-2.9.2.jar, file:/Users/cgrote/.m2/repository/io/springfox/springfox-schema/2.9.2/springfox-schema-2.9.2.jar, file:/Users/cgrote/.m2/repository/io/springfox/springfox-swagger-common/2.9.2/springfox-swagger-common-2.9.2.jar, file:/Users/cgrote/.m2/repository/io/springfox/springfox-spring-web/2.9.2/springfox-spring-web-2.9.2.jar, file:/Users/cgrote/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar, file:/Users/cgrote/.m2/repository/com/fasterxml/classmate/1.4.0/classmate-1.4.0.jar, file:/Users/cgrote/.m2/repository/org/springframework/plugin/spring-plugin-core/1.2.0.RELEASE/spring-plugin-core-1.2.0.RELEASE.jar, file:/Users/cgrote/.m2/repository/org/springframework/plugin/spring-plugin-metadata/1.2.0.RELEASE/spring-plugin-metadata-1.2.0.RELEASE.jar, file:/Users/cgrote/.m2/repository/org/mapstruct/mapstruct/1.2.0.Final/mapstruct-1.2.0.Final.jar, file:/Users/cgrote/.m2/repository/io/springfox/springfox-swagger-ui/2.7.0/springfox-swagger-ui-2.7.0.jar, file:/Users/cgrote/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.7/jackson-databind-2.9.7.jar, file:/Users/cgrote/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.7/jackson-core-2.9.7.jar, file:/Users/cgrote/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar, file:/Users/cgrote/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.7/jackson-annotations-2.9.7.jar, file:/Users/cgrote/.m2/repository/com/webcohesion/enunciate/enunciate-core-annotations/2.10.1/enunciate-core-annotations-2.10.1.jar, file:/Users/cgrote/.m2/repository/net/bytebuddy/byte-buddy/1.8.5/byte-buddy-1.8.5.jar, file:/Users/cgrote/.m2/repository/org/apache/kafka/kafka-clients/0.10.0.0/kafka-clients-0.10.0.0.jar, file:/Users/cgrote/.m2/repository/net/jpountz/lz4/lz4/1.3.0/lz4-1.3.0.jar, file:/Users/cgrote/.m2/repository/org/xerial/snappy/snappy-java/1.1.2.4/snappy-java-1.1.2.4.jar, file:/Applications/IntelliJ%20IDEA%20CE.app/Contents/lib/idea_rt.jar]
2019-01-04 11:11:46.390 ERROR 53157 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [org.odpi.openmetadata.serverchassis.springboot.OMAGApplication]; nested exception is java.io.FileNotFoundException: class path resource [org/odpi/openmetadata/accessservices/subjectarea/server/services/SubjectAreaRESTServicesInstance.class] cannot be opened because it does not exist
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:181) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:315) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:691) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:528) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.odpi.openmetadata.serverchassis.springboot.OMAGApplication.main(OMAGApplication.java:30) [classes/:na]
Caused by: java.io.FileNotFoundException: class path resource [org/odpi/openmetadata/accessservices/subjectarea/server/services/SubjectAreaRESTServicesInstance.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180) ~[spring-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:51) ~[spring-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[spring-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:88) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:75) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81) ~[spring-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.asSourceClass(ConfigurationClassParser.java:685) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser$SourceClass.getSuperClass(ConfigurationClassParser.java:998) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:332) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:242) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:191) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:295) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:242) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:199) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:167) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	... 13 common frames omitted


Process finished with exit code 1
```

**Comment by cmgrote** [comment]
(This is when building via Maven, within IntelliJ on MacOS, which I'm never sure whether it goes into "nap" mode when it's a background window and that might be causing some issues?)

**Comment by cmgrote** [comment]
Closing -- cannot reproduce when simply running "mvn clean install" from the command-line instead of using it as a target within IntelliJ -- seems to be some nuance with IntelliJ.
