### ISSUE TITLE
InvalidParameterException with getEntityByGUID during processNewRelationshipEvent

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5375]
When testing the Postgres connector I see some exceptions as Postgres resources are discovered shortly after enabling my integration server.

All relate to a type mismatch on getEntityBy GUID, for example

```
Thu Jun 17 09:23:59 GMT 2021 mds1 Information OMAS-GOVERNANCE-ENGINE-0017 The Governance Engine Open Metadata Access Service (OMAS) sent a metadata change event to listening Open Watchdog Governance Action Services: New Element
Thu Jun 17 09:24:00 GMT 2021 mds1 Exception An unexpected error org.odpi.openmetadata.frameworks.connectors.ffdc.InvalidParameterException was returned to getEntityByGUID by the metadata server during processNewRelationshipEvent request for open metadata access service Data Manager OMAS on server mds1; message was OMAG-REPOSITORY-HANDLER-404-001 The getEntityByGUID method has retrieved a object for unique identifier (guid) 72bafd56-6071-4505-b73e-9700520f929c which is of type Database rather than type DataContentForDataSet on behalf of method processNewRelationshipEvent
```

^^^ So it appears the GUID relates to a database, but a DataContentForDataSet is being expected
```
Thu Jun 17 09:24:00 GMT 2021 mds1 Exception OMAG-REPOSITORY-HANDLER-0003 Supplementary information: log record id 91443f48-85d2-45e1-b060-90df836d4513 org.odpi.openmetadata.frameworks.connectors.ffdc.InvalidParameterException returned message of OMAG-REPOSITORY-HANDLER-404-001 The getEntityByGUID method has retrieved a object for unique identifier (guid) 72bafd56-6071-4505-b73e-9700520f929c which is of type Database rather than type DataContentForDataSet on behalf of method processNewRelationshipEvent and stacktrace of
InvalidParameterException{parameterName='guid', reportedHTTPCode=404, reportingClassName='org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryErrorHandler', reportingActionDescription='processNewRelationshipEvent', reportedErrorMessage='OMAG-REPOSITORY-HANDLER-404-001 The getEntityByGUID method has retrieved a object for unique identifier (guid) 72bafd56-6071-4505-b73e-9700520f929c which is of type Database rather than type DataContentForDataSet on behalf of method processNewRelationshipEvent', reportedErrorMessageId='OMAG-REPOSITORY-HANDLER-404-001', reportedErrorMessageParameters=[getEntityByGUID, 72bafd56-6071-4505-b73e-9700520f929c, Database, DataContentForDataSet, processNewRelationshipEvent], reportedSystemAction='The service is not able to return the requested object.', reportedUserAction='Check that the unique identifier is correct and the metadata server(s) supporting the service is running.', reportedCaughtException=null, reportedCaughtExceptionClassName='null', relatedProperties=null}
        at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryErrorHandler.handleWrongTypeForGUIDException(RepositoryErrorHandler.java:437)
        at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryErrorHandler.validateInstanceType(RepositoryErrorHandler.java:269)
        at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryHandler.getEntityByGUID(RepositoryHandler.java:2709)
        at org.odpi.openmetadata.commonservices.generichandlers.OpenMetadataAPIGenericHandler.validateAnchorEntity(OpenMetadataAPIGenericHandler.java:2845)
        at org.odpi.openmetadata.accessservices.datamanager.listener.DataManagerOMRSTopicListener.processRelationshipEvent(DataManagerOMRSTopicListener.java:202)
        at org.odpi.openmetadata.accessservices.datamanager.listener.DataManagerOMRSTopicListener.processNewRelationshipEvent(DataManagerOMRSTopicListener.java:686)
        at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicListenerBase.processInstanceEvent(OMRSTopicListenerBase.java:633)
        at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicListenerWrapper.processInstanceEvent(OMRSTopicListenerWrapper.java:146)
        at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.processOMRSEvent(OMRSTopicConnector.java:518)
        at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.lambda$processEvent$0(OMRSTopicConnector.java:455)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

Thu Jun 17 09:24:00 GMT 2021 mds1 Exception OMAS-DATA-MANAGER-0018 Unable to send an outbound event of type d8cfbb5d-970c-40b5-a6ed-2b69b7443a0d for instance with unique identifier of DataContentForDataSet and type name org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException due to exception OMAG-REPOSITORY-HANDLER-500-001 An unexpected error org.odpi.openmetadata.frameworks.connectors.ffdc.InvalidParameterException was returned to getEntityByGUID by the metadata server during processNewRelationshipEvent request for open metadata access service Data Manager OMAS on server mds1; message was OMAG-REPOSITORY-HANDLER-404-001 The getEntityByGUID method has retrieved a object for unique identifier (guid) 72bafd56-6071-4505-b73e-9700520f929c which is of type Database rather than type DataContentForDataSet on behalf of method processNewRelationshipEvent.  The error message from the exception was {4}
Thu Jun 17 09:24:00 GMT 2021 mds1 Exception OMAS-DATA-MANAGER-0018 Supplementary information: log record id d87adad9-f3ee-46b0-ac96-5af8883537a4 org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException returned message of OMAG-REPOSITORY-HANDLER-500-001 An unexpected error org.odpi.openmetadata.frameworks.connectors.ffdc.InvalidParameterException was returned to getEntityByGUID by the metadata server during processNewRelationshipEvent request for open metadata access service Data Manager OMAS on server mds1; message was OMAG-REPOSITORY-HANDLER-404-001 The getEntityByGUID method has retrieved a object for unique identifier (guid) 72bafd56-6071-4505-b73e-9700520f929c which is of type Database rather than type DataContentForDataSet on behalf of method processNewRelationshipEvent and stacktrace of
PropertyServerException{reportedHTTPCode=500, reportingClassName='org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryErrorHandler', reportingActionDescription='processNewRelationshipEvent', reportedErrorMessage='OMAG-REPOSITORY-HANDLER-500-001 An unexpected error org.odpi.openmetadata.frameworks.connectors.ffdc.InvalidParameterException was returned to getEntityByGUID by the metadata server during processNewRelationshipEvent request for open metadata access service Data Manager OMAS on server mds1; message was OMAG-REPOSITORY-HANDLER-404-001 The getEntityByGUID method has retrieved a object for unique identifier (guid) 72bafd56-6071-4505-b73e-9700520f929c which is of type Database rather than type DataContentForDataSet on behalf of method processNewRelationshipEvent', reportedErrorMessageId='OMAG-REPOSITORY-HANDLER-500-001', reportedErrorMessageParameters=[OMAG-REPOSITORY-HANDLER-404-001 The getEntityByGUID method has retrieved a object for unique identifier (guid) 72bafd56-6071-4505-b73e-9700520f929c which is of type Database rather than type DataContentForDataSet on behalf of method processNewRelationshipEvent, processNewRelationshipEvent, Data Manager OMAS, mds1, org.odpi.openmetadata.frameworks.connectors.ffdc.InvalidParameterException, getEntityByGUID], reportedSystemAction='The system is unable to process the request because of an internal error.', reportedUserAction='Verify the sanity of the server.  This is probably a logic error.  If you can not work out what happened, ask the Egeria community for help.', reportedCaughtException=null, reportedCaughtExceptionClassName='null', relatedProperties=null}
        at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryErrorHandler.handleRepositoryError(RepositoryErrorHandler.java:651)
        at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryHandler.getEntityByGUID(RepositoryHandler.java:2727)
        at org.odpi.openmetadata.commonservices.generichandlers.OpenMetadataAPIGenericHandler.validateAnchorEntity(OpenMetadataAPIGenericHandler.java:2845)
        at org.odpi.openmetadata.accessservices.datamanager.listener.DataManagerOMRSTopicListener.processRelationshipEvent(DataManagerOMRSTopicListener.java:202)
        at org.odpi.openmetadata.accessservices.datamanager.listener.DataManagerOMRSTopicListener.processNewRelationshipEvent(DataManagerOMRSTopicListener.java:686)
        at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicListenerBase.processInstanceEvent(OMRSTopicListenerBase.java:633)
        at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicListenerWrapper.processInstanceEvent(OMRSTopicListenerWrapper.java:146)
        at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.processOMRSEvent(OMRSTopicConnector.java:518)
        at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.lambda$processEvent$0(OMRSTopicConnector.java:455)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

Thu Jun 17 09:24:00 GMT 2021 mds1 Event OMAS-GOVERNANCE-ENGINE-0019 The Governance Engine Open Metadata Access Service (OMAS) has sent event of type Metadata change event
```
^^^ this seems to indicate the end of processing this particular event

|

**Comment by planetf1** [comment]
In total we see this for other instances of processNewRelationshipEvent with the following pairings:

Database / DataContentForDataSet
DeployedDatabaseSchema / AssetSchemaType
RelationalDBSchemaType/AttributeForSchema

**Comment by planetf1** [comment]
The full log can be found at https://gist.github.com/42bc71b3a65fca832e4404cd81229fb2

**Comment by mandy-chessell** [comment]
Correct - this is nothing to do with the connector.  The Data Manager OMAS is using the relationship's type name when verifying if the ends are visible to the server's userId.

**Comment by mandy-chessell** [comment]
Hopefully fixed now

**Comment by planetf1** [comment]
I have confirmed this is fixed in current master after retesting
