### ISSUE TITLE
Unable to start service instance

### ISSUE THREAD

**Issue by moonwalk23** [odpi/egeria#5459]
Fri Jul 02 08:22:48 UTC 2021 ProxySP Startup OMRS-AUDIT-0064 The Open Metadata Repository Services (OMRS) has initialized the audit log for the Repository Proxy called ProxySP
Fri Jul 02 08:22:48 UTC 2021 ProxySP Startup OMAG-ADMIN-0001 The ProxySP server is configured with a max page size of 1000
Fri Jul 02 08:22:48 UTC 2021 ProxySP Startup OMRS-AUDIT-0001 The Open Metadata Repository Services (OMRS) is initializing the subsystems to support a new server
Fri Jul 02 08:22:48 UTC 2021 ProxySP Startup OMRS-AUDIT-0003 The local repository is initializing the metadata collection named ProxySP with an id of 3d02a0da-2e8c-4371-8ce9-5f44dcbb038f
Fri Jul 02 08:22:48 UTC 2021 ProxySP Startup OMRS-AUDIT-0029 The local repository outbound event manager is initializing
Fri Jul 02 08:22:48 UTC 2021 ProxySP Exception OMRS-AUDIT-0034 The connector to the local repository failed with a org.odpi.openmetadata.repositoryservices.ffdc.exception.OMRSLogicErrorException exception and the following error message: OMRS-REPOSITORY-400-025 Local metadata repository has not initialized correctly because it has a null metadata collection.
Fri Jul 02 08:22:48 UTC 2021 ProxySP Exception OMRS-AUDIT-0034 Supplementary information: log record id d6e769ce-4f55-4db8-9c1e-bfa07d1968e3 org.odpi.openmetadata.repositoryservices.ffdc.exception.OMRSLogicErrorException returned message of OMRS-REPOSITORY-400-025 Local metadata repository has not initialized correctly because it has a null metadata collection. and stacktrace of
OMRSRuntimeException{reportedHTTPCode=400, reportingClassName='org.odpi.openmetadata.repositoryservices.localrepository.repositoryconnector.LocalOMRSRepositoryConnector', reportingActionDescription='setMetadataCollectionId', reportedErrorMessage='OMRS-REPOSITORY-400-025 Local metadata repository has not initialized correctly because it has a null metadata collection.', reportedErrorMessageId='OMRS-REPOSITORY-400-025', reportedErrorMessageParameters=[LocalRepository], reportedSystemAction='The system is unable to process requests for this repository.', reportedUserAction='Verify that the repository connector is correctly configured in the OMAG server.', reportedCaughtException=OCFCheckedExceptionBase{reportedHTTPCode=400, reportingClassName='org.odpi.egeria.connectors.azure.repositoryconnector.AzureCatalogRepositoryConnector', reportingActionDescription='getMetadataCollection', reportedErrorMessage='OMRS-REPOSITORY-400-025 Local metadata repository has not initialized correctly because it has a null metadata collection.', reportedErrorMessageId='OMRS-REPOSITORY-400-025', reportedErrorMessageParameters=[ProxySP], reportedSystemAction='The system is unable to process requests for this repository.', reportedUserAction='Verify that the repository connector is correctly configured in the OMAG server.', reportedCaughtException=null, reportedCaughtExceptionClassName='null', relatedProperties=null}, reportedCaughtExceptionClassName='org.odpi.openmetadata.repositoryservices.ffdc.exception.RepositoryErrorException', relatedProperties=null, errorMessage='OMRS-REPOSITORY-400-025 Local metadata repository has not initialized correctly because it has a null metadata collection.'}
        at org.odpi.openmetadata.repositoryservices.localrepository.repositoryconnector.LocalOMRSRepositoryConnector.setMetadataCollectionId(LocalOMRSRepositoryConnector.java:414)
        at org.odpi.openmetadata.repositoryservices.admin.OMRSOperationalServices.getLocalOMRSConnector(OMRSOperationalServices.java:1164)
        at org.odpi.openmetadata.repositoryservices.admin.OMRSOperationalServices.initializeLocalRepository(OMRSOperationalServices.java:736)
        at org.odpi.openmetadata.repositoryservices.admin.OMRSOperationalServices.initializeCohortMember(OMRSOperationalServices.java:402)
        at org.odpi.openmetadata.adminservices.OMAGServerOperationalServices.activateWithSuppliedConfig(OMAGServerOperationalServices.java:314)
        at org.odpi.openmetadata.adminservices.OMAGServerOperationalServices.activateWithStoredConfig(OMAGServerOperationalServices.java:148)
        at org.odpi.openmetadata.adminservices.spring.OperationalServicesResource.activateWithStoredConfig(OperationalServicesResource.java:59)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1063)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: OCFCheckedExceptionBase{reportedHTTPCode=400, reportingClassName='org.odpi.egeria.connectors.azure.repositoryconnector.AzureCatalogRepositoryConnector', reportingActionDescription='getMetadataCollection', reportedErrorMessage='OMRS-REPOSITORY-400-025 Local metadata repository has not initialized correctly because it has a null metadata collection.', reportedErrorMessageId='OMRS-REPOSITORY-400-025', reportedErrorMessageParameters=[ProxySP], reportedSystemAction='The system is unable to process requests for this repository.', reportedUserAction='Verify that the repository connector is correctly configured in the OMAG server.', reportedCaughtException=null, reportedCaughtExceptionClassName='null', relatedProperties=null}
        at org.odpi.openmetadata.repositoryservices.connectors.stores.metadatacollectionstore.repositoryconnector.OMRSRepositoryConnector.getMetadataCollection(OMRSRepositoryConnector.java:334)
        at org.odpi.openmetadata.repositoryservices.localrepository.repositoryconnector.LocalOMRSRepositoryConnector.setMetadataCollectionId(LocalOMRSRepositoryConnector.java:392)
        ... 60 more

Fri Jul 02 08:22:48 UTC 2021 ProxySP Shutdown OMAG-ADMIN-0005 The ProxySP server has begun the shutdown process
Fri Jul 02 08:22:48 UTC 2021 ProxySP Shutdown OMRS-AUDIT-0010 The Open Metadata Repository Services (OMRS) is disconnecting the open metadata repositories
Fri Jul 02 08:22:48 UTC 2021 ProxySP Shutdown OMRS-AUDIT-0011 The Open Metadata Repository Services (OMRS) has disconnected from the open metadata repositories
Fri Jul 02 08:22:48 UTC 2021 ProxySP Shutdown OMAG-ADMIN-0006 The ProxySP server has completed shutdown

**Comment by mandy-chessell** [comment]
The problem is in the java class `org.odpi.egeria.connectors.azure.repositoryconnector.AzureCatalogRepositoryConnector`.  This is not a class that has been contributed to Egeria.  Please contact the developers of this class for assistance.
