### ISSUE TITLE
StringIndexOutOfBoundsException in OMRSRepositoryContentHelper.

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#5835]
I issued a search in Rex in React UI for .* of type asset. It ended up in OMRSRepositoryContentHelper with StringIndexOutOfBoundsException.

the line that errors is 

```java
  private boolean isCaseSensitiveContainsRegex(String searchString)
    {
        return searchString != null
                && searchString.startsWith(".*")
                && searchString.endsWith(".*")
                && isCaseSensitiveExactMatchRegex(searchString.substring(2, searchString.length() - 2));
    }
```

If the search string is ".*" then the substring operation errors. 

```text
Wed Oct 20 11:55:14 BST 2021 cocoMDS1 Exception OMRS-AUDIT-0136 A java.lang.StringIndexOutOfBoundsException exception was received from a remote repository with metadata collection id 92740b1b-46ea-49e5-be94-0d7416a16bea during findEntitiesByPropertyValue.  The exception message was String index out of range: 2
Wed Oct 20 11:55:14 BST 2021 cocoMDS1 Exception OMRS-AUDIT-0136 Supplementary information: log record id 5b5a8858-f110-4927-b6fa-e1c3d8dcb82e java.lang.StringIndexOutOfBoundsException returned message of String index out of range: 2 and stacktrace of 
java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.base/java.lang.String.substring(String.java:2655)
	at org.odpi.openmetadata.repositoryservices.localrepository.repositorycontentmanager.OMRSRepositoryContentHelper.isCaseSensitiveContainsRegex(OMRSRepositoryContentHelper.java:2639)
	at org.odpi.openmetadata.repositoryservices.localrepository.repositorycontentmanager.OMRSRepositoryContentHelper.isContainsRegex(OMRSRepositoryContentHelper.java:2667)
	at org.odpi.egeria.connectors.juxt.crux.model.search.TextConditionBuilder.getRegexCondition(TextConditionBuilder.java:367)
	at org.odpi.egeria.connectors.juxt.crux.model.search.TextConditionBuilder.buildRegexConditions(TextConditionBuilder.java:330)
	at org.odpi.egeria.connectors.juxt.crux.model.search.ConditionBuilder.buildConditionForPropertyRef(ConditionBuilder.java:206)
	at org.odpi.egeria.connectors.juxt.crux.model.search.TextConditionBuilder.buildWildcardTextCondition(TextConditionBuilder.java:116)
	at org.odpi.egeria.connectors.juxt.crux.repositoryconnector.CruxOMRSRepositoryConnector.updateTextQuery(CruxOMRSRepositoryConnector.java:2348)
	at org.odpi.egeria.connectors.juxt.crux.repositoryconnector.CruxOMRSRepositoryConnector.searchCruxText(CruxOMRSRepositoryConnector.java:2044)
	at org.odpi.egeria.connectors.juxt.crux.repositoryconnector.CruxOMRSRepositoryConnector.findEntitiesByText(CruxOMRSRepositoryConnector.java:517)
	at org.odpi.egeria.connectors.juxt.crux.repositoryconnector.CruxOMRSMetadataCollection.findEntitiesByPropertyValue(CruxOMRSMetadataCollection.java:355)
	at org.odpi.openmetadata.repositoryservices.localrepository.repositoryconnector.LocalOMRSMetadataCollection.findEntitiesByPropertyValue(LocalOMRSMetadataCollection.java:2362)
	at org.odpi.openmetadata.repositoryservices.enterprise.repositoryconnector.executors.FindEntitiesByPropertyValueExecutor.issueRequestToRepository(FindEntitiesByPropertyValueExecutor.java:181)
	at org.odpi.openmetadata.repositoryservices.enterprise.repositoryconnector.control.ParallelFederationControl.executeCommand(ParallelFederationControl.java:61)
	at org.odpi.openmetadata.repositoryservices.enterprise.repositoryconnector.EnterpriseOMRSMetadataCollection.findEntitiesByPropertyValue(EnterpriseOMRSMetadataCollection.java:1623)
```

**Comment by davidradl** [comment]
I made this change 

'''  private boolean isCaseSensitiveContainsRegex(String searchString)
    {
        return searchString != null
                && searchString.startsWith(".*")
                && searchString.endsWith(".*")
                && (searchString.length() == 2 || isCaseSensitiveExactMatchRegex(searchString.substring(2, searchString.length() - 2)));
    } '''

but it fell into subsequent errors.
