### ISSUE TITLE
Maven surefire breaks in virtualizer (java 11 only)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#595]
virtual data connector test fails with:

[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /Users/jonesn/IdeaProjects/egeria/open-metadata-resources/open-metadata-demos/virtual-data-connector/virtualizer/target/surefire-reports/2019-01-22T10-48-28_648-jvmRun1.dumpstream
[INFO]

When using java 11

➜  egeria (sonar1) ✗)java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.1+13, mixed mode)

more info on the failure:

[ERROR] Command was /bin/sh -c cd /Users/jonesn/IdeaProjects/egeria/open-metadata-resources/open-metadata-demos/virtual-data-connector/virtualizer && /Users/jonesn/java/jdk-11.0.1+13/Contents/Home/bin/java -javaagent:/Users/jonesn/.m2/repository/org/jacoco/org.jacoco.agent/0.8.1/org.jacoco.agent-0.8.1-runtime.jar=destfile=/Users/jonesn/IdeaProjects/egeria/open-metadata-resources/open-metadata-demos/virtual-data-connector/virtualizer/../target/jacoco.exec,append=true -jar /Users/jonesn/IdeaProjects/egeria/open-metadata-resources/open-metadata-demos/virtual-data-connector/virtualizer/target/surefire/surefirebooter7836134154970860815.jar /Users/jonesn/IdeaProjects/egeria/open-metadata-resources/open-metadata-demos/virtual-data-connector/virtualizer/target/surefire 2019-01-22T10-48-28_648-jvmRun1 surefire15028447498785064334tmp surefire_015999334700059969981tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?

And from the dump file created:

# Created at 2019-01-22T10:48:34.789
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream 'FATAL ERROR in native method: processing of -javaagent failed'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command 'FATAL ERROR in native method: processing of -javaagent failed'.
        at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:507)
        at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:210)
        at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:177)
        at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:88)
        at java.base/java.lang.Thread.run(Thread.java:834)

This is recorded as an issue at
https://issues.apache.org/jira/browse/SUREFIRE-1359

But it appears the fault is not there and more investigation is needed.

Logging this for now but not persuing as Java 11 only. Java 8 works ok

**Comment by planetf1** [comment]
Crash implicated jacoco plugin (using -javaagent)
Top level pom was using jacoco plugin 0.8.2
Virtualizer pom was using 0.8.1 & had local configuration - the objective with jacoco is to have consistent reports aggregated for Sonar checking
So
-> updated jacoco version to 0.8.3 (current) using <PluginManagement> instead of property (to handle any transitive dependencies)
-> Removed local definition for jacoco in virtualizer
-> Verified build clean on Java 8 & Java 11
