### ISSUE TITLE
[BUG] Null pointer in tex and rex 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#6114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when using tex and rex in the react ui it null pointers when selecting the server in the UI
The cause is that there is a new ClassificationDef that has a supertype and the view service type explorer code path for a non-null super type for classification is now driven. ClassificationExplorer method 
```
    public void addSubTypName(String subTypeName) {
        subTypeNames.add(subTypeName);
    } 
```
is driven but filed subTypeNames is not initialised. 

This occurs for StewardshipServer ClassificationDef that has a supertype of ServerPurpose. this is a proposed type that is not yet released.

It fails with  
Fri Jan 07 14:30:22 GMT 2022 cocoView1 Startup OMAG-ADMIN-0004 The cocoView1 server has successfully completed start up. The following services are running: [Open Metadata Repository Services (OMRS), Glossary Author OMVS, Repository Explorer OMVS, Dynamic Infrastructure and Operations OMVS, Type Explorer OMVS, Server Author OMVS]
Fri Jan 07 14:30:22 GMT 2022 cocoView1 Startup OMAG-ADMIN-0004 The cocoView1 server has successfully completed start up. The following services are running: [Open Metadata Repository Services (OMRS), Glossary Author OMVS, Repository Explorer OMVS, Dynamic Infrastructure and Operations OMVS, Type Explorer OMVS, Server Author OMVS]
Fri Jan 07 14:30:48 GMT 2022 cocoView1 Exception OMAG-COMMON-0001 The Open Metadata Service has generated an unexpected java.lang.NullPointerException exception during method getTypeExplorer. The message was: null
Fri Jan 07 14:30:48 GMT 2022 cocoView1 Exception OMAG-COMMON-0001 Supplementary information: log record id 9404cb72-2311-448b-8f85-83c018a9c3f4 java.lang.NullPointerException returned message of null and stacktrace of 
java.lang.NullPointerException
	at org.odpi.openmetadata.viewservices.tex.api.properties.ClassificationExplorer.addSubTypName(ClassificationExplorer.java:29)
	at org.odpi.openmetadata.viewservices.tex.api.properties.TypeExplorer.resolveClassifications(TypeExplorer.java:421)
	at org.odpi.openmetadata.viewservices.tex.api.properties.TypeExplorer.resolve(TypeExplorer.java:129)
	at org.odpi.openmetadata.viewservices.tex.handlers.TexViewHandler.getTypeExplorer(TexViewHandler.java:292)
	at org.odpi.openmetadata.viewservices.tex.server.TexViewRESTServices.getTypeExplorer(TexViewRESTServices.java:167)
	at org.odpi.openmetadata.viewservices.tex.server.TexViewRESTResource.getTypeExplorer(TexViewRESTResource.ja

### Expected Behavior

allow tex and rex to start correctly by tolerating classificationDefs with superTypes

### Steps To Reproduce

configure and start tex and rex with the react ui

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by davidradl** [comment]
@lpalashevski @sarbull  I am putting in a minimal fix to avoid the null pointer in the react ui rex and tex view services, I will add it to the rex and tex in the ui chassis so the polymer UI will null pointer.
