### ISSUE TITLE
hibernate-validator v7 breaks server chassis/FVT

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#6288]
Last seen when testing Mar 2022 dependabot updates (https://github.com/odpi/egeria/runs/5375244543?check_suite_focus=true)

When the latest update to hivernate-validator 7.0.2.Final is applied, egeria FVT will fail

For example output see https://github.com/odpi/egeria/actions/runs/1915312553
Example:
```
[INFO] ***************************
[37593](https://github.com/odpi/egeria/runs/5372905416?check_suite_focus=true#step:5:37593)
[INFO] APPLICATION FAILED TO START
[37594](https://github.com/odpi/egeria/runs/5372905416?check_suite_focus=true#step:5:37594)
[INFO] ***************************
[37595](https://github.com/odpi/egeria/runs/5372905416?check_suite_focus=true#step:5:37595)
[INFO] 
[37596](https://github.com/odpi/egeria/runs/5372905416?check_suite_focus=true#step:5:37596)
[INFO] Description:
[37597](https://github.com/odpi/egeria/runs/5372905416?check_suite_focus=true#step:5:37597)
[INFO] 
[37598](https://github.com/odpi/egeria/runs/5372905416?check_suite_focus=true#step:5:37598)
[INFO] The Bean Validation API is on the classpath but no implementation could be found
[37599](https://github.com/odpi/egeria/runs/5372905416?check_suite_focus=true#step:5:37599)
[INFO] 
[37600](https://github.com/odpi/egeria/runs/5372905416?check_suite_focus=true#step:5:37600)
[INFO] Action:
[37601](https://github.com/odpi/egeria/runs/5372905416?check_suite_focus=true#step:5:37601)
[INFO] 
[37602](https://github.com/odpi/egeria/runs/5372905416?check_suite_focus=true#step:5:37602)
[INFO] Add an implementation, such as Hibernate Validator, to the classpath
[37603](https://github.com/odpi/egeria/runs/5372905416?check_suite_focus=true#step:5:37603)
[INFO]
```

**Comment by planetf1** [comment]
Even trying to fix up the relocated package (org.hibernate->org.hibernate.validator at version 6.2.2 causes similar issues ie:

```
2022-03-14 17:47:45.291 ERROR 32009 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultValidator' defined in class path resource [org/springframework/boot/autoconfigure/validation/ValidationAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.AbstractMethodError: Receiver class org.hibernate.validator.internal.engine.ConfigurationImpl does not define or inherit an implementation of the resolved method 'abstract javax.validation.ParameterNameProvider getDefaultParameterNameProvider()' of interface javax.validation.Configuration.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.16.jar!/:5.3.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.16.jar!/:5.3.16]
```

**Comment by planetf1** [comment]
@lpalashevski @bogdan-sava Any idea on this - it seems specific to spring.

**Comment by bogdan-sava** [comment]
hibernate-validator 7 is not compatible yet with spring-boot
Relocation is not working as the incompatibility is not a matter of group/artifact name, but regarding not implementing an expected interface

**Comment by bogdan-sava** [comment]
hibernate-validator 7 implements the  new Jakarta Bean Validation AP, also package renamed to jakarta.validation.
spring-boot is still using Java EE Bean Validation ( javax.validation )

**Comment by bogdan-sava** [comment]
as I can see the the next version of spring 6.0.0 is using hibernate-validator 7

https://github.com/spring-projects/spring-framework/blob/v6.0.0-M2/build.gradle

coming soon...
