### ISSUE TITLE
[BUG] Exception in IGC proxy caused by iterators

### ISSUE THREAD

**Issue by lcpopa** [odpi/egeria#6294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Pagination params are not properly managed by RepositoryFindRelationshipsIterator, causing exceptions in igc-proxy. Judging by the similarities, it is possible that all iterators have this issue

2022-02-22 15:31:33.609 DEBUG 55140 --- [io-9445-exec-10] o.o.e.c.i.i.r.m.r.RelationshipMapping    : addSingleMappedRelationship - adding relationship: ff247351-5a8f-4fcc-b6f2-0713e422c36e:data_file_record@b1c497ce.54bd3a08.c6hn1i9sq.bukfo4j.i3u8dd.g2acraes43blt0nb71avu<AttributeForSchema>data_file_field@b1c497ce.60641b50.c6hn1i9sq.bukj51s.ve15al.mk89o65falg24f018ob1g
Tue Feb 22 15:31:33 EET 2022 igc-proxy Exception OMRS-AUDIT-9014 The Open Metadata Repository Service has generated an unexpected java.lang.IllegalArgumentException exception during method getRelationshipsForEntity.  The message was fromIndex(1000) > toIndex(2)
Tue Feb 22 15:31:33 EET 2022 igc-proxy Exception OMRS-AUDIT-9014 Supplementary information: log record id ac20880f-5adf-4de1-a484-bd856b156586 java.lang.IllegalArgumentException returned message of fromIndex(1000) > toIndex(2) and stacktrace of 
java.lang.IllegalArgumentException: fromIndex(1000) > toIndex(2)
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:509)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1138)
	at org.odpi.egeria.connectors.ibm.igc.repositoryconnector.mapping.entities.EntityMapping.getMappedRelationships(EntityMapping.java:961)
	at org.odpi.egeria.connectors.ibm.igc.repositoryconnector.IGCOMRSMetadataCollection.getRelationshipsForEntity(IGCOMRSMetadataCollection.java:893)
	at org.odpi.openmetadata.repositoryservices.localrepository.repositoryconnector.LocalOMRSMetadataCollection.getRelationshipsForEntity(LocalOMRSMetadataCollection.java:1997)
	at org.odpi.openmetadata.repositoryservices.rest.server.OMRSRepositoryRESTServices.getRelationshipsForEntity(OMRSRepositoryRESTServices.java:2147)
	at org.odpi.openmetadata.repositoryservices.rest.server.spring.LocalRepositoryServicesResource.getRelationshipsForEntity(LocalRepositoryServicesResource.java:782)
	at jdk.internal.reflect.GeneratedMethodAccessor335.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)

### Expected Behavior

Proper pagination params are sent to igc-proxy

### Steps To Reproduce

Search for an entity that involves igc-proxy in fetching it

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by lcpopa** [comment]
Fixed in igc-connector [https://github.com/odpi/egeria-connector-ibm-information-server/pull/679](url)
