### ISSUE TITLE
[BUG] Groovy 3.0.10 causes gradle build failure

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#6409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
> Task :open-metadata-test:open-metadata-fvt:access-services-fvt:analytics-modeling-fvt:configServer
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:88)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.lambda$createCallStaticSite$2(CallSiteArray.java:65)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:63)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:240)
        at configureStartServer.main(configureStartServer.groovy)
Caused by: groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-xml is loaded in version 3.0.9 and you are trying to load version 3.0.10
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java:510)
        at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromProperties(ExtensionModuleScanner.java:87)
        at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromMetaInf(ExtensionModuleScanner.java:81)
        at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanClasspathModulesFrom(ExtensionModuleScanner.java:63)
        at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanClasspathModules(ExtensionModuleScanner.java:54)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:125)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:86)
        at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:37)
        ... 10 more

> Task :open-metadata-test:open-metadata-fvt:access-services-fvt:analytics-modeling-fvt:configServer FAILED
```

### Expected Behavior

build should work correctly

### Steps To Reproduce

update groovyVersion in build.gradle to '3.0.10'

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

### Any Further Information?

The maven build uses groovy 3.0.10 for FVTs
Gradle itself uses groovy, presumably at 3.0.9, which seems to clash to 3.0.10

Needs to be resolved by forcing dependency, or opt not to fix and stay on older version.

Originally seen via https://github.com/odpi/egeria/pull/6408

**Comment by planetf1** [comment]
Update
 - This is affecting my local environment. However the build environment is not affected.
 - Clash may therefore be a local issue.

**Comment by planetf1** [comment]
Gradle is entirely build around groovy. Reading up on this topic it seems inadvisable to try and force a later version of gradle for these build-related tasks.

As such this will not be fixed -- closing
