### ISSUE TITLE
Dependencies update issue

### ISSUE THREAD

**Issue by ruxandraRosu** [odpi/egeria#650]
Exception below is thrown after dependencies update:
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.springframework.http.MediaType.isPresentIn(Ljava/util/Collection;)Z
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1053) ~[spring-webmvc-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) ~[spring-webmvc-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[tomcat-embed-core-9.0.14.jar!/:9.0.14]
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) ~[spring-webmvc-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.14.jar!/:9.0.14]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.14.jar!/:9.0.14]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.14.jar!/:9.0.14]
at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[tomcat-embed-core-9.0.14.jar!/:9.0.14]
at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:461) ~[tomcat-embed-core-9.0.14.jar!/:9.0.14]
at org.apache.catalina.core.Application

**Comment by mandy-chessell** [comment]
What was the client calling?  Which server (Atlas, OMAG Server, ...)?
Where there any audit log messages or was this before the open metadata content was initialized?

**Comment by cmgrote** [comment]
_(Pasting below from PR thread for continuity)_

I'm not recognising anything in the stack trace you pasted... It seems to indicate that Spring itself isn't finding a method that it expects (a method called `org.springframework.http.MediaType.isPresentIn(Ljava/util/Collection;)` ?) Could this have been caused by @bogdan-sava 's update to SpringBoot 2.1.2 from 2.1.1? There isn't anywhere I'm explicitly trying to use that method (that I'm aware of)...

stackoverflow threads with similar errors seem to suggest it's a potential dependency problem where some other dependency (which itself depends on Spring) is loading a different version of the Spring libraries before Spring itself is loaded (?) (https://stackoverflow.com/questions/38442676/java-lang-nosuchmethoderror-org-springframework-http-mediatype-getcharsetljav)

**Comment by bogdan-sava** [comment]
Cannot reproduce on local environment.
I'll update the IBM env to test it

**Comment by cmgrote** [comment]
I haven't been able to reproduce, either...  @ruxandraRosu is this still an issue in your environment?

**Comment by bogdan-sava** [comment]
not an issue
