### ISSUE TITLE
[BUG] null pointer when sending a batch omrs event with only one entity and no relationships  

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#6537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to send a batch event with no relationships the code null pointers. With this error

```
Exception in thread "Thread-5" java.lang.NullPointerException
	at org.odpi.openmetadata.repositoryservices.eventmanagement.OMRSRepositoryEventManager.distributeInstanceEvent(OMRSRepositoryEventManager.java:303)
	at org.odpi.openmetadata.repositoryservices.eventmanagement.OMRSRepositoryEventManager.sendInstanceEvent(OMRSRepositoryEventManager.java:374)
	at org.odpi.openmetadata.repositoryservices.eventmanagement.OMRSRepositoryEventBuilder.processInstanceBatchEvent(OMRSRepositoryEventBuilder.java:1701)
	at org.odpi.openmetadata.repositoryservices.eventmanagement.OMRSRepositoryEventManager.processInstanceBatchEvent(OMRSRepositoryEventManager.java:1578)
```

### Expected Behavior

The event to be successfully sent , if there are no entities or no relationships.

### Steps To Reproduce

I hit this this developing an omrs proxy connector. 

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

### Any Further Information?

The bug is in `OMRSRepositoryEventManager` in method `distributeInstanceEvent`

` */
    		InstanceGraph eventGraph = event.getInstanceBatch();
    		List<EntityDetail> eventEntities = eventGraph.getEntities();
    		List<Relationship> eventRelationships = eventGraph.getRelationships();
    		
    		List<EntityDetail> validEntities = new ArrayList<>();
    		List<Relationship> validRelationships = new ArrayList<>();
    		
    		for (EntityDetail entity: eventEntities)
    		{
    			if (exchangeRule.processInstanceEvent(entity))
    			{
    				validEntities.add(entity);
    			}
    		}
    		
    		
    		for (Relationship relationship: eventRelationships)
    		{
    		...`

line 		`List<Relationship> eventRelationships = eventGraph.getRelationships(); returns null of there are no relationships` so line 	`for (Relationship relationship: eventRelationships)` null pointers.

The fix is either to 
1) not return null for empty lists 
2) or check for null around the for loop .

**Comment by mandy-chessell** [comment]
Should check for null - all of the OMRS interfaces return null rather than empty list
