### ISSUE TITLE
OpenLineage FVT fails with gremlin 3.5.2->3.6.0 update

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#6602]
When testing this month's updates, the lineage FVT fails in gradle with:
```
LineageGraphQueryServiceTest STANDARD_OUT
    11:38:02.471 [Test worker] INFO  o.j.d.c.b.ReadConfigurationBuilder - Set default timestamp provider MICRO
    11:38:02.507 [Test worker] INFO  o.j.g.i.UniqueInstanceIdRetriever - Generated unique-instance-id=7f00000132744-egeriadevrhel1
    11:38:02.533 [Test worker] INFO  o.j.d.c.ExecutorServiceBuilder - Initiated fixed thread pool of size 8
    11:38:02.669 [Test worker] INFO  o.j.diskstorage.log.kcvs.KCVSLog - Loaded unidentified ReadMarker start time 2022-06-01T10:38:02.669024Z into org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller@e5c5e6

LineageGraphQueryServiceTest > initializationError FAILED
    java.lang.NoSuchMethodError: 'org.apache.tinkerpop.gremlin.structure.util.CloseableIterator org.apache.tinkerpop.gremlin.structure.util.CloseableIterator.asCloseable(java.util.Iterator)'
        at org.janusgraph.graphdb.util.CloseableIteratorUtils.<clinit>(CloseableIteratorUtils.java:28)
        at org.janusgraph.graphdb.query.graph.GraphCentricQueryBuilder.lambda$iterables$1(GraphCentricQueryBuilder.java:239)
        at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:278)
        at org.janusgraph.graphdb.database.StandardJanusGraph$1.retrieveSchemaByName(StandardJanusGraph.java:426)
        at org.janusgraph.graphdb.database.cache.StandardSchemaCache.getSchemaId(StandardSchemaCache.java:111)
        at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.getSchemaVertex(StandardJanusGraphTx.java:1033)
        at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.getVertexLabel(StandardJanusGraphTx.java:1168)
        at org.janusgraph.graphdb.database.management.ManagementSystem.getVertexLabel(ManagementSystem.java:1508)
        at org.odpi.openmetadata.openconnectors.governancedaemonconnectors.openlineageconnectors.janusconnector.factory.OpenLineageSchemaHelper.checkAndAddLabelVertex(OpenLineageSchemaHelper.java:98)
        at org.odpi.openmetadata.openconnectors.governancedaemonconnectors.openlineageconnectors.janusconnector.factory.OpenLineageSchemaHelper.createSchemas(OpenLineageSchemaHelper.java:73)
        at org.odpi.openmetadata.openconnectors.governancedaemonconnectors.openlineageconnectors.janusconnector.factory.GraphFactory.initializeGraph(GraphFactory.java:131)
        at org.odpi.openmetadata.openconnectors.governancedaemonconnectors.openlineageconnectors.janusconnector.factory.GraphFactory.openEmbeddedGraph(GraphFactory.java:79)
        at org.odpi.openmetadata.openconnectors.governancedaemonconnectors.openlineageconnectors.janusconnector.factory.GraphFactory.openGraph(GraphFactory.java:52)
        at org.odpi.openmetadata.openconnectors.governancedaemonconnectors.openlineageconnectors.janusconnector.graph.GraphHelper.openGraph(GraphHelper.java:41)
        at org.odpi.openmetadata.openconnectors.governancedaemonconnectors.openlineageconnectors.janusconnector.lineagegraph.LineageGraphQueryServiceTest.beforeClass(LineageGraphQueryServiceTest.java:60)

Gradle Test Executor 251 finished executing tests.
```

Likely similar in maven.

Looks like some API changes relating to `    java.lang.NoSuchMethodError: 'org.apache.tinkerpop.gremlin.structure.util.CloseableIterator `

This also fails with janus ( https://github.com/JanusGraph/janusgraph/pull/3037 ) though it may be the next version addresses, so worth considering. May also be a repackaging issue

**Comment by planetf1** [comment]
this still occurs

**Comment by lpalashevski** [comment]
The fix was merged to master some time ago https://github.com/JanusGraph/janusgraph/pull/3208
We are going to update and re-test once the next release is out.

**Comment by planetf1** [comment]
Janusgraph is at version 1.0 RC. 
Dependabot recommended an update, but I will close dependabot update & suggest we continue monitoring until v1 is finally released. This will likely co-incide with version 4.x of egeria.

See 
* https://github.com/odpi/egeria/pull/7347
* https://github.com/odpi/egeria/pull/7340
* https://github.com/odpi/egeria/pull/7339
