### ISSUE TITLE
[BUG] Server starts up with bad metadata collection: cohort membership

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#6612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

During testing for another issue, I attempted to start a server with an invalid metadata collection id - and in this case to join a cohort named 'xxx'

OMRS-COHORT-REGISTRY-400-002 was reported in the errorlog during server startup
```
Wed Jun 08 16:25:16 BST 2022 mds1 Exception OMRS-AUDIT-0006 Configuration error detected while connecting to cohort xxx, exception org.odpi.openmetadata.repositoryservices.ffdc.exception.OMRSConfigErrorException was caught with error message: OMRS-COHORT-REGISTRY-400-002 The Open Metadata Repository Cohort xxx is not available to server mds1 because the local metadata collection id has been changed from b7db5a0e-291e-410b-b2f2-83020685d244 to e4cdf735-d555-4022-b3bc-a5367551001a since this server registered with the cohort.
```

Ok so this suggests that mds1 will not participate in the cohort, as there is some suspicion about the local metadata collection id - seems reasonable...

We then get an exception of 
```
OMRSRuntimeException{reportedHTTPCode=400, reportingClassName='org.odpi.openmetadata.repositoryservices.metadatahighway.cohortregistry.OMRSCohortRegistry', reportingActionDescription='validateLocalMetadataCollectionId()', reportedErrorMessage='OMRS-COHORT-REGISTRY-400-002 The Open Metadata Repository Cohort xxx is not available to server mds1 because the local metadata collection id has been changed from b7db5a0e-291e-410b-b2f2-83020685d244 to e4cdf735-d555-4022-b3bc-a5367551001a since this server registered with the cohort.', reportedErrorMessageId='OMRS-COHORT-REGISTRY-400-002', reportedErrorMessageParameters=[xxx, mds1, b7db5a0e-291e-410b-b2f2-83020685d244, e4cdf735-d555-4022-b3bc-a5367551001a], reportedSystemAction='The system is unable to connect with other members of the cohort while this incompatibility exists.', reportedUserAction='If there is no reason for the change of local metadata collection id (this is the normal case) change the local metadata collection id back to its original valid in the server configuration. If the local metadata collection Id must be changed (due to a conflict for example) then shutdown the server, restart it with no local repository configured and shut it down normally once the server has successfully unregistered with the cohort. Then re-establish the local repository configuration.Restart the server once the configuration is correct.', reportedCaughtException=null, reportedCaughtExceptionClassName='null', relatedProperties=null, errorMessage='OMRS-COHORT-REGISTRY-400-002 The Open Metadata Repository Cohort xxx is not available to server mds1 because the local metadata collection id has been changed from b7db5a0e-291e-410b-b2f2-83020685d244 to e4cdf735-d555-4022-b3bc-a5367551001a since this server registered with the cohort.'}
```

This provides more information, and confirms the above - either the admin needs to
* restore the metadata collection id to the default (via config file, or REST API)
* deregister from cohort, and restart the server without a metadata collection

That also seems to make sense - two possible recovery actions. Both require access to admin APIs

with a stacktrace of
```
	at org.odpi.openmetadata.repositoryservices.metadatahighway.cohortregistry.OMRSCohortRegistry.validateLocalMetadataCollectionId(OMRSCohortRegistry.java:156)
	at org.odpi.openmetadata.repositoryservices.metadatahighway.cohortregistry.OMRSCohortRegistry.initialize(OMRSCohortRegistry.java:223)
	at org.odpi.openmetadata.repositoryservices.metadatahighway.OMRSCohortManager.initialize(OMRSCohortManager.java:187)
	at org.odpi.openmetadata.repositoryservices.metadatahighway.OMRSMetadataHighwayManager.connectToCohort(OMRSMetadataHighwayManager.java:229)
	at org.odpi.openmetadata.repositoryservices.metadatahighway.OMRSMetadataHighwayManager.initialize(OMRSMetadataHighwayManager.java:100)
	at org.odpi.openmetadata.repositoryservices.admin.OMRSOperationalServices.initializeCohorts(OMRSOperationalServices.java:890)
	at org.odpi.openmetadata.repositoryservices.admin.OMRSOperationalServices.initializeCohortMember(OMRSOperationalServices.java:478)
	at org.odpi.openmetadata.adminservices.OMAGServerOperationalServices.activateWithSuppliedConfig(OMAGServerOperationalServices.java:320)
	at org.odpi.openmetadata.adminservices.OMAGServerOperationalServices.activateWithStoredConfig(OMAGServerOperationalServices.java:150)
	at org.odpi.openmetadata.adminservices.spring.OperationalServicesResource.activateWithStoredConfig(OperationalServicesResource.java:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909
```

The indication that the server will not participate in the cohort makes sense - we don't want to respond to federated queries in this state, or share metadata in other ways.

A question arises...

However in addition, what about regular queries against this server? Should in fact this server be in some kind of 'failed' or 'recovery' state where functionality is limited. That may be hard to determine without more context, but should it at least report it's state as such so that an orchestration engine or admin can take admin action? 

From the log it then seems as if cohort initialization does continue - this seems to different to what the message suggests will happen (though there may be further controls elsewhere) since startup then continues
```
Wed Jun 08 16:25:16 BST 2022 mds1 Startup OMRS-AUDIT-0007 The Open Metadata Repository Services (OMRS) has initialized
Wed Jun 08 16:25:16 BST 2022 mds1 Startup OMRS-AUDIT-0031 The xxx cohort inbound event manager is starting with 0 type definition event consumer(s) and 0 instance event consumer(s)
Wed Jun 08 16:25:16 BST 2022 mds1 Startup OMRS-AUDIT-0026 Initializing listener for cohort xxx
Wed Jun 08 16:25:16 BST 2022 mds1 Startup OMRS-AUDIT-0019 An OMRS Topic Connector has registered with an event bus connector for topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.registration
Wed Jun 08 16:25:16 BST 2022 mds1 Startup OCF-KAFKA-TOPIC-CONNECTOR-0001 Connecting to Apache Kafka Topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.registration with a server identifier of ecff2eda-7940-4363-983a-8f4a89804fb1
Wed Jun 08 16:25:16 BST 2022 mds1 Startup OCF-KAFKA-TOPIC-CONNECTOR-0015 The local server is attempting to connect to Kafka brokers at localhost:9092 [ attempt 1 of 5 ]
Wed Jun 08 16:26:16 BST 2022 mds1 Startup OCF-KAFKA-TOPIC-CONNECTOR-0015 The local server is attempting to connect to Kafka brokers at localhost:9092 [ attempt 2 of 5 ]
Wed Jun 08 16:27:16 BST 2022 mds1 Startup OCF-KAFKA-TOPIC-CONNECTOR-0015 The local server is attempting to connect to Kafka brokers at localhost:9092 [ attempt 3 of 5 ]
Wed Jun 08 16:28:16 BST 2022 mds1 Startup OCF-KAFKA-TOPIC-CONNECTOR-0015 The local server is attempting to connect to Kafka brokers at localhost:9092 [ attempt 4 of 5 ]
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OCF-KAFKA-TOPIC-CONNECTOR-0003 10 properties passed to the Apache Kafka Consumer for topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.registration
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OCF-KAFKA-TOPIC-CONNECTOR-0002 10 properties passed to the Apache Kafka Producer for topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.registration
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OCF-KAFKA-TOPIC-CONNECTOR-0010 The Apache Kafka producer for topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.registration is starting up with 0 buffered messages
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OMRS-AUDIT-0020 An OMRS Topic Connector is ready to send and receive events on topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.registration
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OMRS-AUDIT-0019 An OMRS Topic Connector has registered with an event bus connector for topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.types
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OCF-KAFKA-TOPIC-CONNECTOR-0001 Connecting to Apache Kafka Topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.types with a server identifier of ecff2eda-7940-4363-983a-8f4a89804fb1
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OCF-KAFKA-TOPIC-CONNECTOR-0015 The local server is attempting to connect to Kafka brokers at localhost:9092 [ attempt 1 of 5 ]
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OCF-KAFKA-TOPIC-CONNECTOR-0003 10 properties passed to the Apache Kafka Consumer for topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.types
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OCF-KAFKA-TOPIC-CONNECTOR-0002 10 properties passed to the Apache Kafka Producer for topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.types
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OCF-KAFKA-TOPIC-CONNECTOR-0010 The Apache Kafka producer for topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.types is starting up with 0 buffered messages
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OMRS-AUDIT-0020 An OMRS Topic Connector is ready to send and receive events on topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.types
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OMRS-AUDIT-0019 An OMRS Topic Connector has registered with an event bus connector for topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.instances
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OCF-KAFKA-TOPIC-CONNECTOR-0001 Connecting to Apache Kafka Topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.instances with a server identifier of ecff2eda-7940-4363-983a-8f4a89804fb1
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OCF-KAFKA-TOPIC-CONNECTOR-0015 The local server is attempting to connect to Kafka brokers at localhost:9092 [ attempt 1 of 5 ]
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OMRS-AUDIT-0015 The listener thread for an OMRS Topic Connector for topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.types has started
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OMRS-AUDIT-0015 The listener thread for an OMRS Topic Connector for topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.types has started
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OCF-KAFKA-TOPIC-CONNECTOR-0003 10 properties passed to the Apache Kafka Consumer for topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.instances
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OCF-KAFKA-TOPIC-CONNECTOR-0002 10 properties passed to the Apache Kafka Producer for topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.instances
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OCF-KAFKA-TOPIC-CONNECTOR-0010 The Apache Kafka producer for topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.instances is starting up with 0 buffered messages
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OMRS-AUDIT-0020 An OMRS Topic Connector is ready to send and receive events on topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.instances
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OMRS-AUDIT-0015 The listener thread for an OMRS Topic Connector for topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.instances has started
Wed Jun 08 16:29:03 BST 2022 mds1 Cohort OMRS-AUDIT-0062 Requesting registration information from other members of the open metadata repository cohort xxx
Wed Jun 08 16:29:03 BST 2022 mds1 Event OMRS-AUDIT-8009 The Open Metadata Repository Services (OMRS) has sent event of type Registry Event to the cohort topic egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.registration
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OMRS-AUDIT-0031 The local repository outbound event manager is starting with 0 type definition event consumer(s) and 0 instance event consumer(s)
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OMRS-AUDIT-0032 The local repository outbound event manager is sending out the 901 type definition events that were generated and buffered during server initialization
Wed Jun 08 16:29:03 BST 2022 mds1 Startup OMAG-ADMIN-0004 The mds1 server has successfully completed start up.  The following services are running: [Open Metadata Repository Services (OMRS)]
```
At this point the server looks normal. I've not yet tested multiple cohort members, but the local info is:
```
{
    "class": "CohortConfigResponse",
    "relatedHTTPCode": 200,
    "config": {
        "class": "CohortConfig",
        "cohortName": "xxx",
        "cohortRegistryConnection": {
            "class": "Connection",
            "headerVersion": 0,
            "connectorType": {
                "class": "ConnectorType",
                "headerVersion": 0,
                "type": {
                    "class": "ElementType",
                    "headerVersion": 0,
                    "elementOrigin": "LOCAL_COHORT",
                    "elementVersion": 0,
                    "elementTypeId": "954421eb-33a6-462d-a8ca-b5709a1bd0d4",
                    "elementTypeName": "ConnectorType",
                    "elementTypeVersion": 1,
                    "elementTypeDescription": "A set of properties describing a type of connector."
                },
                "guid": "108b85fe-d7a8-45c3-9f88-742ac4e4fd14",
                "qualifiedName": "Egeria:CohortRegistryConnector:File",
                "displayName": "File-based Cohort Registry Store Connector",
                "description": "Connector supports storing of the open metadata cohort registry in a file using JSON format.",
                "connectorProviderClassName": "org.odpi.openmetadata.adapters.repositoryservices.cohortregistrystore.file.FileBasedRegistryStoreProvider"
            },
            "endpoint": {
                "class": "Endpoint",
                "headerVersion": 0,
                "address": "./data/servers/mds1/cohorts/xxx.registrystore"
            }
        },
        "cohortOMRSRegistrationTopicConnection": {
            "class": "VirtualConnection",
            "headerVersion": 0,
            "connectorType": {
                "class": "ConnectorType",
                "headerVersion": 0,
                "connectorProviderClassName": "org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicProvider"
            },
            "embeddedConnections": [
                {
                    "class": "EmbeddedConnection",
                    "headerVersion": 0,
                    "position": 0,
                    "displayName": "xxx OMRS Topic for registrations",
                    "embeddedConnection": {
                        "class": "Connection",
                        "headerVersion": 0,
                        "connectorType": {
                            "class": "ConnectorType",
                            "headerVersion": 0,
                            "type": {
                                "class": "ElementType",
                                "headerVersion": 0,
                                "elementOrigin": "LOCAL_COHORT",
                                "elementVersion": 0,
                                "elementTypeId": "954421eb-33a6-462d-a8ca-b5709a1bd0d4",
                                "elementTypeName": "ConnectorType",
                                "elementTypeVersion": 1,
                                "elementTypeDescription": "A set of properties describing a type of connector."
                            },
                            "guid": "3851e8d0-e343-400c-82cb-3918fed81da6",
                            "qualifiedName": "Egeria:OpenMetadataTopicConnector:Kafka",
                            "displayName": "Apache Kafka Open Metadata Topic Connector",
                            "description": "Apache Kafka Open Metadata Topic Connector supports string based events over an Apache Kafka event bus.",
                            "supportedAssetTypeName": "KafkaTopic",
                            "expectedDataFormat": "PLAINTEXT",
                            "connectorProviderClassName": "org.odpi.openmetadata.adapters.eventbus.topic.kafka.KafkaOpenMetadataTopicProvider",
                            "connectorInterfaces": [
                                "org.odpi.openmetadata.frameworks.connectors.Connector",
                                "org.odpi.openmetadata.repositoryservices.connectors.openmetadatatopic.OpenMetadataTopic",
                                "org.odpi.openmetadata.frameworks.auditlog.AuditLoggingComponent"
                            ],
                            "recognizedConfigurationProperties": [
                                "producer",
                                "consumer",
                                "local.server.id",
                                "sleepTime"
                            ]
                        },
                        "endpoint": {
                            "class": "Endpoint",
                            "headerVersion": 0,
                            "address": "egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.registration"
                        },
                        "configurationProperties": {
                            "producer": {
                                "bootstrap.servers": "localhost:9092",
                                "bring.up.minSleepTime": "60000",
                                "bring.up.retries": "5"
                            },
                            "local.server.id": "ecff2eda-7940-4363-983a-8f4a89804fb1",
                            "consumer": {
                                "bootstrap.servers": "localhost:9092",
                                "bring.up.minSleepTime": "60000",
                                "bring.up.retries": "5"
                            }
                        }
                    }
                }
            ]
        },
        "cohortOMRSTypesTopicConnection": {
            "class": "VirtualConnection",
            "headerVersion": 0,
            "connectorType": {
                "class": "ConnectorType",
                "headerVersion": 0,
                "connectorProviderClassName": "org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicProvider"
            },
            "embeddedConnections": [
                {
                    "class": "EmbeddedConnection",
                    "headerVersion": 0,
                    "position": 0,
                    "displayName": "xxx OMRS Topic for types",
                    "embeddedConnection": {
                        "class": "Connection",
                        "headerVersion": 0,
                        "connectorType": {
                            "class": "ConnectorType",
                            "headerVersion": 0,
                            "type": {
                                "class": "ElementType",
                                "headerVersion": 0,
                                "elementOrigin": "LOCAL_COHORT",
                                "elementVersion": 0,
                                "elementTypeId": "954421eb-33a6-462d-a8ca-b5709a1bd0d4",
                                "elementTypeName": "ConnectorType",
                                "elementTypeVersion": 1,
                                "elementTypeDescription": "A set of properties describing a type of connector."
                            },
                            "guid": "3851e8d0-e343-400c-82cb-3918fed81da6",
                            "qualifiedName": "Egeria:OpenMetadataTopicConnector:Kafka",
                            "displayName": "Apache Kafka Open Metadata Topic Connector",
                            "description": "Apache Kafka Open Metadata Topic Connector supports string based events over an Apache Kafka event bus.",
                            "supportedAssetTypeName": "KafkaTopic",
                            "expectedDataFormat": "PLAINTEXT",
                            "connectorProviderClassName": "org.odpi.openmetadata.adapters.eventbus.topic.kafka.KafkaOpenMetadataTopicProvider",
                            "connectorInterfaces": [
                                "org.odpi.openmetadata.frameworks.connectors.Connector",
                                "org.odpi.openmetadata.repositoryservices.connectors.openmetadatatopic.OpenMetadataTopic",
                                "org.odpi.openmetadata.frameworks.auditlog.AuditLoggingComponent"
                            ],
                            "recognizedConfigurationProperties": [
                                "producer",
                                "consumer",
                                "local.server.id",
                                "sleepTime"
                            ]
                        },
                        "endpoint": {
                            "class": "Endpoint",
                            "headerVersion": 0,
                            "address": "egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.types"
                        },
                        "configurationProperties": {
                            "producer": {
                                "bootstrap.servers": "localhost:9092",
                                "bring.up.minSleepTime": "60000",
                                "bring.up.retries": "5"
                            },
                            "local.server.id": "ecff2eda-7940-4363-983a-8f4a89804fb1",
                            "consumer": {
                                "bootstrap.servers": "localhost:9092",
                                "bring.up.minSleepTime": "60000",
                                "bring.up.retries": "5"
                            }
                        }
                    }
                }
            ]
        },
        "cohortOMRSInstancesTopicConnection": {
            "class": "VirtualConnection",
            "headerVersion": 0,
            "connectorType": {
                "class": "ConnectorType",
                "headerVersion": 0,
                "connectorProviderClassName": "org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicProvider"
            },
            "embeddedConnections": [
                {
                    "class": "EmbeddedConnection",
                    "headerVersion": 0,
                    "position": 0,
                    "displayName": "xxx OMRS Topic for instances",
                    "embeddedConnection": {
                        "class": "Connection",
                        "headerVersion": 0,
                        "connectorType": {
                            "class": "ConnectorType",
                            "headerVersion": 0,
                            "type": {
                                "class": "ElementType",
                                "headerVersion": 0,
                                "elementOrigin": "LOCAL_COHORT",
                                "elementVersion": 0,
                                "elementTypeId": "954421eb-33a6-462d-a8ca-b5709a1bd0d4",
                                "elementTypeName": "ConnectorType",
                                "elementTypeVersion": 1,
                                "elementTypeDescription": "A set of properties describing a type of connector."
                            },
                            "guid": "3851e8d0-e343-400c-82cb-3918fed81da6",
                            "qualifiedName": "Egeria:OpenMetadataTopicConnector:Kafka",
                            "displayName": "Apache Kafka Open Metadata Topic Connector",
                            "description": "Apache Kafka Open Metadata Topic Connector supports string based events over an Apache Kafka event bus.",
                            "supportedAssetTypeName": "KafkaTopic",
                            "expectedDataFormat": "PLAINTEXT",
                            "connectorProviderClassName": "org.odpi.openmetadata.adapters.eventbus.topic.kafka.KafkaOpenMetadataTopicProvider",
                            "connectorInterfaces": [
                                "org.odpi.openmetadata.frameworks.connectors.Connector",
                                "org.odpi.openmetadata.repositoryservices.connectors.openmetadatatopic.OpenMetadataTopic",
                                "org.odpi.openmetadata.frameworks.auditlog.AuditLoggingComponent"
                            ],
                            "recognizedConfigurationProperties": [
                                "producer",
                                "consumer",
                                "local.server.id",
                                "sleepTime"
                            ]
                        },
                        "endpoint": {
                            "class": "Endpoint",
                            "headerVersion": 0,
                            "address": "egeria.omag.openmetadata.repositoryservices.cohort.xxx.OMRSTopic.instances"
                        },
                        "configurationProperties": {
                            "producer": {
                                "bootstrap.servers": "localhost:9092",
                                "bring.up.minSleepTime": "60000",
                                "bring.up.retries": "5"
                            },
                            "local.server.id": "ecff2eda-7940-4363-983a-8f4a89804fb1",
                            "consumer": {
                                "bootstrap.servers": "localhost:9092",
                                "bring.up.minSleepTime": "60000",
                                "bring.up.retries": "5"
                            }
                        }
                    }
                }
            ]
        },
        "cohortOMRSTopicProtocolVersion": "V1",
        "eventsToProcessRule": "ALL"
    }
}
```

It seems as if the server is in a bad state which needs one of two actions performing. It is 'risky' for it to participate in a cohort, but it is unclear how this is known to callers or cohort members 

@mandy-chessell  ?

### Expected Behavior

see above

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by mandy-chessell** [comment]
@planetf1 I had a look at the code and found the problem - its a one line change - I can do it - but I wondered if you want to do it - particulaly if it is holding you up?

The problem is in OMRSCohortManager in the `initialize` method.  The catch statement at line 279 is outputting AudiitLog message OMRS-AUDIT-0006 and returning - it should rethrow the error after it has output the audit log message.

**Comment by planetf1** [comment]
I'll do the PR. thanks
