### ISSUE TITLE
Can't load library libtcnative-1.so

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#664]
I can see this error message when server-chassis-spring starts:

org.apache.tomcat.jni.LibraryNotFoundError: Can't load library: /opt/igc-repo-proxy/bin/libtcnative-1.so, Can't load library: /opt/igc-repo-proxy/bin/liblibtcnative-1.so, no tcnative-1 in java.library.path, no libtcnative-1 in java.library.path

**Comment by bogdan-sava** [comment]
It is a debug message from tomcat embedded

**Comment by cmgrote** [comment]
Is this in the "old" IGC repository proxy (under virtualizer demo area of code hierarchy), which I think we're now suggesting to remove (?)  The new one (under `...implementation/adapters/open-connectors/...`) should no longer have an embedded tomcat -- it just re-uses the OMAG server chassis...

**Comment by bogdan-sava** [comment]
This is an issue of embedded tomcat.

**Comment by DSBoyce** [comment]
Was there ever a concrete solution to this. Im having the same exact issue.

**Comment by mandy-chessell** [comment]
@bogdan-sava ?

**Comment by usmanovbf** [comment]
same issue

**Comment by planetf1** [comment]
@usmanovbf @DSBoyce Can you provide some more information
 - What version of egeria are you using? 
 - Are you building from source, or using our maven artifacts or docker images
 - What exactly are you running when you see this error? (standalone or from an IDE etc)
 - What OS platform/version are you running

I have not seen this error -- and in the egeria team we thought this was relating to some very old code, so I'm concerned if we're seeing it with current code. Let's see if we can get to the bottom of it.

Reopening

**Comment by planetf1** [comment]
Going to close for now as we don't have sufficient info to persue.

Please add relevant info & reopen if required.

**Comment by Maxvgrad** [comment]
I have the same issue. Here is stack trace:

>org.apache.tomcat.jni.LibraryNotFoundError: Can't load library: /Users/{omit my path for this message}/bin/libtcnative-1.dylib, Can't load library: /Users/{omit my path for this message}/bin/liblibtcnative-1.dylib, no tcnative-1 in java.library.path: [/Users/{omit my path for this message}/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .], no libtcnative-1 in java.library.path: [/Users/{omit my path for this message}/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at org.apache.tomcat.jni.Library.<init>(Library.java:102)
	at org.apache.tomcat.jni.Library.initialize(Library.java:206)
	at org.apache.catalina.core.AprLifecycleListener.init(AprLifecycleListener.java:198)
	at org.apache.catalina.core.AprLifecycleListener.isAprAvailable(AprLifecycleListener.java:107)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getDefaultLifecycleListeners(TomcatServletWebServerFactory.java:168)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.<init>(TomcatServletWebServerFactory.java:119)
	at org.springframework.boot.autoconfigure.web.servlet.ServletWebServerFactoryConfiguration$EmbeddedTomcat.tomcatServletWebServerFactory(ServletWebServerFactoryConfiguration.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:635)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:212)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:177)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:158)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)

**Comment by planetf1** [comment]
The stacktrace above is put out as a debug message I think by tomcat when it tries to load a native library to improve performance. Tomcat still functions without it ie
```
16:03:07.750 [main] DEBUG o.a.c.core.AprLifecycleListener - The Apache Tomcat Native library could not be found
```

Tomcat will log quite a few 'exceptions' as DEBUG messages  that may relate to various things not being found as it figures out an appropriate configuration to use.

So I think the question here is
 - what additional benefit does the native library offer
 - how might a user configure it
 - how else might a user want to deploy the spring app

This is only an optimization, there is no error here.

Googling elicits a few examples of attempts to answer this configuration such as https://medium.com/@crueda/tomcat-native-openssl-in-spring-boot-2-0-a341ad07471d

@Maxvgrad perhaps you could give some of the suggestions and propose a PR to improve our documentation in this area? 


 -

**Comment by planetf1** [comment]
This is normal tomcat behaviour. By default we do not log this message. I don't see we have any particularly useful action to take.

**Comment by visheshmohan** [comment]
`2022-01-12 06:40:46.967 DEBUG [improv-services,,,] 1 --- [ main] o.a.catalina.core.AprLifecycleListener : The APR based Apache Tomcat Native library could not be found using names [tcnative-1, libtcnative-1] on the java.library.path [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]. The errors reported were [Can't load library: /bin/libtcnative-1.so, Can't load library: /bin/liblibtcnative-1.so, no tcnative-1 in java.library.path, no libtcnative-1 in java.library.path]



org.apache.tomcat.jni.LibraryNotFoundError: Can't load library: /bin/libtcnative-1.so, Can't load library: /bin/liblibtcnative-1.so, no tcnative-1 in java.library.path, no libtcnative-1 in java.library.path`


`org.apache.tomcat.jni.LibraryNotFoundError: Can't load library: /bin/libtcnative-1.so, Can't load library: /bin/liblibtcnative-1.so, no tcnative-1 in java.library.path, no libtcnative-1 in java.library.path
at org.apache.tomcat.jni.Library.<init>(Library.java:102) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
at org.apache.tomcat.jni.Library.initialize(Library.java:206) ~[tomcat-embed-core-9.0.31.jar!/:9.0.31]
at org.apache.catalina.core.AprLifecycleListener.init(AprLifecycleListener.java:198) [tomcat-embed-core-9.0.31.jar!/:9.0.31]
at org.apache.catalina.core.AprLifecycleListener.isAprAvailable(AprLifecycleListener.java:107) [tomcat-embed-core-9.0.31.jar!/:9.0.31]
at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getDefaultLifecycleListeners(TomcatServletWebServerFactory.java:168) [spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.<init>(TomcatServletWebServerFactory.java:119) [spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.autoconfigure.web.servlet.ServletWebServerFactoryConfiguration$EmbeddedTomcat.tomcatServletWebServerFactory(ServletWebServerFactoryConfiguration.java:75) [spring-boot-autoconfigure-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_262]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_262]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_262]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_262]
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) [spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) [spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636) [spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) [spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) [spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) [spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) [spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) [spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) [spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207) [spring-beans-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:210) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:179) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
at com.centurylink.improv.api.application.ImprovApplication.main(ImprovApplication.java:22) ~[classes!/:1.0.0]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_262]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_262]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_262]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_262]
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[app.jar:1.0.0]
at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[app.jar:1.0.0]
at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[app.jar:1.0.0]
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[app.jar:1.0.0]`

> Here is the dockerFile for our project that worked fine for last few months

`FROM organizations-local-repo/java8:2020Q4
VOLUME /tmp
ADD /app-api/target/app-services-1.0.0.jar app.jar
ENTRYPOINT ["java", "-Xmx750m", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]`

Are we missing something here?

**Comment by planetf1** [comment]
@visheshmohan Hi - I don't see any mention of Egeria in the above stack trace and Dockerfile. Was this seen using Egeria?

Our understanding is that this stacktrace occurs in 'normal' tomcat operation. 

Tomcat can optionally use native libraries to improve performance, but functions fine without them. There is some further information on this in the [tomcat docs](https://tomcat.apache.org/native-doc/) 

We don't currently make use of them in the docker container we create for egeria for example - but if you could like to propose an enhancement that incorporates them, I'd be happy to review that.

**Comment by rapar8** [comment]
I was having same issue but I was using kotlin with spring, 
Kotlin doen't throw any error if for example properties is missing in application, 

Solution I use is put try catch in main, And got ERROR

**Comment by visheshmohan** [comment]
@planetf1  - Thanks for your response and I really appreciate you responding to my problem statement.

The point is, we got this error in a completely different application that is unrelated to Egeria, and it came when K8 environment tried starting the java spring-boot app docker image.

I posted it here since it was ranked #1 in google search when I tried looking for a solution to this scenario. 
For those who may land on this page for some reason, I must tell, that this problem was generated in my application due to some other error that is not even related to it.

**Comment by pranith-shabodi** [comment]
I am facing this issue in my project

**Comment by kusumkappdirect** [comment]
is it resolved @pranith-shabodi  @visheshmohan

**Comment by planetf1** [comment]
@pranith-shabodi @visheshmohan The message is seen in the debug log with tomcat - something we found with our Egeria code

It's 'normal' in that tomcat looks for native platform code to improve performance which may, or may not, be present.
tomcat will work in either case
I recommend visiting the apache tomcat community to get more info -> https://tomcat.apache.org/native-doc/ is a starting point about the library

**Comment by princeramkot** [comment]
i receive this error when i add SPRING_PROFILES_ACTIVE=dev in my env variables to use dev profile, if i dont' use it i don't get errors

**Comment by mandy-chessell** [comment]
@princeramkot I am not sure what the SPRING_PROFILES_ACTIVE=dev is for - what are you trying to achieve?
