### ISSUE TITLE
[BUG] mvn clean install throws multiple Exceptions to the console 

### ISSUE THREAD

**Issue by wbittles** [odpi/egeria#6796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

` Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.277 s - in org.odpi.openmetadata.accessservices.designmodel.responses.OMASAPIResponseTest
[main] ERROR org.testng.reporters.jq.Main - /home/wbittles/egeria-repos/egeria/open-metadata-implementation/access-services/design-model/design-model-api/target/surefire-reports/jquery-3.6.0.min.js
java.nio.file.FileAlreadyExistsException: /home/wbittles/egeria-repos/egeria/open-metadata-implementation/access-services/design-model/design-model-api/target/surefire-reports/jquery-3.6.0.min.js
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
	at java.base/java.nio.file.Files.copy(Files.java:3067)
	at org.testng.reporters.jq.Main.generateReport(Main.java:95)
	at org.testng.TestNG.generateReports(TestNG.java:1134)
	at org.testng.TestNG.run(TestNG.java:1072)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:111)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:122)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:89)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.73 s - in`

### Expected Behavior

no exceptions 

### Steps To Reproduce

mvn clean install 

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by planetf1** [comment]
This problem was:
-  initially reported in #6692 
- testing update 7.5 -> 7.6.1 was backed off in #6693 (1 Jul)
- #6680 reintroduced : -> 7.6.1 (5 Jul) as part of the July dependabot run
- testng team have an issue open at https://github.com/cbeust/testng/issues/2770 which reports the issue, and we are awaiting an update. 

For now I will back off the testing update

**Comment by planetf1** [comment]
Though we make some use of testng, this was primarily due to JUnit4 lacking capability.
JUnit5 addressed these gaps, and tends to integrate better.
We may want to consider reducing testng use and moving more to JUnit5 where this is in use, however it's not clear if it's a valuable effort.
