### ISSUE TITLE
Problems building master with npm / node_modules already existing elsewhere

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#681]
I'm no longer able to successfully build master with `mvn clean install` (see logs below).  I suspect this is because the install process is now installing and trying to use `npm`, but if a user already has `npm` installed (and perhaps more problematically, already has a `node_modules` directory somewhere higher-up the source tree), then any `npm install <module>` commands will end up installing node modules into that higher-level source location -- not into the expected location under `.../access-services-user-interface/tools/node_modules/...`

```
[INFO] Ranger Gaian Plugin ................................ SUCCESS [  8.083 s]
[INFO] Gaian Impersonation support ........................ SUCCESS [  1.098 s]
[INFO] Open Metadata User Interfaces ...................... SUCCESS [  0.134 s]
[INFO] Access Services User Interface ..................... FAILURE [ 22.346 s]
[INFO] Server Configuration User Interface ................ SKIPPED
[INFO] Open Metadata Conformance Suite .................... SKIPPED
[INFO] Open Metadata Distribution Files ................... SKIPPED
[INFO] Open Metadata Packages ............................. SKIPPED
[INFO] Open Metadata Client Package ....................... SKIPPED
[INFO] Open Metadata Native Package ....................... SKIPPED
[INFO] Open Metadata Caller Package ....................... SKIPPED
[INFO] Open Metadata Adapter Package ...................... SKIPPED
[INFO] Open Metadata Assemblies ........................... SKIPPED
[INFO] Open Metadata Publication Processes ................ SKIPPED
[INFO] Egeria Website ..................................... SKIPPED
[INFO] Open Metadata Resources ............................ SKIPPED
[INFO] Open Metadata Samples .............................. SKIPPED
[INFO] Access Services Samples ............................ SKIPPED
[INFO] Governance Program OMAS Client Samples ............. SKIPPED
[INFO] Subject Area OMAS Samples .......................... SKIPPED
[INFO] Open Metadata Demos ................................ SKIPPED
[INFO] Virtual Data Connector (VDC) Demo .................. SKIPPED
[INFO] IGC Repository Proxy ............................... SKIPPED
[INFO] Virtualizer ........................................ SKIPPED
[INFO] In Memory repository Demo .......................... SKIPPED
[INFO] Open Metadata Tutorials ............................ SKIPPED
[INFO] Open Metadata Test Resources ....................... SKIPPED
[INFO] Open Metadata Access Service FVT Resources ......... SKIPPED
[INFO] Open Metadata Test Resources ....................... SKIPPED
[INFO] Subject Area OMAS FVT .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:14 min
[INFO] Finished at: 2019-01-31T14:40:08Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (Polymer build) on project access-services-user-interface: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :access-services-user-interface
```

Stack trace further up indicates:

```
[INFO] --- jacoco-maven-plugin:0.8.2:prepare-agent (agent) @ access-services-user-interface ---
[INFO] argLine set to -javaagent:/Users/cgrote/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/Users/cgrote/Developer/git-repos/forks/odpi/egeria/target/jacoco.exec,append=true
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:exec (Polymer build) @ access-services-user-interface ---
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/Users/cgrote/Developer/git-repos/forks/odpi/egeria/open-metadata-implementation/user-interfaces/access-services-user-interface/tools/node_modules/polymer-cli/bin/polymer.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

(In my case, I have most of my node modules installed into `/Users/cgrote/Developer/git-repos/node_modules`, and I can see this is were `polymer-cli` has been placed by the build as well -- nowhere within the Egeria tree...)

**Comment by cmgrote** [comment]
Probably need to use something like the `--prefix` argument to `npm` to ensure it places `node_modules` where we expect it (see: https://stackoverflow.com/questions/14742553/how-to-set-custom-location-for-local-installation-of-npm-package)

**Comment by cmgrote** [comment]
(Trying out some fixes and will take you on any resulting PR.)

**Comment by bogdan-sava** [comment]
Indeed!
Didn't see that coming.
Thanks Chris
