### ISSUE TITLE
logback 1.4 causes applications to fail to load (chassis, UI, etc)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#6884]
If logback is updated from 1.2.11 to 1.4 (or 1.3), ie by updating this in the top level pom:
```
         <logback.version>1.4.0</logback.version>
```

then egeria tests fail.

This test was detected by the UI server chassis UT which attempts to resolve the context (nice test!) - it would be detected later in FVT

For example in the  ui server chassis we see
```
➜  ui-chassis-spring git:(master) ✗ java -jar target/ui-chassis-spring-3.12-SNAPSHOT.jar
\Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.lang.NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:293)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:118)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationStartingEvent(LoggingApplicationListener.java:238)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:220)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:79)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$starting$0(SpringApplicationRunListeners.java:56)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:56)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:299)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at org.odpi.openmetadata.userinterface.uichassis.springboot.EgeriaUIPlatform.main(EgeriaUIPlatform.java:56)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.impl.StaticLoggerBinder
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 23 more
```

This appears to be an issue where there is no appropriate slf4j logger implementation, even though logback:classic is in the classpath/maven dependencies.

The same stack can be seen with the server chassis.

It's either an intentional change, or bug in the recent update to logback, or possibly slf4j

For the Sep dependabot updates we will skip the logback update, but opening for any ideas, and to track eventual resolution

**Comment by planetf1** [comment]
The resolved dependency tree in this failing example is:
```
[INFO] --- maven-dependency-plugin:3.3.0:tree (default-cli) @ ui-chassis-spring ---
[INFO] org.odpi.egeria:ui-chassis-spring:jar:3.12-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.7.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.7.3:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.7.3:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.17.2:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.18.0:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.36:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.31:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.7.3:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.13.3:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.3:runtime
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.13.3:compile
[INFO] |  \- org.springframework.boot:spring-boot-starter-tomcat:jar:2.7.3:compile
[INFO] |     \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.65:compile
[INFO] +- org.springframework.boot:spring-boot-starter-validation:jar:2.7.3:compile
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.65:compile
[INFO] |  \- org.hibernate.validator:hibernate-validator:jar:6.2.4.Final:compile
[INFO] |     +- jakarta.validation:jakarta.validation-api:jar:3.0.2:compile
[INFO] |     +- org.jboss.logging:jboss-logging:jar:3.4.1.Final:compile
[INFO] |     \- com.fasterxml:classmate:jar:1.5.1:compile
[INFO] +- org.springframework.boot:spring-boot-starter-security:jar:2.7.3:compile
[INFO] |  \- org.springframework:spring-aop:jar:5.3.22:compile
[INFO] +- org.springframework.boot:spring-boot-starter-data-redis:jar:2.7.3:compile
[INFO] |  \- org.springframework.data:spring-data-redis:jar:2.7.2:compile
[INFO] |     +- org.springframework.data:spring-data-keyvalue:jar:2.7.2:compile
[INFO] |     |  \- org.springframework.data:spring-data-commons:jar:2.7.2:compile
[INFO] |     +- org.springframework:spring-oxm:jar:5.3.22:compile
[INFO] |     \- org.springframework:spring-context-support:jar:5.3.22:compile
[INFO] +- io.lettuce:lettuce-core:jar:6.2.0.RELEASE:compile
[INFO] |  +- io.netty:netty-common:jar:4.1.80.Final:compile
[INFO] |  +- io.netty:netty-handler:jar:4.1.80.Final:compile
[INFO] |  |  +- io.netty:netty-resolver:jar:4.1.80.Final:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.80.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-unix-common:jar:4.1.80.Final:compile
[INFO] |  |  \- io.netty:netty-codec:jar:4.1.80.Final:compile
[INFO] |  +- io.netty:netty-transport:jar:4.1.80.Final:compile
[INFO] |  \- io.projectreactor:reactor-core:jar:3.4.21:compile
[INFO] |     \- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.7.3:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.7.3:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.7.0:test
[INFO] |  |  \- net.minidev:json-smart:jar:2.4.7:test
[INFO] |  |     \- net.minidev:accessors-smart:jar:2.4.7:test
[INFO] |  |        \- org.ow2.asm:asm:jar:9.1:test
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
[INFO] |  +- org.assertj:assertj-core:jar:3.22.0:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.8.2:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-params:jar:5.9.0:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.1:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-test:jar:5.3.22:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.9.0:test
[INFO] +- org.springframework.boot:spring-boot-test:jar:2.7.3:test
[INFO] +- org.springframework.security:spring-security-ldap:jar:5.7.3:compile
[INFO] |  \- org.springframework:spring-tx:jar:5.3.22:compile
[INFO] +- org.springframework.security:spring-security-crypto:jar:5.7.3:compile
[INFO] +- javax.servlet:javax.servlet-api:jar:4.0.1:compile
[INFO] +- io.jsonwebtoken:jjwt:jar:0.9.1:compile
[INFO] +- org.odpi.egeria:asset-catalog-client:jar:3.12-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:rest-client-connectors-api:jar:3.12-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:ocf-metadata-client:jar:3.12-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:asset-catalog-topic-connector:jar:3.12-SNAPSHOT:compile
[INFO] |  \- org.odpi.egeria:ocf-metadata-api:jar:3.12-SNAPSHOT:compile
[INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.9.0:test
[INFO] |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  +- org.junit.platform:junit-platform-commons:jar:1.9.0:test
[INFO] |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] +- org.junit.jupiter:junit-jupiter-engine:jar:5.9.0:test
[INFO] |  \- org.junit.platform:junit-platform-engine:jar:1.9.0:test
[INFO] +- ch.qos.logback:logback-classic:jar:1.3.0:runtime
[INFO] |  \- ch.qos.logback:logback-core:jar:1.3.0:compile
[INFO] +- org.mockito:mockito-junit-jupiter:jar:4.7.0:test
[INFO] +- org.mockito:mockito-inline:jar:4.7.0:test
[INFO] +- org.mockito:mockito-core:jar:4.7.0:test
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.12.13:test
[INFO] |  +- net.bytebuddy:byte-buddy-agent:jar:1.12.13:test
[INFO] |  \- org.objenesis:objenesis:jar:3.2:test
[INFO] +- org.odpi.egeria:http-helper:jar:3.12-SNAPSHOT:compile
[INFO] +- org.odpi.egeria:repository-services-apis:jar:3.12-SNAPSHOT:compile
[INFO] +- org.odpi.egeria:repository-services-client:jar:3.12-SNAPSHOT:compile
[INFO] |  \- org.odpi.egeria:rest-client-factory:jar:3.12-SNAPSHOT:compile
[INFO] +- org.odpi.egeria:open-connector-framework:jar:3.12-SNAPSHOT:compile
[INFO] +- org.springframework.boot:spring-boot-autoconfigure:jar:2.7.3:compile
[INFO] +- org.springframework:spring-webmvc:jar:5.3.22:compile
[INFO] |  \- org.springframework:spring-expression:jar:5.3.22:compile
[INFO] +- org.springframework:spring-context:jar:5.3.22:compile
[INFO] +- org.springframework.security:spring-security-config:jar:5.7.3:compile
[INFO] +- org.springframework.security:spring-security-core:jar:5.7.3:compile
[INFO] +- org.springframework:spring-web:jar:5.3.22:compile
[INFO] +- org.springframework.boot:spring-boot:jar:2.7.3:compile
[INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:2.7.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.7.3:compile
[INFO] |  |  \- org.springframework.boot:spring-boot-actuator:jar:2.7.3:compile
[INFO] |  \- io.micrometer:micrometer-core:jar:1.9.3:compile
[INFO] |     +- org.hdrhistogram:HdrHistogram:jar:2.1.12:compile
[INFO] |     \- org.latencyutils:LatencyUtils:jar:2.0.3:runtime
[INFO] +- io.micrometer:micrometer-registry-prometheus:jar:1.9.3:compile
[INFO] |  \- io.prometheus:simpleclient_common:jar:0.15.0:compile
[INFO] |     \- io.prometheus:simpleclient:jar:0.15.0:compile
[INFO] |        +- io.prometheus:simpleclient_tracer_otel:jar:0.15.0:compile
[INFO] |        |  \- io.prometheus:simpleclient_tracer_common:jar:0.15.0:compile
[INFO] |        \- io.prometheus:simpleclient_tracer_otel_agent:jar:0.15.0:compile
[INFO] +- org.springframework:spring-beans:jar:5.3.22:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.13.3:compile
[INFO] +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO] |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.3:compile
[INFO] +- org.slf4j:slf4j-api:jar:2.0.0:compile
[INFO] +- org.springframework:spring-core:jar:5.3.22:compile
[INFO] |  \- org.springframework:spring-jcl:jar:5.3.22:compile
[INFO] +- org.odpi.egeria:asset-catalog-api:jar:3.12-SNAPSHOT:compile
[INFO] |  \- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] +- org.springframework.security:spring-security-web:jar:5.7.3:compile
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.13.3:compile
[INFO] +- org.odpi.egeria:open-lineage-services-client:jar:3.12-SNAPSHOT:compile
[INFO] +- org.odpi.egeria:open-lineage-services-api:jar:3.12-SNAPSHOT:compile
[INFO] |  \- org.odpi.egeria:asset-lineage-api:jar:3.12-SNAPSHOT:compile
[INFO] +- org.odpi.egeria:ffdc-services:jar:3.12-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:spring-rest-client-connector:jar:3.12-SNAPSHOT:compile
[INFO] |  |  \- org.codehaus.plexus:plexus-utils:jar:3.4.2:compile
[INFO] |  \- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO] +- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO] +- commons-io:commons-io:jar:2.11.0:compile
[INFO] +- org.odpi.egeria:audit-log-framework:jar:3.12-SNAPSHOT:compile
[INFO] +- org.odpi.egeria:glossary-view-client:jar:3.12-SNAPSHOT:compile
[INFO] +- org.odpi.egeria:glossary-view-api:jar:3.12-SNAPSHOT:compile
[INFO] +- org.odpi.egeria:admin-services-api:jar:3.12-SNAPSHOT:compile
[INFO] +- org.odpi.egeria:tex-view-server:jar:3.12-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:tex-view-api:jar:3.12-SNAPSHOT:compile
[INFO] |  \- org.odpi.egeria:multi-tenant:jar:3.12-SNAPSHOT:compile
[INFO] |     +- org.odpi.egeria:metadata-security-server:jar:3.12-SNAPSHOT:compile
[INFO] |     |  +- org.odpi.egeria:metadata-security-apis:jar:3.12-SNAPSHOT:compile
[INFO] |     |  \- org.odpi.egeria:metadata-security-connectors:jar:3.12-SNAPSHOT:compile
[INFO] |     +- org.odpi.egeria:repository-handler:jar:3.12-SNAPSHOT:compile
[INFO] |     +- org.odpi.egeria:engine-host-services-registration:jar:3.12-SNAPSHOT:compile
[INFO] |     |  \- org.odpi.egeria:engine-host-services-api:jar:3.12-SNAPSHOT:compile
[INFO] |     +- org.odpi.egeria:integration-daemon-services-registration:jar:3.12-SNAPSHOT:compile
[INFO] |     +- org.odpi.egeria:governance-action-framework:jar:3.12-SNAPSHOT:compile
[INFO] |     \- org.odpi.egeria:integration-daemon-services-api:jar:3.12-SNAPSHOT:compile
[INFO] +- org.odpi.egeria:tex-view-spring:jar:3.12-SNAPSHOT:runtime
[INFO] +- org.odpi.egeria:rex-view-server:jar:3.12-SNAPSHOT:compile
[INFO] |  \- org.odpi.egeria:rex-view-api:jar:3.12-SNAPSHOT:compile
[INFO] +- org.odpi.egeria:rex-view-spring:jar:3.12-SNAPSHOT:runtime
[INFO] +- org.odpi.egeria:dino-view-server:jar:3.12-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:dino-view-api:jar:3.12-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:platform-services-client:jar:3.12-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:admin-services-client:jar:3.12-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:platform-services-api:jar:3.12-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:governance-engine-api:jar:3.12-SNAPSHOT:compile
[INFO] |  \- org.odpi.egeria:governance-engine-client:jar:3.12-SNAPSHOT:compile
[INFO] |     \- org.odpi.egeria:governance-engine-topic-connectors:jar:3.12-SNAPSHOT:compile
[INFO] +- org.odpi.egeria:dino-view-spring:jar:3.12-SNAPSHOT:runtime
[INFO] +- org.odpi.egeria:admin-services-registration:jar:3.12-SNAPSHOT:compile
[INFO] +- org.springframework.ldap:spring-ldap-core:jar:2.4.1:compile
[INFO] +- junit:junit:jar:4.13.2:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.65:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.24:provided
[INFO] +- org.springdoc:springdoc-openapi-ui:jar:1.6.11:compile
[INFO] |  +- org.springdoc:springdoc-openapi-webmvc-core:jar:1.6.11:compile
[INFO] |  |  \- org.springdoc:springdoc-openapi-common:jar:1.6.11:compile
[INFO] |  |     \- io.swagger.core.v3:swagger-core:jar:2.2.2:compile
[INFO] |  |        +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.13.3:compile
[INFO] |  |        \- io.swagger.core.v3:swagger-models:jar:2.2.2:compile
[INFO] |  +- org.webjars:swagger-ui:jar:4.14.0:compile
[INFO] |  +- org.webjars:webjars-locator-core:jar:0.50:compile
[INFO] |  \- io.github.classgraph:classgraph:jar:4.8.149:compile
[INFO] +- io.swagger.core.v3:swagger-annotations:jar:2.2.2:compile
[INFO] \- org.slf4j:slf4j-simple:jar:2.0.0:test
```

**Comment by planetf1** [comment]
Will
 - remove this update from the dependabot set for Sep
 - contact the logback team to see if it's a bug/known issue

**Comment by planetf1** [comment]
Responses on mailing list indicate that logback now uses 'ServiceLoader' to find providers - could it be that this is causing a problem in Spring apps (which have their own loader) .... ??

**Comment by planetf1** [comment]
The issue is likely spring:

* https://github.com/spring-projects/spring-boot/issues/12649
* https://github.com/spring-projects/spring-boot/issues/32182

Will see how things develop and whether the 2.x stream will work -possibly with upcoming updates
