### ISSUE TITLE
[BUG] Error in GlossarycontextHandler

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#7227]
### Current Behavior

Exception when running he sample lineage integration connector. It creates a glossaryTerm that is then checked to see if it has lineage relationships, unfortunately GlossaryContextHandler line 224 has this code
```
        return CollectionUtils.isNotEmpty(getTermCategorizations(userId, entityDetailGUID, entityDetail.getType().getTypeDefGUID()));
    }
```
The last parameter is incorrect - as the called code wants this to be the typename. The guid to checked to see if it a valid typename and an error occurs. 

Tue Dec 06 14:22:40 GMT 2022 cocoMDS1 Event OMAS-IT-INFRASTRUCTURE-0013 The IT Infrastructure Open Metadata Access Service (OMAS) has sent event of type: Element Reclassified
Tue Dec 06 14:22:40 GMT 2022 cocoMDS1 Event OMAS-ASSET-CONSUMER-0012 The Asset Consumer Open Metadata Access Service (OMAS) has sent event of type: Element Reclassified
Tue Dec 06 14:22:40 GMT 2022 cocoMDS1 Event OMAS-ASSET-OWNER-0012 The Asset Owner Open Metadata Access Service (OMAS) has sent event of type: Element Reclassified
Tue Dec 06 14:22:40 GMT 2022 cocoMDS1 Exception OMAG-REPOSITORY-HANDLER-0003 An unexpected error org.odpi.openmetadata.frameworks.connectors.ffdc.InvalidParameterException was returned to validateEntityGUID by the metadata server during getRelationshipsByType request for open metadata access service Asset Lineage OMAS on server cocoMDS1; message was OMAG-REPOSITORY-HANDLER-404-001 The validateEntityGUID method has retrieved a object for unique identifier (guid) a96f12f4-76f6-458a-9287-de34f6e217ea which is of type GlossaryTerm rather than type 0db3e6ec-f5ef-4d75-ae38-b7ee6fd6ec0a on behalf of method getRelationshipsByType
Tue Dec 06 14:22:40 GMT 2022 cocoMDS1 Exception OMAG-REPOSITORY-HANDLER-0003 Supplementary information: log record id 24306f51-9d3b-4715-ac19-b31d9a8b1309 org.odpi.openmetadata.frameworks.connectors.ffdc.InvalidParameterException returned message of OMAG-REPOSITORY-HANDLER-404-001 The validateEntityGUID method has retrieved a object for unique identifier (guid) a96f12f4-76f6-458a-9287-de34f6e217ea which is of type GlossaryTerm rather than type 0db3e6ec-f5ef-4d75-ae38-b7ee6fd6ec0a on behalf of method getRelationshipsByType and stacktrace of 
InvalidParameterException{parameterName='guid', reportedHTTPCode=404, reportingClassName='org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryErrorHandler', reportingActionDescription='getRelationshipsByType', reportedErrorMessage='OMAG-REPOSITORY-HANDLER-404-001 The validateEntityGUID method has retrieved a object for unique identifier (guid) a96f12f4-76f6-458a-9287-de34f6e217ea which is of type GlossaryTerm rather than type 0db3e6ec-f5ef-4d75-ae38-b7ee6fd6ec0a on behalf of method getRelationshipsByType', reportedErrorMessageId='OMAG-REPOSITORY-HANDLER-404-001', reportedErrorMessageParameters=[validateEntityGUID, a96f12f4-76f6-458a-9287-de34f6e217ea, GlossaryTerm, 0db3e6ec-f5ef-4d75-ae38-b7ee6fd6ec0a, getRelationshipsByType], reportedSystemAction='The service is not able to return the requested object.', reportedUserAction='Check that the unique identifier is correct and the metadata server(s) supporting the service is running.', reportedCaughtException=null, reportedCaughtExceptionClassName='null', relatedProperties=null}
	at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryErrorHandler.handleWrongTypeForGUIDException(RepositoryErrorHandler.java:547)
	at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryErrorHandler.validateInstanceType(RepositoryErrorHandler.java:342)
	at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryHandler.validateEntityGUID(RepositoryHandler.java:138)
	at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryHandler.getEntityByGUID(RepositoryHandler.java:2974)
	at org.odpi.openmetadata.commonservices.generichandlers.OpenMetadataAPIGenericHandler.getAttachmentLinks(OpenMetadataAPIGenericHandler.java:5007)
	at org.odpi.openmetadata.commonservices.generichandlers.OpenMetadataAPIGenericHandler.getAttachmentLinks(OpenMetadataAPIGenericHandler.java:4940)
	at org.odpi.openmetadata.accessservices.assetlineage.handlers.HandlerHelper.getRelationshipsByType(HandlerHelper.java:112)
	at org.odpi.openmetadata.accessservices.assetlineage.handlers.GlossaryContextHandler.getTermCategorizations(GlossaryContextHandler.java:173)
	at org.odpi.openmetadata.accessservices.assetlineage.handlers.GlossaryContextHandler.hasGlossaryTermLineageRelationships(GlossaryContextHandler.java:224)
	at org.odpi.openmetadata.accessservices.assetlineage.outtopic.AssetLineagePublisher.isEntityEligibleForPublishing(AssetLineagePublisher.java:412)
	at org.odpi.openmetadata.accessservices.assetlineage.listeners.AssetLineageOMRSTopicListener.publishEntityEvent(AssetLineageOMRSTopicListener.java:288)
	at org.odpi.openmetadata.accessservices.assetlineage.listeners.AssetLineageOMRSTopicListener.processUpdatedEntity(AssetLineageOMRSTopicListener.java:190)
	at org.odpi.openmetadata.accessservices.assetlineage.listeners.AssetLineageOMRSTopicListener.processInstanceEvent(AssetLineageOMRSTopicListener.java:123)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicListenerWrapper.processInstanceEvent(OMRSTopicListenerWrapper.java:165)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.processOMRSEvent(OMRSTopicConnector.java:576)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.lambda$processEvent$0(OMRSTopicConnector.java:513)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.processEvent(OMRSTopicConnector.java:509)
	at org.odpi.openmetadata.repositoryservices.connectors.openmetadatatopic.OpenMetadataTopicConnector.distributeEvent(OpenMetadataTopicConnector.java:163)
	at org.odpi.openmetadata.repositoryservices.connectors.openmetadatatopic.OpenMetadataTopicConnector.run(OpenMetadataTopicConnector.java:121)
	at java.base/java.lang.Thread.run(Thread.java:829)

Tue Dec 06 14:22:40 GMT 2022 cocoMDS1 Event OMAS-ASSET-MANAGER-0013 The Asset Manager Open Metadata Access Service (OMAS) has sent event of type: Element Updated
Tue Dec 06 14:22:40 GMT 2022 cocoMDS1 Event OMAS-IT-INFRASTRUCTURE-0013 The IT Infrastructure Open Metadata Access Service (OMAS) has sent event of type: Element Updated
Tue Dec 06 14:22:40 GMT 2022 cocoMDS1 Event OMAS-DATA-MANAGER-0013 The Data Manager Open Metadata Access Service (OMAS) has sent event of type: Element Updated
Tue Dec 06 14:22:40 GMT 2022 cocoMDS1 Event OMAS-DIGITAL-ARCHITECTURE-0012 The Digital Architecture Open Metadata Access Service (OMAS) has sent event of type: Element Updated

### Expected Behavior

no error

### Steps To Reproduce

run the sample lineage connector , sample1 then sample2 shows the error in the log.

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by mandy-chessell** [comment]
This issue is in Asset Lineage OMAS - reproduction instructions should also say that Asset Lineage OMAS should also be enabled.  (This OMAS is not used by the sample connector.)
