### ISSUE TITLE
[BUG] HTTP Request errors noted when trying to use notebooks

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#7313]
### Current Behavior

When trying to run the basic configuration notebook in the clean environment, for the first time:
```
Checking OMAG Server Platform availability...
Exception: HTTPSConnectionPool(host='localhost', port=9443): Max retries exceeded with url: /open-metadata/platform-services/users/garygeeke/server-platform/origin (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106fcd3d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
    Core Platform is down - start it before proceeding
    Data Lake Platform is active
        Checking OMAG Server cocoMDS1
           ... cocoMDS1 needs configuring
        Checking OMAG Server cocoMDS4
           ... cocoMDS4 needs configuring
        Checking OMAG Server cocoView1
           ... cocoView1 needs configuring
        Checking OMAG Server cocoOLS1
           ... cocoOLS1 needs configuring
    Dev Platform is active
        Checking OMAG Server cocoMDSx
           ... cocoMDSx needs configuring
Done.
 
 ```

### Expected Behavior

no errors shows

### Steps To Reproduce

Run the notebooks - using 'main' of both the notebooks and egeria

### Environment

```markdown
- Egeria: 3.15-SNAPSHOT
- OS: macOS 13.2
- Java: 11 (temurin)
- Browser (for UI issues):
- Additional connectors and integration:
None (empty additional lib directory)
```

### Any Further Information?

Debug log shows:
```
2023-01-11 12:09:31.757 DEBUG 13017 --- [nio-9444-exec-6] o.o.o.f.connectors.ConnectorBroker       : Using Connection: data/servers/cocoOLS1/config/cocoOLS1.config(null)
2023-01-11 12:09:31.757 DEBUG 13017 --- [nio-9444-exec-6] o.o.o.f.connectors.ConnectorBroker       : <== ConnectorBroker.getConnector
2023-01-11 12:09:31.758 DEBUG 13017 --- [nio-9444-exec-6] o.o.o.a.server.OMAGServerAdminServices   : 3:OMAG Server Operational Services:cocoOLS1:getStoredConfiguration call invoked by garygeeke returned with response OMAGServerConfigResponse{, OMAGServerConfig=OMAGServerConfig{versionId='V2.0', localServerId='f7e07366-ef6d-478c-bfea-5fdff497a4fd', localServerName='cocoOLS1', localServerType='Open Metadata and Governance Server', organizationName='null', localServerURL='https://localhost:9443', localServerUserId='OMAGServer', localServerPassword='null', maxPageSize=1000, serverSecurityConnection=null, eventBusConfig=null, accessServicesConfig=null, integrationServicesConfig=null, engineHostServicesConfig=null, viewServicesConfig=null, repositoryServicesConfig=null, conformanceSuiteConfig=null, openLineageServerConfig=null, dataEngineProxyConfig=null, auditTrail=null}, exceptionClassName='null', exceptionCausedBy='null', actionDescription='null', relatedHTTPCode=200, exceptionErrorMessage='null', exceptionErrorMessageId='null', exceptionErrorMessageParameters=null, exceptionSystemAction='null', exceptionUserAction='null', exceptionProperties=null}; Duration: 0seconds
2023-01-11 12:09:31.758 DEBUG 13017 --- [nio-9444-exec-6] o.a.coyote.http11.Http11InputBuffer      : Before fill(): parsingHeader: [true], parsingRequestLine: [true], parsingRequestLinePhase: [0], parsingRequestLineStart: [0], byteBuffer.position(): [0], byteBuffer.limit(): [0], end: [256]
2023-01-11 12:09:31.758 DEBUG 13017 --- [nio-9444-exec-6] o.a.tomcat.util.net.SocketWrapperBase    : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@2665863c:org.apache.tomcat.util.net.SecureNioChannel@4efa9aa2:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:9444 remote=/0:0:0:0:0:0:0:1:54987]], Read from buffer: [0]
2023-01-11 12:09:31.758 DEBUG 13017 --- [nio-9444-exec-6] org.apache.tomcat.util.net.NioEndpoint   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@2665863c:org.apache.tomcat.util.net.SecureNioChannel@4efa9aa2:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:9444 remote=/0:0:0:0:0:0:0:1:54987]], Read direct from socket: [0]
2023-01-11 12:09:31.759 DEBUG 13017 --- [nio-9444-exec-6] o.a.coyote.http11.Http11InputBuffer      : Received []
2023-01-11 12:09:31.759 DEBUG 13017 --- [nio-9444-exec-6] o.apache.coyote.http11.Http11Processor   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@2665863c:org.apache.tomcat.util.net.SecureNioChannel@4efa9aa2:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:9444 remote=/0:0:0:0:0:0:0:1:54987]], Status in: [OPEN_READ], State out: [OPEN]
2023-01-11 12:09:31.759 DEBUG 13017 --- [nio-9444-exec-6] org.apache.tomcat.util.net.NioEndpoint   : Registered read interest for [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@2665863c:org.apache.tomcat.util.net.SecureNioChannel@4efa9aa2:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:9444 remote=/0:0:0:0:0:0:0:1:54987]]
2023-01-11 12:09:31.759 DEBUG 13017 --- [nio-9444-exec-7] o.a.coyote.http11.Http11InputBuffer      : Before fill(): parsingHeader: [true], parsingRequestLine: [true], parsingRequestLinePhase: [0], parsingRequestLineStart: [0], byteBuffer.position(): [0], byteBuffer.limit(): [0], end: [256]
2023-01-11 12:09:31.759 DEBUG 13017 --- [nio-9444-exec-7] o.a.tomcat.util.net.SocketWrapperBase    : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@2665863c:org.apache.tomcat.util.net.SecureNioChannel@4efa9aa2:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:9444 remote=/0:0:0:0:0:0:0:1:54987]], Read from buffer: [0]
2023-01-11 12:09:31.759 DEBUG 13017 --- [nio-9444-exec-7] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header

java.io.EOFException: null
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1340) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1227) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:805) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:360) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:271) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

2023-01-11 12:09:31.759 DEBUG 13017 --- [nio-9444-exec-7] o.apache.coyote.http11.Http11Processor   : Error state [CLOSE_CONNECTION_NOW] reported while processing request

java.io.EOFException: null
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1340) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1227) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:805) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:360) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:271) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.70.jar!/:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

2023-01-11 12:09:31.759 DEBUG 13017 --- [nio-9444-exec-7] o.apache.coyote.http11.Http11Processor   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@2665863c:org.apache.tomcat.util.net.SecureNioChannel@4efa9aa2:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:9444 remote=/0:0:0:0:0:0:0:1:54987]], Status in: [OPEN_READ], State out: [CLOSED]
2023-01-11 12:09:31.759 DEBUG 13017 --- [nio-9444-exec-7] o.apache.tomcat.util.threads.LimitLatch  : Counting down[https-jsse-nio-9444-exec-7] latch=1
2023-01-11 12:09:31.759 DEBUG 13017 --- [nio-9444-exec-7] org.apache.tomcat.util.net.NioEndpoint   : Calling [org.apache.tomcat.util.net.NioEndpoint@722cc4aa].closeSocket([org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@2665863c:org.apache.tomcat.util.net.SecureNioChannel@4efa9aa2:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:9444 remote=/0:0:0:0:0:0:0:1:54987]])
2023-01-11 12:09:57.227 DEBUG 13017 --- [alina-utility-1] org.apache.catalina.session.ManagerBase  : Start expire sessions StandardManager at 1673438997227 sessioncount 0
2023-01-11 12:09:57.228 DEBUG 13017 --- [alina-utility-1] org.apache.catalina.session.ManagerBase  : End expire sessions StandardManager processingTime 1 expired sessions: 0
2023-01-11 12:10:57.251 DEBUG 13017 --- [alina-utility-1] org.apache.catalina.session.ManagerBase  : Start expire sessions StandardManager at 1673439057251 sessioncount 0
2023-01-11 12:10:57.252 DEBUG 13017 --- [alina-utility-1] org.apache.catalina.session.ManagerBase  : End expire sessions StandardManager processingTime 1 expired sessions: 0
[I 2023-01-11 12:11:21.950 ServerApp] Saving file at /egeria-server-config.ipynb
```

**Comment by planetf1** [comment]
* Verified in container environment (with latest container image from main) - issue does not occur.

**Comment by planetf1** [comment]
Very odd, seemed to be fine after a reboot. system resource exhaustion/error? Closing as environment/user error
