### ISSUE TITLE
Connector fails to import any metadata on version 4

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#7566]
Tested with Postgres -- but likely affects all sources
Using helm deployment of lab chart, with postgres notebook

Servers start correctly, however only one node 'postgres' is visible in the graph - no tables/columns are imported

The cause appears to be:
```
Fri Mar 24 12:32:04 GMT 2023 intserv Exception JDBC-INTEGRATION-CONNECTOR-0006 Supplementary information: log record id 4f8d20b4-e322-457e-a046-19b7798eaf9c org.odpi.openmetadata.commonservices.ffdc.exceptions.InvalidParameterException returned message of OMAG-COMMON-400-004 The user identifier (user id) passed on the createDatabase operation is null and stacktrace of
InvalidParameterException{parameterName='userId', reportedHTTPCode=400, reportingClassName='org.odpi.openmetadata.commonservices.ffdc.InvalidParameterHandler', reportingActionDescription='createDatabase', reportedErrorMessage='OMAG-COMMON-400-004 The user identifier (user id) passed on the createDatabase operation is null', reportedErrorMessageId='OMAG-COMMON-400-004', reportedErrorMessageParameters=[createDatabase], reportedSystemAction='The system is unable to process the request without a user id.', reportedUserAction='Correct the code in the caller to provide the user id.', reportedCaughtException=null, reportedCaughtExceptionClassName='null', relatedProperties=null}
        at org.odpi.openmetadata.commonservices.ffdc.InvalidParameterHandler.validateUserId(InvalidParameterHandler.java:121)
        at org.odpi.openmetadata.accessservices.datamanager.client.DataManagerBaseClient.createReferenceable(DataManagerBaseClient.java:207)
        at org.odpi.openmetadata.accessservices.datamanager.client.DatabaseManagerClient.createDatabase(DatabaseManagerClient.java:154)
        at org.odpi.openmetadata.integrationservices.database.connector.DatabaseIntegratorContext.createDatabase(DatabaseIntegratorContext.java:154)
        at org.odpi.openmetadata.adapters.connectors.integration.jdbc.transfer.requests.OmasCreateDatabase.apply(OmasCreateDatabase.java:42)
        at org.odpi.openmetadata.adapters.connectors.integration.jdbc.transfer.requests.Omas.createDatabase(Omas.java:115)
        at org.odpi.openmetadata.adapters.connectors.integration.jdbc.transfer.DatabaseTransfer.execute(DatabaseTransfer.java:50)
        at org.odpi.openmetadata.adapters.connectors.integration.jdbc.transfer.JdbcMetadataTransfer.execute(JdbcMetadataTransfer.java:72)
        at org.odpi.openmetadata.adapters.connectors.integration.jdbc.JdbcIntegrationConnector.refresh(JdbcIntegrationConnector.java:67)
        at org.odpi.openmetadata.governanceservers.integrationdaemonservices.handlers.IntegrationConnectorHandler.refreshConnector(IntegrationConnectorHandler.java:552)
        at org.odpi.openmetadata.governanceservers.integrationdaemonservices.threads.IntegrationDaemonThread.run(IntegrationDaemonThread.java:99)
        at java.base/java.lang.Thread.run(Thread.java:833)

Fri Mar 24 12:32:04 GMT 2023 intserv Exception JDBC-INTEGRATION-CONNECTOR-0008 Error reading data from OMAS in method OmasGetDatabasesByName. Possible message is OMAG-COMMON-400-004 The user identifier (user id) passed on the getDatabasesByName operation is null
Fri Mar 24 12:32:04 GMT 2023 intserv Information JDBC-INTEGRATION-CONNECTOR-0007 Exiting from method JdbcMetadataTransfer.execute as a result of a failed database transfer
```
cc: @dwolfson @mandy-chessell

**Comment by planetf1** [comment]
This is working now
