### ISSUE TITLE
CTS failing (graph, xtdb) for last 2 days — since dependabot updates

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#7618]
For the last two dats CTS is failing.

See https://github.com/odpi/egeria-test-cts/actions
 - Graph fails with a functional issue
 - XTDB is timing out after 6 hours
 
 Whilst these may be transient, two PRs were merged on Friday which could have impacted CTS: (prior to Friday the tests were clean)
 
 * #7612
 * #7616

**Comment by planetf1** [comment]
Reviewing the included commits, none immediately stand-out as the cause of the regression. However we have now had multiple days of failure.

I therefore plan to create a test branch to run cts against. This will be set with HEAD at the commit immediately prior to the dependabot changes. 

First I will check that runs clear. If not, there is some other kind of infra issue.
If it does, I will experiment with re-adding selected commits

This will ensure the problem can be examined in an environment nearly the same as that within which it is failing (and impact other work less)

**Comment by planetf1** [comment]
Running at https://github.com/odpi/egeria-test-cts/actions/runs/4741352134

**Comment by planetf1** [comment]
@lpalashevski @alexandra-bucur 

elasticsearch was updated 8.6.2 -> 8.7.0 in https://github.com/odpi/egeria/pull/7612/commits/bf6276b8a377940198c876fb52f9c10ee4114748

This also pulls in some lucene update

I'll start a CTS run reverting this commit

**Comment by alexandra-bucur** [comment]
@planetf1 I tried to use the graph with the older version and does not seem to work. Do you think it's related?

 `Apr 19 15:49:13 : 2023-04-19 15:49:13.785 ERROR [http-nio-127.0.0.1-8080-exec-5] [o.j.g.database.StandardJanusGraph] --- Error while committing index mutations for transaction [823] on index: search
Apr 19 15:49:13 : org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception
Apr 19 15:49:13 : at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:54)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.indexing.IndexTransaction.flushInternal(IndexTransaction.java:158)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.indexing.IndexTransaction.commit(IndexTransaction.java:139)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.BackendTransaction.commitIndexes(BackendTransaction.java:143)
Apr 19 15:49:13 : at org.janusgraph.graphdb.database.StandardJanusGraph.commit(StandardJanusGraph.java:804)
Apr 19 15:49:13 : at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1525)
Apr 19 15:49:13 : at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph$GraphTransaction.doCommit(JanusGraphBlueprintsGraph.java:322)
Apr 19 15:49:13 : at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:104)
Apr 19 15:49:13 : at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph$GraphTransaction.commit(JanusGraphBlueprintsGraph.java:300)
Apr 19 15:49:13 : at org.odpi.openmetadata.adapters.repositoryservices.graphrepository.repositoryconnector.GraphOMRSMetadataStore.createRelationshipInStore(GraphOMRSMetadataStore.java:924)
Apr 19 15:49:13 : at org.odpi.openmetadata.adapters.repositoryservices.graphrepository.repositoryconnector.GraphOMRSMetadataCollection.addRelationship(GraphOMRSMetadataCollection.java:495)
Apr 19 15:49:13 : at org.odpi.openmetadata.repositoryservices.localrepository.repositoryconnector.LocalOMRSMetadataCollection.addRelationship(LocalOMRSMetadataCollection.java:4863)
Apr 19 15:49:13 : at org.odpi.openmetadata.repositoryservices.enterprise.repositoryconnector.executors.AddRelationshipExecutor.issueRequestToRepository(AddRelationshipExecutor.java:140)
Apr 19 15:49:13 : at org.odpi.openmetadata.repositoryservices.enterprise.repositoryconnector.control.SequentialFederationControl.executeCommand(SequentialFederationControl.java:60)
Apr 19 15:49:13 : at org.odpi.openmetadata.repositoryservices.enterprise.repositoryconnector.EnterpriseOMRSMetadataCollection.addRelationship(EnterpriseOMRSMetadataCollection.java:3855)
Apr 19 15:49:13 : at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryHandler.createRelationship(RepositoryHandler.java:5302)
Apr 19 15:49:13 : at org.odpi.openmetadata.commonservices.generichandlers.OpenMetadataAPIGenericHandler.maintainSupplementaryProperties(OpenMetadataAPIGenericHandler.java:4066)
Apr 19 15:49:13 : at org.odpi.openmetadata.accessservices.assetmanager.handlers.ExchangeHandlerBase.maintainSupplementaryProperties(ExchangeHandlerBase.java:506)
Apr 19 15:49:13 : at org.odpi.openmetadata.accessservices.assetmanager.handlers.ProcessExchangeHandler.createProcess(ProcessExchangeHandler.java:318)
Apr 19 15:49:13 : at org.odpi.openmetadata.accessservices.assetmanager.server.LineageExchangeRESTServices.createProcess(LineageExchangeRESTServices.java:80)
Apr 19 15:49:13 : at org.odpi.openmetadata.accessservices.assetmanager.server.spring.LineageExchangeResource.createProcess(LineageExchangeResource.java:62)
Apr 19 15:49:13 : at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
Apr 19 15:49:13 : at java.base/java.lang.reflect.Method.invoke(Method.java:577)
Apr 19 15:49:13 : at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
Apr 19 15:49:13 : at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
Apr 19 15:49:13 : at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
Apr 19 15:49:13 : at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
Apr 19 15:49:13 : at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
Apr 19 15:49:13 : at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
Apr 19 15:49:13 : at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
Apr 19 15:49:13 : at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
Apr 19 15:49:13 : at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
Apr 19 15:49:13 : at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
Apr 19 15:49:13 : at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:563)
Apr 19 15:49:13 : at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
Apr 19 15:49:13 : at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:631)
Apr 19 15:49:13 : at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
Apr 19 15:49:13 : at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
Apr 19 15:49:13 : at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Apr 19 15:49:13 : at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
Apr 19 15:49:13 : at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
Apr 19 15:49:13 : at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
Apr 19 15:49:13 : at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
Apr 19 15:49:13 : at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
Apr 19 15:49:13 : at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
Apr 19 15:49:13 : at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
Apr 19 15:49:13 : at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
Apr 19 15:49:13 : at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
Apr 19 15:49:13 : at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
Apr 19 15:49:13 : at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
Apr 19 15:49:13 : at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
Apr 19 15:49:13 : at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
Apr 19 15:49:13 : at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
Apr 19 15:49:13 : at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
Apr 19 15:49:13 : at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
Apr 19 15:49:13 : at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
Apr 19 15:49:13 : at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
Apr 19 15:49:13 : at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
Apr 19 15:49:13 : at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
Apr 19 15:49:13 : at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
Apr 19 15:49:13 : at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
Apr 19 15:49:13 : at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
Apr 19 15:49:13 : at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
Apr 19 15:49:13 : at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
Apr 19 15:49:13 : at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
Apr 19 15:49:13 : at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
Apr 19 15:49:13 : at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
Apr 19 15:49:13 : at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
Apr 19 15:49:13 : at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
Apr 19 15:49:13 : at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
Apr 19 15:49:13 : at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
Apr 19 15:49:13 : at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
Apr 19 15:49:13 : at java.base/java.lang.Thread.run(Thread.java:833)
Apr 19 15:49:13 : Caused by: org.janusgraph.diskstorage.PermanentBackendException: Permanent exception while executing backend operation IndexMutation
Apr 19 15:49:13 : at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:79)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:52)
Apr 19 15:49:13 : ... 72 common frames omitted
Apr 19 15:49:13 : Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.lucene.codecs.Codec$Holder
Apr 19 15:49:13 : at org.apache.lucene.codecs.Codec.getDefault(Codec.java:143)
Apr 19 15:49:13 : at org.apache.lucene.index.LiveIndexWriterConfig.<init>(LiveIndexWriterConfig.java:132)
Apr 19 15:49:13 : at org.apache.lucene.index.IndexWriterConfig.<init>(IndexWriterConfig.java:160)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.lucene.LuceneIndex.getWriter(LuceneIndex.java:213)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.lucene.LuceneIndex.mutateStores(LuceneIndex.java:289)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.lucene.LuceneIndex.mutate(LuceneIndex.java:275)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:161)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:158)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:66)
Apr 19 15:49:13 : ... 73 common frames omitted
Apr 19 15:49:13 : Caused by: java.lang.ExceptionInInitializerError: Exception java.util.ServiceConfigurationError: Cannot instantiate SPI class: org.apache.lucene.codecs.lucene70.Lucene70Codec [in thread "http-nio-127.0.0.1-8080-exec-1"]
Apr 19 15:49:13 : at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:82)
Apr 19 15:49:13 : at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:51)
Apr 19 15:49:13 : at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:38)
Apr 19 15:49:13 : at org.apache.lucene.codecs.Codec$Holder.<clinit>(Codec.java:47)
Apr 19 15:49:13 : at org.apache.lucene.codecs.Codec.getDefault(Codec.java:143)
Apr 19 15:49:13 : at org.apache.lucene.index.LiveIndexWriterConfig.<init>(LiveIndexWriterConfig.java:132)
Apr 19 15:49:13 : at org.apache.lucene.index.IndexWriterConfig.<init>(IndexWriterConfig.java:160)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.lucene.LuceneIndex.getWriter(LuceneIndex.java:213)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.lucene.LuceneIndex.mutateStores(LuceneIndex.java:289)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.lucene.LuceneIndex.mutate(LuceneIndex.java:275)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:161)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:158)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:66)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:52)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.indexing.IndexTransaction.flushInternal(IndexTransaction.java:158)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.indexing.IndexTransaction.commit(IndexTransaction.java:139)
Apr 19 15:49:13 : at org.janusgraph.diskstorage.BackendTransaction.commitIndexes(BackendTransaction.java:143)
Apr 19 15:49:13 : at org.janusgraph.graphdb.database.StandardJanusGraph.commit(StandardJanusGraph.java:804)
Apr 19 15:49:13 : at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1525)
Apr 19 15:49:13 : at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph$GraphTransaction.doCommit(JanusGraphBlueprintsGraph.java:322)
Apr 19 15:49:13 : at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:104)
Apr 19 15:49:13 : at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph$GraphTransaction.commit(JanusGraphBlueprintsGraph.java:300)
Apr 19 15:49:13 : at org.odpi.openmetadata.adapters.repositoryservices.graphrepository.repositoryconnector.GraphOMRSMetadataStore.createEntityInStore(GraphOMRSMetadataStore.java:281)
Apr 19 15:49:13 : at org.odpi.openmetadata.adapters.repositoryservices.graphrepository.repositoryconnector.GraphOMRSMetadataCollection.addExternalEntity(GraphOMRSMetadataCollection.java:266)
Apr 19 15:49:13 : at org.odpi.openmetadata.repositoryservices.localrepository.repositoryconnector.LocalOMRSMetadataCollection.addExternalEntity(LocalOMRSMetadataCollection.java:3228)
Apr 19 15:49:13 : at org.odpi.openmetadata.repositoryservices.enterprise.repositoryconnector.executors.AddEntityExecutor.issueRequestToRepository(AddEntityExecutor.java:128)
Apr 19 15:49:13 : at org.odpi.openmetadata.repositoryservices.enterprise.repositoryconnector.control.SequentialFederationControl.executeCommand(SequentialFederationControl.java:60)
Apr 19 15:49:13 : at org.odpi.openmetadata.repositoryservices.enterprise.repositoryconnector.EnterpriseOMRSMetadataCollection.addExternalEntity(EnterpriseOMRSMetadataCollection.java:2828)
Apr 19 15:49:13 : at org.odpi.openmetadata.commonservices.repositoryhandler.RepositoryHandler.createEntity(RepositoryHandler.java:577)
Apr 19 15:49:13 : at org.odpi.openmetadata.commonservices.generichandlers.OpenMetadataAPIGenericHandler.createBeanInRepository(OpenMetadataAPIGenericHandler.java:5415)
Apr 19 15:49:13 : at org.odpi.openmetadata.commonservices.generichandlers.AssetHandler.createAssetInRepository(AssetHandler.java:929)
Apr 19 15:49:13 : at org.odpi.openmetadata.commonservices.generichandlers.ProcessHandler.createProcess(ProcessHandler.java:243)
Apr 19 15:49:13 : at org.odpi.openmetadata.accessservices.assetmanager.handlers.ProcessExchangeHandler.createProcess(ProcessExchangeHandler.java:297)
Apr 19 15:49:13 : ... 54 common frames omitted`

**Comment by planetf1** [comment]
@alexandra-bucur I only looked briefly, but it's in graph indexes, so lucene related, and the elastic search update did pull something in. Also XTDB is affected, which is also using lucene.

I've built a fix and just about to kick off CTS (but it takes 3-4 hours to run)

**Comment by planetf1** [comment]
Draft PR: https://github.com/odpi/egeria/pull/7622 - has links to test run & image. Will revisit later/tomorrow.
It may be worth you trying to see if your tests pass with this reversion 

Speculative for now...

**Comment by planetf1** [comment]
the particular error was not finding `org.apache.lucene.codecs.lucene70.Lucene70Codec`. In current versions of lucene it looks as if this is found in `org.apache.lucene:lucene-backward-codecs`. This does seem to be included by org.janusgraph:janusgraph-lucene (8.9.0) both with & without the dependabot updates. So it's not clear backing off addresses your issue.

I will let the CTS run. The issue there may be different (I didn't see this error, but the cts run didn't capture all the log).

**Comment by planetf1** [comment]
See also #7624 -- conclusion is that FVT tests on graph haven't worked in a long time. Will put addressing that to one side & return to the current regression which has happened recently.

**Comment by planetf1** [comment]
CTS test run (graph) on k8s (latest code in main) -
 - Fails as with automated tests
 - no exceptions noted in test results, nor from stdout/stderr/audit log
 - all test failures in  findRelationshipsByProperty or findEntitiesByProperty

**Comment by planetf1** [comment]
The exception trace is the same as yours @alexandra-bucur 

This occurs both at HEAD *AND* prior to the dependabot changes

This suggests the change may in fact have been due to an external source -- perhaps a change in published lucene packages

My initial error (running locally) was due to having some old connectors in my classpath ie
```
Caused by: java.util.ServiceConfigurationError: Cannot instantiate SPI class: org.apache.lucene.codecs.lucene70.Lucene70Codec
        at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:82) ~[egeria-connector-xtdb-3.14-SNAPSHOT-jar-with-dependencies.jar:8.11.1 0b002b11819df70783e83ef36b42ed1223c14b50 - janhoy - 2021-12-14 13:46:43]
 ```
 
 Cleaning and retrying ...
 
 Get exception picking up class from egeria
 ```
 aused by: java.util.ServiceConfigurationError: Cannot instantiate SPI class: org.apache.lucene.codecs.lucene70.Lucene70Codec
Caused by: java.util.ServiceConfigurationError: Cannot instantiate SPI class: org.apache.lucene.codecs.lucene70.Lucene70Codec
        at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:82) ~[graph-repository-connector-jar-with-dependencies-4.1-SNAPSHOT.jar:8.11.1 0b002b11819df70783e83ef36b42ed1223c14b50 - janhoy - 2021-12-14 13:46:43]
        at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:51) ~[graph-repository-connector-jar-with-dependencies-4.1-SNAPSHOT.jar:8.11.1 0b002b11819df70783e83ef36b42ed1223c14b50 - janhoy - 2021-12-14 13:46:43]
```
This seems relevant
```
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.DocValuesFormat with name 'Lucene70' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene80]
```

This implies we need a Lucene 8 implementation

We have lucene constrained to 8.11.1 - Janusgraph prereqs 

Lucene latest version is 9.5 - 8.11.2 is the latest 8.x

Related, elasticsearch is 8.7.0 (lucene 9.5.0)- which is the latest. this was 8.6.2 previously (lucene 9.4.2)

Latest Janusgraph is 0.6.2 (we are using 0.6.1) which prereqs lucene 8.9

Given that reverting dependencies doesn't seem to work (unsure why), other options include
* removing all constraints on lucene -> risk of introducing security vuln
* Updating lucene to latest level (8.11.2, or else 9.5)
* Updating Janusgraph to 0.6.2 
* Updating Janusgraph to 1.0.0-rc-2 (but this isn't final yet)

Try 2
 - update to latest minor versions

**Comment by lpalashevski** [comment]
regression re-testing on our end in progress

**Comment by planetf1** [comment]
* My tests ran repeatedly locally (lab chart, data catalog, graph)
* Previously failing FVT on graph worked (but very slow)
* HOWEVER tests against the built image with lab chart are still failing - despite verifying the correct image is in use
* Launched CTS manually at https://github.com/odpi/egeria-test-cts/actions/runs/4757260867
* CTS will also run overnight on schedule

**Comment by planetf1** [comment]
Cts has failed for graph with the same error as before. I therefore think the fix is not sufficient.

Unsure why it seemed to fix the issue locally

**Comment by planetf1** [comment]
Tested locally 
 - clean build, no cache. Using lucene 8.11.2
 - asset consumer search consistently working
 
 Tested in k8s
  - rebuilt image
  - confirmed it has updates & is using lucene 8.11.2
  - asset consumer search consistently *not* working
  
  @lpalashevski @alexandra-bucur how is your testing going?

**Comment by planetf1** [comment]
CTS succeeded last night.
See https://github.com/odpi/egeria-test-cts/actions/runs/4781958910

Some changes were included from @mandy-chessell though I have no explanation for why this is now working

**Comment by planetf1** [comment]
closing as fixed
