### ISSUE TITLE
Getting LibraryNotFoundError please help me to solve

### ISSUE THREAD

**Issue by sahoor-1999** [odpi/egeria#8049]
**I have been use java- 17 on my local I am getting this issue please help me to fix this.**

<img width="868" alt="image" src="https://github.com/odpi/egeria/assets/157471652/ead800e7-60c3-4516-abd6-0dc4b7364147">

org.apache.tomcat.jni.LibraryNotFoundError: Can't load library: C:\IntelijIDEA Projfile\bloggingAPI\bloggingAPI\bin\tcnative-2.dll, Can't load library: C:\IntelijIDEA Projfile\bloggingAPI\bloggingAPI\bin\libtcnative-2.dll, Can't load library: C:\IntelijIDEA Projfile\bloggingAPI\bloggingAPI\bin\tcnative-1.dll, Can't load library: C:\IntelijIDEA Projfile\bloggingAPI\bloggingAPI\bin\libtcnative-1.dll, no tcnative-2 in java.library.path: C:\Extron\Application\java\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Extron\Application\java\bin;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\sahoo\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.1\bin;C:\Users\sahoo\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\sahoo\AppData\Roaming\npm;., no libtcnative-2 in java.library.path: C:\Extron\Application\java\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Extron\Application\java\bin;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\sahoo\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.1\bin;C:\Users\sahoo\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\sahoo\AppData\Roaming\npm;., no tcnative-1 in java.library.path: C:\Extron\Application\java\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Extron\Application\java\bin;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\sahoo\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.1\bin;C:\Users\sahoo\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\sahoo\AppData\Roaming\npm;., no libtcnative-1 in java.library.path: C:\Extron\Application\java\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Extron\Application\java\bin;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\sahoo\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.1\bin;C:\Users\sahoo\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\sahoo\AppData\Roaming\npm;.
	at org.apache.tomcat.jni.Library.<init>(Library.java:91) ~[tomcat-embed-core-10.1.18.jar:10.1.18]
	at org.apache.tomcat.jni.Library.initialize(Library.java:146) ~[tomcat-embed-core-10.1.18.jar:10.1.18]
	at org.apache.catalina.core.AprLifecycleListener.init(AprLifecycleListener.java:193) ~[tomcat-embed-core-10.1.18.jar:10.1.18]
	at org.apache.catalina.core.AprLifecycleListener.isAprAvailable(AprLifecycleListener.java:107) ~[tomcat-embed-core-10.1.18.jar:10.1.18]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getDefaultServerLifecycleListeners(TomcatServletWebServerFactory.java:189) ~[spring-boot-3.2.2.jar:3.2.2]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.<init>(TomcatServletWebServerFactory.java:136) ~[spring-boot-3.2.2.jar:3.2.2]
	at org.springframework.boot.autoconfigure.web.servlet.ServletWebServerFactoryConfiguration$EmbeddedTomcat.tomcatServletWebServerFactory(ServletWebServerFactoryConfiguration.java:73) ~[spring-boot-autoconfigure-3.2.2.jar:3.2.2]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]

**Comment by sahoor-1999** [comment]
I fixed this
