### ISSUE TITLE
OutOfMemory errors caused by debug logging of incoming Kafka messages

### ISSUE THREAD

**Issue by dkantor** [odpi/egeria#860]
We have seen OutOfMemoryErrors with the following stack trace.  Analysis of heap dump showed a `StringBuilder` instance holding 275MB of memory that is a local variable in `java.util.AbstractCollection.toString()`.
```
java.lang.OutOfMemoryError: Java heap space
    at java.lang.StringBuilder.ensureCapacityImpl(Unknown Source)
    at java.lang.StringBuilder.append(Unknown Source)
    at java.lang.StringBuilder.append(Unknown Source)
    at java.util.AbstractCollection.toString(Unknown Source)
    at java.util.Collections$SynchronizedCollection.toString(Unknown Source)
    at java.lang.String.valueOf(Unknown Source)
    at java.lang.StringBuilder.append(Unknown Source)
    at org.odpi.openmetadata.adapters.eventbus.topic.kafka.KafkaOpenMetadataTopicConnector.checkForEvents(KafkaOpenMetadataTopicConnector.java:246)
    at org.odpi.openmetadata.repositoryservices.connectors.openmetadatatopic.OpenMetadataTopicConnector.run(OpenMetadataTopicConnector.java:96)
    at java.lang.Thread.run(Unknown Source)
```

`KafkaOpenMetadataTopicConnector` at line 246 is logging the contents of `incomingEventsList`:
```
 log.debug("checking for events {0}" + incomingEventsList);
```
At a minimum, the debug logging should be changed to pass incomingEventsList as an argument rather than concatenating it, to avoid the overhead of `incomingEventsList.toString()` if debug is not enabled on the logger.
```
log.debug("checking for events {0}", incomingEventsList);
```
In addition, it would make sense to implement some logging code for efficiently logging the contents of `incomingEventsList` which avoids concatenating the entire contents of the list in a `StringBuilder`.  Perhaps it could log a subset of the events if the list exceeds a certain size.

**Comment by guptaneeru** [comment]
Agree with @dkantor to atleast check the log level. but I would even say to not log this at the debug level. 
On the side note, the real question is why is this collection holding so many messages in memory. Is it something to do with how Kafka was setup?

**Comment by jnhagelberg** [comment]
@guptaneeru The issue is that you can see in KafkaOpenMetadataEventConsumer that the code polls Kafka once every second and adds what it finds to a list.  That needs to be changed so that polling is only done if the number of queued events is small.  That should be done as part of this issue.  It is really the root cause of the issue.  Once that is done, fixing the logging becomes less important (although it does need to be done as well)

**Comment by mandy-chessell** [comment]
I agree with @guptaneeru that we should remove the debug logging of the received list
