### ISSUE TITLE
Incompatible kafka versions

### ISSUE THREAD

**Issue by ruxandraRosu** [odpi/egeria#922]
Current kafka version in atlas is 1.0.0. The OM KafkaTopicConnector requires a higher version, currently used version is 2.1.1

**Comment by planetf1** [comment]
I too see the same issue - atlas' stack trace is
```
2019-04-16 09:22:29,731 INFO  - [pool-1-thread-6 - 808e64d8-c324-415b-90c0-af788cd21b88:] ~ Index creation for type RelationshipAnnotation complete (GraphBackedSearchIndexer:783)
2019-04-16 09:22:30,006 ERROR - [pool-1-thread-6 - 808e64d8-c324-415b-90c0-af788cd21b88:] ~ Unable to initialize cohort manager (OMRSCohortManager:253)
java.lang.NoSuchMethodError: org.apache.kafka.clients.consumer.ConsumerConfig.<init>(Ljava/util/Properties;)V
	at org.apache.kafka.clients.consumer.KafkaConfigurationWrapper.<init>(KafkaConfigurationWrapper.java:21)
	at org.odpi.openmetadata.adapters.eventbus.topic.kafka.KafkaOpenMetadataEventConsumer.<init>(KafkaOpenMetadataEventConsumer.java:93)
	at org.odpi.openmetadata.adapters.eventbus.topic.kafka.KafkaOpenMetadataTopicConnector.start(KafkaOpenMetadataTopicConnector.java:207)
	at org.odpi.openmetadata.repositoryservices.connectors.omrstopic.OMRSTopicConnector.start(OMRSTopicConnector.java:252)
	at org.odpi.openmetadata.repositoryservices.metadatahighway.OMRSCohortManager.initialize(OMRSCohortManager.java:238)
	at org.odpi.openmetadata.repositoryservices.metadatahighway.OMRSMetadataHighwayManager.connectToCohort(OMRSMetadataHighwayManager.java:183)
	at org.odpi.openmetadata.repositoryservices.metadatahighway.OMRSMetadataHighwayManager.initialize(OMRSMetadataHighwayManager.java:97)
	at org.odpi.openmetadata.repositoryservices.admin.OMRSOperationalServices.initializeCohorts(OMRSOperationalServices.java:666)
	at org.odpi.openmetadata.repositoryservices.admin.OMRSOperationalServices.initialize(OMRSOperationalServices.java:412)
	at org.odpi.openmetadata.adminservices.OMAGServerOperationalServices.activateWithSuppliedConfig(OMAGServerOperationalServices.java:206)
	at org.odpi.openmetadata.adminservices.OMAGServerOperationalServices.activateWithStoredConfig(OMAGServerOperationalServices.java:65)
	at org.apache.atlas.openmetadata.admin.server.spring.OpenMetadataAdminResource.activateWithStoredConfig(OpenMetadataAdminResource.java:452)
```


In order to deploy to k8s I need to either
 * Have a fix in the atlas managed fork that I can use
or
 * Add a temporary patch into the docker build of atlas

**Comment by planetf1** [comment]
FAO: @grahamwallis

**Comment by planetf1** [comment]
this looks completely out of date now so closing - reopen if still an issue
